# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
# RUN: llc -mtriple=amdgcn -mcpu=gfx1200 -verify-machineinstrs -run-pass=amdgpu-ssa-register-spiller --amdgpu-ssa-spill-markers=1 -o - %s | FileCheck %s

# Test: Multi-path independent spilling
# Verifies:
# 1. Path A: Register %0 is used before high RP forces spill (cannot hoist to NCD)
# 2. Path B: Also has high RP, independently triggering spill of %0
# 3. Both paths spill %0 to the same stack slot (independent decisions)
# 4. Split-before-use at join point with conditional reload
#
# NOTE: This is NOT coordinated "balanced spilling" (cost model not implemented yet).
# Each path independently decides to spill when RP exceeds limit.

--- |
  target datalayout = "e-p:64:64-p1:64:64-p2:32:32-p3:32:32-p4:64:64-p5:32:32-p6:32:32-i64:64-v16:16-v24:32-v32:32-v48:64-v96:128-v192:256-v256:256-v512:512-v1024:1024-v2048:2048-n32:64-S32-A5-G1-ni:7:8:9"
  target triple = "amdgcn"

  define amdgpu_kernel void @test_multi_path_independent(i32 %cond) #0 {
  entry:
    %cmp = icmp eq i32 %cond, 0
    br i1 %cmp, label %path_a, label %path_b

  path_a:
    br label %path_a_use

  path_a_use:
    br label %join

  path_b:
    br label %join

  join:
    ret void
  }

  attributes #0 = { "amdgpu-num-vgpr"="7" "target-cpu"="gfx1200" }
...
---
name:            test_multi_path_independent
alignment:       1
tracksRegLiveness: true
noPhis:          false
registers:
  - { id: 0, class: vreg_128 }
  - { id: 1, class: vreg_64 }
  - { id: 2, class: vreg_64 }
  - { id: 3, class: sreg_32 }
  - { id: 4, class: vreg_64 }
  - { id: 5, class: vreg_64 }
liveins:
  - { reg: '$vgpr0_vgpr1_vgpr2_vgpr3' }
  - { reg: '$sgpr0' }
stack:
frameInfo:
  maxAlignment:    4
machineFunctionInfo:
  stackPtrOffsetReg: '$sgpr32'
body: |
  ; CHECK-LABEL: name: test_multi_path_independent
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   successors: %bb.1(0x40000000), %bb.3(0x40000000)
  ; CHECK-NEXT:   liveins: $vgpr0_vgpr1_vgpr2_vgpr3, $sgpr0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:vreg_128 = COPY $vgpr0_vgpr1_vgpr2_vgpr3
  ; CHECK-NEXT:   SI_SPILL_V32_SAVE [[COPY]].sub0, %stack.0, $sgpr32, 0, implicit $exec :: (store (s32) into %stack.0, addrspace 5)
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:sreg_32 = COPY $sgpr0
  ; CHECK-NEXT:   S_CMP_EQ_U32 [[COPY1]], 0, implicit-def $scc
  ; CHECK-NEXT:   S_CBRANCH_SCC1 %bb.1, implicit $scc
  ; CHECK-NEXT:   S_BRANCH %bb.3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1.path_a:
  ; CHECK-NEXT:   successors: %bb.2(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   S_NOP 0, implicit [[COPY]]
  ; CHECK-NEXT:   [[DEF:%[0-9]+]]:vreg_64 = IMPLICIT_DEF
  ; CHECK-NEXT:   SI_VIRTUAL_SPILL_MARKER [[COPY]], 0000000000000003
  ; CHECK-NEXT:   [[DEF1:%[0-9]+]]:vreg_64 = IMPLICIT_DEF
  ; CHECK-NEXT:   S_NOP 0, implicit [[DEF]], implicit [[DEF1]]
  ; CHECK-NEXT:   S_BRANCH %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2.path_a_use:
  ; CHECK-NEXT:   successors: %bb.4(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[SI_SPILL_V32_RESTORE:%[0-9]+]]:vgpr_32 = SI_SPILL_V32_RESTORE %stack.0, $sgpr32, 0, implicit $exec :: (load (s32) from %stack.0, addrspace 5)
  ; CHECK-NEXT:   [[REG_SEQUENCE:%[0-9]+]]:vreg_128 = REG_SEQUENCE [[SI_SPILL_V32_RESTORE]], %subreg.sub0, [[COPY]].sub1_sub2_sub3, %subreg.sub1_sub2_sub3
  ; CHECK-NEXT:   S_NOP 0, implicit [[REG_SEQUENCE]]
  ; CHECK-NEXT:   S_BRANCH %bb.4
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3.path_b:
  ; CHECK-NEXT:   successors: %bb.4(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[DEF2:%[0-9]+]]:vreg_64 = IMPLICIT_DEF
  ; CHECK-NEXT:   SI_VIRTUAL_SPILL_MARKER [[COPY]], 0000000000000003
  ; CHECK-NEXT:   [[DEF3:%[0-9]+]]:vreg_64 = IMPLICIT_DEF
  ; CHECK-NEXT:   S_NOP 0, implicit [[DEF2]], implicit [[DEF3]]
  ; CHECK-NEXT:   S_BRANCH %bb.4
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.4.join:
  ; CHECK-NEXT:   [[SI_SPILL_V32_RESTORE1:%[0-9]+]]:vgpr_32 = SI_SPILL_V32_RESTORE %stack.0, $sgpr32, 0, implicit $exec :: (load (s32) from %stack.0, addrspace 5)
  ; CHECK-NEXT:   [[REG_SEQUENCE1:%[0-9]+]]:vreg_128 = REG_SEQUENCE [[SI_SPILL_V32_RESTORE1]], %subreg.sub0, [[COPY]].sub1_sub2_sub3, %subreg.sub1_sub2_sub3
  ; CHECK-NEXT:   S_ENDPGM 0, implicit [[REG_SEQUENCE1]]

  bb.0.entry:
    successors: %bb.1(0x40000000), %bb.2(0x40000000)
    liveins: $vgpr0_vgpr1_vgpr2_vgpr3, $sgpr0

    ; Define register that will be spilled on both paths
    %0:vreg_128 = COPY $vgpr0_vgpr1_vgpr2_vgpr3

    ; Branch condition
    %3:sreg_32 = COPY $sgpr0
    S_CMP_EQ_U32 %3, 0, implicit-def $scc
    S_CBRANCH_SCC1 %bb.1, implicit $scc
    S_BRANCH %bb.2

  ; Path A: Use before spill (cannot hoist to NCD)

  bb.1.path_a:
    successors: %bb.4(0x80000000)

    ; Early use of %0 - prevents hoisting spill to NCD
    S_NOP 0, implicit %0

    ; High RP forcing %0 to be spilled
    %1:vreg_64 = IMPLICIT_DEF
    %2:vreg_64 = IMPLICIT_DEF
    ; %0 (4 VGPRs) + %1 (2 VGPRs) + %2 (2 VGPRs) = 8 VGPRs (exceeds limit of 7)
    ; Only %0 can be spilled (%1 and %2 are used immediately below)
    S_NOP 0, implicit %1, implicit %2
    ; %1 and %2 die, %0 is spilled
    S_BRANCH %bb.4

  ; Intermediate block - use %0 to trigger reload

  bb.4.path_a_use:
    successors: %bb.3(0x80000000)

    ; Use %0 - triggers reload
    S_NOP 0, implicit %0
    S_BRANCH %bb.3

  ; Path B: Also high RP - independently triggers spilling

  bb.2.path_b:
    successors: %bb.3(0x80000000)

    ; High RP on this path too - independently triggers spill of %0
    %4:vreg_64 = IMPLICIT_DEF
    %5:vreg_64 = IMPLICIT_DEF
    ; %0 (4 VGPRs) + %4 (2 VGPRs) + %5 (2 VGPRs) = 8 VGPRs (exceeds limit of 7)
    ; Spill %0 here
    S_NOP 0, implicit %4, implicit %5
    ; %4 and %5 die, %0 remains live (but spilled)
    S_BRANCH %bb.3

  ; Join point: path_a_use has reloaded %0, path_b has %0 spilled
  ; path_b will need a reload before join

  bb.3.join:
    ; Use of %0 at join point
    S_ENDPGM 0, implicit %0

...

