# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
# RUN: llc -mtriple=amdgcn -mcpu=gfx1200 -verify-machineinstrs -run-pass=amdgpu-ssa-register-spiller --amdgpu-ssa-spill-markers=1 -o - %s | FileCheck %s

# Test: Use before spill (no hoist to NCD) + clean path with high RP
# Verifies:
# 1. Register %0 is used in bb.1 before high RP forces spill
# 2. Spill cannot be hoisted to NCD (bb.0) because of early use
# 3. Clean path (bb.2) has different high RP but no spill
# 4. Split-before-use at join point (bb.3) where both paths converge
# 5. Flag PHI and value PHI for conditional reload

--- |
  target datalayout = "e-p:64:64-p1:64:64-p2:32:32-p3:32:32-p4:64:64-p5:32:32-p6:32:32-i64:64-v16:16-v24:32-v32:32-v48:64-v96:128-v192:256-v256:256-v512:512-v1024:1024-v2048:2048-n32:64-S32-A5-G1-ni:7:8:9"
  target triple = "amdgcn"

  define amdgpu_kernel void @test_use_before_spill(i32 %cond) #0 {
  entry:
    %cmp = icmp eq i32 %cond, 0
    br i1 %cmp, label %spill_path, label %clean_path

  spill_path:
    br label %join

  clean_path:
    br label %join

  join:
    ret void
  }

  attributes #0 = { "amdgpu-num-vgpr"="7" "target-cpu"="gfx1200" }
...
---
name:            test_use_before_spill
alignment:       1
tracksRegLiveness: true
noPhis:          false
registers:
  - { id: 0, class: vreg_128 }
  - { id: 1, class: vreg_64 }
  - { id: 2, class: vreg_64 }
  - { id: 3, class: sreg_32 }
stack:
frameInfo:
  maxAlignment:    4
machineFunctionInfo:
  stackPtrOffsetReg: '$sgpr32'
body: |
  ; CHECK-LABEL: name: test_use_before_spill
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   successors: %bb.1(0x40000000), %bb.2(0x40000000)
  ; CHECK-NEXT:   liveins: $vgpr0_vgpr1_vgpr2_vgpr3, $sgpr0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:vreg_128 = COPY $vgpr0_vgpr1_vgpr2_vgpr3
  ; CHECK-NEXT:   SI_SPILL_V32_SAVE [[COPY]].sub0, %stack.0, $sgpr32, 0, implicit $exec :: (store (s32) into %stack.0, addrspace 5)
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:sreg_32 = COPY $sgpr0
  ; CHECK-NEXT:   S_CMP_EQ_U32 [[COPY1]], 0, implicit-def $scc
  ; CHECK-NEXT:   S_CBRANCH_SCC1 %bb.1, implicit $scc
  ; CHECK-NEXT:   S_BRANCH %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1.spill_path:
  ; CHECK-NEXT:   successors: %bb.3(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   S_NOP 0, implicit [[COPY]]
  ; CHECK-NEXT:   [[DEF:%[0-9]+]]:vreg_64 = IMPLICIT_DEF
  ; CHECK-NEXT:   SI_VIRTUAL_SPILL_MARKER [[COPY]], 0000000000000003
  ; CHECK-NEXT:   [[DEF1:%[0-9]+]]:vreg_64 = IMPLICIT_DEF
  ; CHECK-NEXT:   S_NOP 0, implicit [[DEF]], implicit [[DEF1]]
  ; CHECK-NEXT:   S_BRANCH %bb.3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2.clean_path:
  ; CHECK-NEXT:   successors: %bb.3(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   S_BRANCH %bb.3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3.join:
  ; CHECK-NEXT:   [[SI_SPILL_V32_RESTORE:%[0-9]+]]:vgpr_32 = SI_SPILL_V32_RESTORE %stack.0, $sgpr32, 0, implicit $exec :: (load (s32) from %stack.0, addrspace 5)
  ; CHECK-NEXT:   [[REG_SEQUENCE:%[0-9]+]]:vreg_128 = REG_SEQUENCE [[SI_SPILL_V32_RESTORE]], %subreg.sub0, [[COPY]].sub1_sub2_sub3, %subreg.sub1_sub2_sub3
  ; CHECK-NEXT:   S_ENDPGM 0, implicit [[REG_SEQUENCE]]

  bb.0.entry:
    successors: %bb.1(0x40000000), %bb.2(0x40000000)
    liveins: $vgpr0_vgpr1_vgpr2_vgpr3, $sgpr0

    ; Define register that will be used on both paths
    %0:vreg_128 = COPY $vgpr0_vgpr1_vgpr2_vgpr3

    ; Branch condition
    %3:sreg_32 = COPY $sgpr0
    S_CMP_EQ_U32 %3, 0, implicit-def $scc
    S_CBRANCH_SCC1 %bb.1, implicit $scc
    S_BRANCH %bb.2

  ; Spill path: Use %0 first, then create high RP forcing spill
  ; Spill cannot be hoisted to bb.0 because of the early use

  bb.1.spill_path:
    successors: %bb.3(0x80000000)

    ; Early use of %0 - prevents hoisting spill to NCD
    S_NOP 0, implicit %0

    ; Now create high RP forcing %0 to be spilled
    %1:vreg_64 = IMPLICIT_DEF
    %2:vreg_64 = IMPLICIT_DEF
    ; %0 (4 VGPRs) + %1 (2 VGPRs) + %2 (2 VGPRs) = 8 VGPRs (exceeds limit of 7)
    S_NOP 0, implicit %1, implicit %2
    ; %1 and %2 die here, leaving only %0 live (4 VGPRs)
    S_BRANCH %bb.3

  ; Clean path: Low RP, no spill

  bb.2.clean_path:
    successors: %bb.3(0x80000000)

    ; Low RP - %0 stays live without spilling
    S_BRANCH %bb.3

  ; Join point: Split-before-use

  ; Reload block

  ; Final use block with value PHI

  bb.3.join:
    ; Use of %0 at join point - not dominated by any single spill
    S_ENDPGM 0, implicit %0

...

