# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
# RUN: llc -mtriple=amdgcn -mcpu=gfx900 -verify-machineinstrs -run-pass=amdgpu-ssa-register-spiller --amdgpu-ssa-spill-markers=1 %s -o - | FileCheck %s
#
# Test lane-aware spilling with vreg_1024 register class (32 VGPRs)
#
# This test validates handling of large register classes where subregisters
# are accessed individually. With amdgpu-num-vgpr=13, the spiller must handle
# each lane separately, creating multiple IDF computations per register.
#

--- |
  ; ModuleID = 'test1.mir'
  source_filename = "test1.ll"
  target datalayout = "e-p:64:64-p1:64:64-p2:32:32-p3:32:32-p4:64:64-p5:32:32-p6:32:32-p7:160:256:256:32-p8:128:128:128:48-p9:192:256:256:32-i64:64-v16:16-v24:32-v32:32-v48:64-v96:128-v192:256-v256:256-v512:512-v1024:1024-v2048:2048-n32:64-S32-A5-G1-ni:7:8:9"
  target triple = "amdgcn"

  define void @stack_args_vgpr_spill(<32 x float> %arg0, <32 x float> %arg1, ptr addrspace(1) %p) #0 {
    %tid = call i32 @llvm.amdgcn.workitem.id.x()
    %idxprom = sext i32 %tid to i64
    %p1 = getelementptr inbounds <32 x float>, ptr addrspace(1) %p, i64 %idxprom
    %p2 = getelementptr inbounds <32 x float>, ptr addrspace(1) %p1, i64 %idxprom
    %p3 = getelementptr inbounds <32 x float>, ptr addrspace(1) %p2, i64 %idxprom
    %p4 = getelementptr inbounds <32 x float>, ptr addrspace(1) %p3, i64 %idxprom
    %p5 = getelementptr inbounds <32 x float>, ptr addrspace(1) %p4, i64 %idxprom
    %p6 = getelementptr inbounds <32 x float>, ptr addrspace(1) %p5, i64 %idxprom
    %p7 = getelementptr inbounds <32 x float>, ptr addrspace(1) %p6, i64 %idxprom
    %v1 = load volatile <32 x float>, ptr addrspace(1) %p1, align 128
    %v2 = load volatile <32 x float>, ptr addrspace(1) %p2, align 128
    %v3 = load volatile <32 x float>, ptr addrspace(1) %p3, align 128
    %v4 = load volatile <32 x float>, ptr addrspace(1) %p4, align 128
    %v5 = load volatile <32 x float>, ptr addrspace(1) %p5, align 128
    %v6 = load volatile <32 x float>, ptr addrspace(1) %p6, align 128
    %v7 = load volatile <32 x float>, ptr addrspace(1) %p7, align 128
    br label %st, !amdgpu.uniform !0

  st:                                               ; preds = %0
    store volatile <32 x float> %arg0, ptr addrspace(1) undef, align 128
    store volatile <32 x float> %arg1, ptr addrspace(1) undef, align 128
    store volatile <32 x float> %v1, ptr addrspace(1) undef, align 128
    store volatile <32 x float> %v2, ptr addrspace(1) undef, align 128
    store volatile <32 x float> %v3, ptr addrspace(1) undef, align 128
    store volatile <32 x float> %v4, ptr addrspace(1) undef, align 128
    store volatile <32 x float> %v5, ptr addrspace(1) undef, align 128
    store volatile <32 x float> %v6, ptr addrspace(1) undef, align 128
    store volatile <32 x float> %v7, ptr addrspace(1) undef, align 128
    ret void
  }

  ; Function Attrs: nocallback nofree nosync nounwind speculatable willreturn memory(none)
  declare noundef range(i32 0, 1024) i32 @llvm.amdgcn.workitem.id.x() #1

  ; Function Attrs: nocallback nofree nounwind willreturn
  declare { i1, i64 } @llvm.amdgcn.if.i64(i1) #2

  ; Function Attrs: nocallback nofree nounwind willreturn
  declare { i1, i64 } @llvm.amdgcn.else.i64.i64(i64) #2

  ; Function Attrs: nocallback nofree nounwind willreturn memory(none)
  declare i64 @llvm.amdgcn.if.break.i64(i1, i64) #3

  ; Function Attrs: nocallback nofree nounwind willreturn
  declare i1 @llvm.amdgcn.loop.i64(i64) #2

  ; Function Attrs: nocallback nofree nounwind willreturn
  declare void @llvm.amdgcn.end.cf.i64(i64) #2

  attributes #0 = { "amdgpu-flat-work-group-size"="1,256" "amdgpu-memory-bound"="true" "target-cpu"="gfx900" }
  attributes #1 = { nocallback nofree nosync nounwind speculatable willreturn memory(none) "target-cpu"="gfx900" }
  attributes #2 = { nocallback nofree nounwind willreturn "target-cpu"="gfx900" }
  attributes #3 = { nocallback nofree nounwind willreturn memory(none) "target-cpu"="gfx900" }

  !0 = !{}
...
---
name:            stack_args_vgpr_spill
alignment:       1
exposesReturnsTwice: false
legalized:       false
regBankSelected: false
selected:        false
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
noPhis:          true
isSSA:           true
noVRegs:         false
hasFakeUses:     false
callsEHReturn:   false
callsUnwindInit: false
hasEHContTarget: false
hasEHScopes:     false
hasEHFunclets:   false
isOutlined:      false
debugInstrRef:   false
failsVerification: false
tracksDebugUserValues: false
registers:
  - { id: 0, class: vreg_1024, preferred-register: '', flags: [  ] }
  - { id: 1, class: vreg_1024, preferred-register: '', flags: [  ] }
  - { id: 2, class: vreg_1024, preferred-register: '', flags: [  ] }
  - { id: 3, class: vreg_1024, preferred-register: '', flags: [  ] }
  - { id: 4, class: vreg_1024, preferred-register: '', flags: [  ] }
  - { id: 5, class: vreg_1024, preferred-register: '', flags: [  ] }
  - { id: 6, class: vreg_1024, preferred-register: '', flags: [  ] }
  - { id: 7, class: sgpr_64, preferred-register: '', flags: [  ] }
  - { id: 8, class: sgpr_64, preferred-register: '', flags: [  ] }
  - { id: 9, class: sgpr_64, preferred-register: '', flags: [  ] }
  - { id: 10, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 11, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 12, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 13, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 14, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 15, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 16, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 17, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 18, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 19, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 20, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 21, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 22, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 23, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 24, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 25, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 26, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 27, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 28, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 29, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 30, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 31, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 32, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 33, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 34, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 35, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 36, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 37, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 38, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 39, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 40, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 41, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 42, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 43, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 44, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 45, class: vreg_1024, preferred-register: '', flags: [  ] }
  - { id: 46, class: vreg_1024, preferred-register: '', flags: [  ] }
  - { id: 47, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 48, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 49, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 50, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 51, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 52, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 53, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 54, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 55, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 56, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 57, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 58, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 59, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 60, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 61, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 62, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 63, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 64, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 65, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 66, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 67, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 68, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 69, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 70, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 71, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 72, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 73, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 74, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 75, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 76, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 77, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 78, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 79, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 80, class: sgpr_1024, preferred-register: '', flags: [  ] }
  - { id: 81, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 82, class: sgpr_1024, preferred-register: '', flags: [  ] }
  - { id: 83, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 84, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 85, class: sreg_64, preferred-register: '', flags: [  ] }
  - { id: 86, class: sreg_32, preferred-register: '', flags: [  ] }
  - { id: 87, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 88, class: sreg_32, preferred-register: '', flags: [  ] }
  - { id: 89, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 90, class: sreg_32, preferred-register: '', flags: [  ] }
  - { id: 91, class: sreg_64, preferred-register: '', flags: [  ] }
  - { id: 92, class: vreg_64, preferred-register: '', flags: [  ] }
  - { id: 93, class: vreg_64, preferred-register: '', flags: [  ] }
  - { id: 94, class: vreg_64, preferred-register: '', flags: [  ] }
  - { id: 95, class: vreg_64, preferred-register: '', flags: [  ] }
  - { id: 96, class: vreg_64, preferred-register: '', flags: [  ] }
  - { id: 97, class: vreg_64, preferred-register: '', flags: [  ] }
  - { id: 98, class: vreg_64, preferred-register: '', flags: [  ] }
  - { id: 99, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 100, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 101, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 102, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 103, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 104, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 105, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 106, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 107, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 108, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 109, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 110, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 111, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 112, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 113, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 114, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 115, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 116, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 117, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 118, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 119, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 120, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 121, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 122, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 123, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 124, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 125, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 126, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 127, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 128, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 129, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 130, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 131, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 132, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 133, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 134, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 135, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 136, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 137, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 138, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 139, class: sgpr_1024, preferred-register: '', flags: [  ] }
  - { id: 140, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 141, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 142, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 143, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 144, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 145, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 146, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 147, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 148, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 149, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 150, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 151, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 152, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 153, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 154, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 155, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 156, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 157, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 158, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 159, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 160, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 161, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 162, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 163, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 164, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 165, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 166, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 167, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 168, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 169, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 170, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 171, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 172, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 173, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 174, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 175, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 176, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 177, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 178, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 179, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 180, class: sgpr_1024, preferred-register: '', flags: [  ] }
  - { id: 181, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 182, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 183, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 184, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 185, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 186, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 187, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 188, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 189, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 190, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 191, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 192, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 193, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 194, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 195, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 196, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 197, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 198, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 199, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 200, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 201, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 202, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 203, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 204, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 205, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 206, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 207, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 208, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 209, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 210, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 211, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 212, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 213, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 214, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 215, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 216, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 217, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 218, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 219, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 220, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 221, class: sgpr_1024, preferred-register: '', flags: [  ] }
  - { id: 222, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 223, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 224, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 225, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 226, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 227, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 228, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 229, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 230, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 231, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 232, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 233, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 234, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 235, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 236, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 237, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 238, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 239, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 240, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 241, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 242, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 243, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 244, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 245, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 246, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 247, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 248, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 249, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 250, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 251, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 252, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 253, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 254, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 255, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 256, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 257, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 258, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 259, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 260, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 261, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 262, class: sgpr_1024, preferred-register: '', flags: [  ] }
  - { id: 263, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 264, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 265, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 266, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 267, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 268, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 269, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 270, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 271, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 272, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 273, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 274, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 275, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 276, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 277, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 278, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 279, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 280, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 281, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 282, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 283, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 284, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 285, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 286, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 287, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 288, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 289, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 290, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 291, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 292, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 293, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 294, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 295, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 296, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 297, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 298, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 299, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 300, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 301, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 302, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 303, class: sgpr_1024, preferred-register: '', flags: [  ] }
  - { id: 304, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 305, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 306, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 307, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 308, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 309, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 310, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 311, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 312, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 313, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 314, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 315, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 316, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 317, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 318, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 319, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 320, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 321, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 322, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 323, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 324, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 325, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 326, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 327, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 328, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 329, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 330, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 331, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 332, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 333, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 334, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 335, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 336, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 337, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 338, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 339, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 340, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 341, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 342, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 343, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 344, class: sgpr_1024, preferred-register: '', flags: [  ] }
  - { id: 345, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 346, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 347, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 348, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 349, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 350, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 351, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 352, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 353, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 354, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 355, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 356, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 357, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 358, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 359, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 360, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 361, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 362, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 363, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 364, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 365, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 366, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 367, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 368, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 369, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 370, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 371, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 372, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 373, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 374, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 375, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 376, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 377, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 378, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 379, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 380, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 381, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 382, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 383, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 384, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 385, class: sgpr_1024, preferred-register: '', flags: [  ] }
  - { id: 386, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 387, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 388, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 389, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 390, class: sgpr_128, preferred-register: '', flags: [  ] }
  - { id: 391, class: sreg_64, preferred-register: '', flags: [  ] }
  - { id: 392, class: vreg_64, preferred-register: '', flags: [  ] }
  - { id: 393, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 394, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 395, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 396, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 397, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 398, class: sgpr_128, preferred-register: '', flags: [  ] }
  - { id: 399, class: sreg_64, preferred-register: '', flags: [  ] }
  - { id: 400, class: vreg_64, preferred-register: '', flags: [  ] }
  - { id: 401, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 402, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 403, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 404, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 405, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 406, class: sgpr_128, preferred-register: '', flags: [  ] }
  - { id: 407, class: sreg_64, preferred-register: '', flags: [  ] }
  - { id: 408, class: vreg_64, preferred-register: '', flags: [  ] }
  - { id: 409, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 410, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 411, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 412, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 413, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 414, class: sgpr_128, preferred-register: '', flags: [  ] }
  - { id: 415, class: sreg_64, preferred-register: '', flags: [  ] }
  - { id: 416, class: vreg_64, preferred-register: '', flags: [  ] }
  - { id: 417, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 418, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 419, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 420, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 421, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 422, class: sgpr_128, preferred-register: '', flags: [  ] }
  - { id: 423, class: sreg_64, preferred-register: '', flags: [  ] }
  - { id: 424, class: vreg_64, preferred-register: '', flags: [  ] }
  - { id: 425, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 426, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 427, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 428, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 429, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 430, class: sgpr_128, preferred-register: '', flags: [  ] }
  - { id: 431, class: sreg_64, preferred-register: '', flags: [  ] }
  - { id: 432, class: vreg_64, preferred-register: '', flags: [  ] }
  - { id: 433, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 434, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 435, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 436, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 437, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 438, class: sgpr_128, preferred-register: '', flags: [  ] }
  - { id: 439, class: sreg_64, preferred-register: '', flags: [  ] }
  - { id: 440, class: vreg_64, preferred-register: '', flags: [  ] }
  - { id: 441, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 442, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 443, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 444, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 445, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 446, class: sgpr_128, preferred-register: '', flags: [  ] }
  - { id: 447, class: sreg_64, preferred-register: '', flags: [  ] }
  - { id: 448, class: vreg_64, preferred-register: '', flags: [  ] }
  - { id: 449, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 450, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 451, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 452, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 453, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 454, class: sgpr_128, preferred-register: '', flags: [  ] }
  - { id: 455, class: sreg_64, preferred-register: '', flags: [  ] }
  - { id: 456, class: vreg_64, preferred-register: '', flags: [  ] }
  - { id: 457, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 458, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 459, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 460, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 461, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 462, class: sgpr_128, preferred-register: '', flags: [  ] }
  - { id: 463, class: sreg_64, preferred-register: '', flags: [  ] }
  - { id: 464, class: vreg_64, preferred-register: '', flags: [  ] }
  - { id: 465, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 466, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 467, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 468, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 469, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 470, class: sgpr_128, preferred-register: '', flags: [  ] }
  - { id: 471, class: sreg_64, preferred-register: '', flags: [  ] }
  - { id: 472, class: vreg_64, preferred-register: '', flags: [  ] }
  - { id: 473, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 474, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 475, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 476, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 477, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 478, class: sgpr_128, preferred-register: '', flags: [  ] }
  - { id: 479, class: sreg_64, preferred-register: '', flags: [  ] }
  - { id: 480, class: vreg_64, preferred-register: '', flags: [  ] }
  - { id: 481, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 482, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 483, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 484, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 485, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 486, class: sgpr_128, preferred-register: '', flags: [  ] }
  - { id: 487, class: sreg_64, preferred-register: '', flags: [  ] }
  - { id: 488, class: vreg_64, preferred-register: '', flags: [  ] }
  - { id: 489, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 490, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 491, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 492, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 493, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 494, class: sgpr_128, preferred-register: '', flags: [  ] }
  - { id: 495, class: sreg_64, preferred-register: '', flags: [  ] }
  - { id: 496, class: vreg_64, preferred-register: '', flags: [  ] }
  - { id: 497, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 498, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 499, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 500, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 501, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 502, class: sgpr_128, preferred-register: '', flags: [  ] }
  - { id: 503, class: sreg_64, preferred-register: '', flags: [  ] }
  - { id: 504, class: vreg_64, preferred-register: '', flags: [  ] }
  - { id: 505, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 506, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 507, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 508, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 509, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 510, class: sgpr_128, preferred-register: '', flags: [  ] }
  - { id: 511, class: sreg_64, preferred-register: '', flags: [  ] }
  - { id: 512, class: vreg_64, preferred-register: '', flags: [  ] }
  - { id: 513, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 514, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 515, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 516, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 517, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 518, class: sgpr_128, preferred-register: '', flags: [  ] }
  - { id: 519, class: sreg_64, preferred-register: '', flags: [  ] }
  - { id: 520, class: vreg_64, preferred-register: '', flags: [  ] }
  - { id: 521, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 522, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 523, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 524, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 525, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 526, class: sgpr_128, preferred-register: '', flags: [  ] }
  - { id: 527, class: sreg_64, preferred-register: '', flags: [  ] }
  - { id: 528, class: vreg_64, preferred-register: '', flags: [  ] }
  - { id: 529, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 530, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 531, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 532, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 533, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 534, class: sgpr_128, preferred-register: '', flags: [  ] }
  - { id: 535, class: sreg_64, preferred-register: '', flags: [  ] }
  - { id: 536, class: vreg_64, preferred-register: '', flags: [  ] }
  - { id: 537, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 538, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 539, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 540, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 541, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 542, class: sgpr_128, preferred-register: '', flags: [  ] }
  - { id: 543, class: sreg_64, preferred-register: '', flags: [  ] }
  - { id: 544, class: vreg_64, preferred-register: '', flags: [  ] }
  - { id: 545, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 546, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 547, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 548, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 549, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 550, class: sgpr_128, preferred-register: '', flags: [  ] }
  - { id: 551, class: sreg_64, preferred-register: '', flags: [  ] }
  - { id: 552, class: vreg_64, preferred-register: '', flags: [  ] }
  - { id: 553, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 554, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 555, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 556, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 557, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 558, class: sgpr_128, preferred-register: '', flags: [  ] }
  - { id: 559, class: sreg_64, preferred-register: '', flags: [  ] }
  - { id: 560, class: vreg_64, preferred-register: '', flags: [  ] }
  - { id: 561, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 562, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 563, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 564, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 565, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 566, class: sgpr_128, preferred-register: '', flags: [  ] }
  - { id: 567, class: sreg_64, preferred-register: '', flags: [  ] }
  - { id: 568, class: vreg_64, preferred-register: '', flags: [  ] }
  - { id: 569, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 570, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 571, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 572, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 573, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 574, class: sgpr_128, preferred-register: '', flags: [  ] }
  - { id: 575, class: sreg_64, preferred-register: '', flags: [  ] }
  - { id: 576, class: vreg_64, preferred-register: '', flags: [  ] }
  - { id: 577, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 578, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 579, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 580, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 581, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 582, class: sgpr_128, preferred-register: '', flags: [  ] }
  - { id: 583, class: sreg_64, preferred-register: '', flags: [  ] }
  - { id: 584, class: vreg_64, preferred-register: '', flags: [  ] }
  - { id: 585, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 586, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 587, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 588, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 589, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 590, class: sgpr_128, preferred-register: '', flags: [  ] }
  - { id: 591, class: sreg_64, preferred-register: '', flags: [  ] }
  - { id: 592, class: vreg_64, preferred-register: '', flags: [  ] }
  - { id: 593, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 594, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 595, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 596, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 597, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 598, class: sgpr_128, preferred-register: '', flags: [  ] }
  - { id: 599, class: sreg_64, preferred-register: '', flags: [  ] }
  - { id: 600, class: vreg_64, preferred-register: '', flags: [  ] }
  - { id: 601, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 602, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 603, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 604, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 605, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 606, class: sgpr_128, preferred-register: '', flags: [  ] }
  - { id: 607, class: sreg_64, preferred-register: '', flags: [  ] }
  - { id: 608, class: vreg_64, preferred-register: '', flags: [  ] }
  - { id: 609, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 610, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 611, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 612, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 613, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 614, class: sgpr_128, preferred-register: '', flags: [  ] }
  - { id: 615, class: sreg_64, preferred-register: '', flags: [  ] }
  - { id: 616, class: vreg_64, preferred-register: '', flags: [  ] }
  - { id: 617, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 618, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 619, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 620, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 621, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 622, class: sgpr_128, preferred-register: '', flags: [  ] }
  - { id: 623, class: sreg_64, preferred-register: '', flags: [  ] }
  - { id: 624, class: vreg_64, preferred-register: '', flags: [  ] }
  - { id: 625, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 626, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 627, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 628, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 629, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 630, class: sgpr_128, preferred-register: '', flags: [  ] }
  - { id: 631, class: sreg_64, preferred-register: '', flags: [  ] }
  - { id: 632, class: vreg_64, preferred-register: '', flags: [  ] }
  - { id: 633, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 634, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 635, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 636, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 637, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 638, class: sgpr_128, preferred-register: '', flags: [  ] }
  - { id: 639, class: sreg_64, preferred-register: '', flags: [  ] }
  - { id: 640, class: vreg_64, preferred-register: '', flags: [  ] }
  - { id: 641, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 642, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 643, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 644, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 645, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 646, class: sgpr_128, preferred-register: '', flags: [  ] }
  - { id: 647, class: sreg_64, preferred-register: '', flags: [  ] }
  - { id: 648, class: vreg_64, preferred-register: '', flags: [  ] }
  - { id: 649, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 650, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 651, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 652, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 653, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 654, class: sgpr_128, preferred-register: '', flags: [  ] }
  - { id: 655, class: sreg_64, preferred-register: '', flags: [  ] }
  - { id: 656, class: vreg_64, preferred-register: '', flags: [  ] }
  - { id: 657, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 658, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 659, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 660, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 661, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 662, class: sgpr_128, preferred-register: '', flags: [  ] }
  - { id: 663, class: sreg_64, preferred-register: '', flags: [  ] }
  - { id: 664, class: vreg_64, preferred-register: '', flags: [  ] }
  - { id: 665, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 666, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 667, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 668, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 669, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 670, class: sgpr_128, preferred-register: '', flags: [  ] }
  - { id: 671, class: sreg_64, preferred-register: '', flags: [  ] }
  - { id: 672, class: vreg_64, preferred-register: '', flags: [  ] }
  - { id: 673, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 674, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 675, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 676, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 677, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 678, class: sgpr_128, preferred-register: '', flags: [  ] }
  - { id: 679, class: sreg_64, preferred-register: '', flags: [  ] }
  - { id: 680, class: vreg_64, preferred-register: '', flags: [  ] }
  - { id: 681, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 682, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 683, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 684, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 685, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 686, class: sgpr_128, preferred-register: '', flags: [  ] }
  - { id: 687, class: sreg_64, preferred-register: '', flags: [  ] }
  - { id: 688, class: vreg_64, preferred-register: '', flags: [  ] }
  - { id: 689, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 690, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 691, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 692, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 693, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 694, class: sgpr_128, preferred-register: '', flags: [  ] }
  - { id: 695, class: sreg_64, preferred-register: '', flags: [  ] }
  - { id: 696, class: vreg_64, preferred-register: '', flags: [  ] }
  - { id: 697, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 698, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 699, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 700, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 701, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 702, class: sgpr_128, preferred-register: '', flags: [  ] }
  - { id: 703, class: sreg_64, preferred-register: '', flags: [  ] }
  - { id: 704, class: vreg_64, preferred-register: '', flags: [  ] }
  - { id: 705, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 706, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 707, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 708, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 709, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 710, class: sgpr_128, preferred-register: '', flags: [  ] }
  - { id: 711, class: sreg_64, preferred-register: '', flags: [  ] }
  - { id: 712, class: vreg_64, preferred-register: '', flags: [  ] }
  - { id: 713, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 714, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 715, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 716, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 717, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 718, class: sgpr_128, preferred-register: '', flags: [  ] }
  - { id: 719, class: sreg_64, preferred-register: '', flags: [  ] }
  - { id: 720, class: vreg_64, preferred-register: '', flags: [  ] }
  - { id: 721, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 722, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 723, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 724, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 725, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 726, class: sgpr_128, preferred-register: '', flags: [  ] }
  - { id: 727, class: sreg_64, preferred-register: '', flags: [  ] }
  - { id: 728, class: vreg_64, preferred-register: '', flags: [  ] }
  - { id: 729, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 730, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 731, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 732, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 733, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 734, class: sgpr_128, preferred-register: '', flags: [  ] }
  - { id: 735, class: sreg_64, preferred-register: '', flags: [  ] }
  - { id: 736, class: vreg_64, preferred-register: '', flags: [  ] }
  - { id: 737, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 738, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 739, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 740, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 741, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 742, class: sgpr_128, preferred-register: '', flags: [  ] }
  - { id: 743, class: sreg_64, preferred-register: '', flags: [  ] }
  - { id: 744, class: vreg_64, preferred-register: '', flags: [  ] }
  - { id: 745, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 746, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 747, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 748, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 749, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 750, class: sgpr_128, preferred-register: '', flags: [  ] }
  - { id: 751, class: sreg_64, preferred-register: '', flags: [  ] }
  - { id: 752, class: vreg_64, preferred-register: '', flags: [  ] }
  - { id: 753, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 754, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 755, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 756, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 757, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 758, class: sgpr_128, preferred-register: '', flags: [  ] }
  - { id: 759, class: sreg_64, preferred-register: '', flags: [  ] }
  - { id: 760, class: vreg_64, preferred-register: '', flags: [  ] }
  - { id: 761, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 762, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 763, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 764, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 765, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 766, class: sgpr_128, preferred-register: '', flags: [  ] }
  - { id: 767, class: sreg_64, preferred-register: '', flags: [  ] }
  - { id: 768, class: vreg_64, preferred-register: '', flags: [  ] }
  - { id: 769, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 770, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 771, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 772, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 773, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 774, class: sgpr_128, preferred-register: '', flags: [  ] }
  - { id: 775, class: sreg_64, preferred-register: '', flags: [  ] }
  - { id: 776, class: vreg_64, preferred-register: '', flags: [  ] }
  - { id: 777, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 778, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 779, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 780, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 781, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 782, class: sgpr_128, preferred-register: '', flags: [  ] }
  - { id: 783, class: sreg_64, preferred-register: '', flags: [  ] }
  - { id: 784, class: vreg_64, preferred-register: '', flags: [  ] }
  - { id: 785, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 786, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 787, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 788, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 789, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 790, class: sgpr_128, preferred-register: '', flags: [  ] }
  - { id: 791, class: sreg_64, preferred-register: '', flags: [  ] }
  - { id: 792, class: vreg_64, preferred-register: '', flags: [  ] }
  - { id: 793, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 794, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 795, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 796, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 797, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 798, class: sgpr_128, preferred-register: '', flags: [  ] }
  - { id: 799, class: sreg_64, preferred-register: '', flags: [  ] }
  - { id: 800, class: vreg_64, preferred-register: '', flags: [  ] }
  - { id: 801, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 802, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 803, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 804, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 805, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 806, class: sgpr_128, preferred-register: '', flags: [  ] }
  - { id: 807, class: sreg_64, preferred-register: '', flags: [  ] }
  - { id: 808, class: vreg_64, preferred-register: '', flags: [  ] }
  - { id: 809, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 810, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 811, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 812, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 813, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 814, class: sgpr_128, preferred-register: '', flags: [  ] }
  - { id: 815, class: sreg_64, preferred-register: '', flags: [  ] }
  - { id: 816, class: vreg_64, preferred-register: '', flags: [  ] }
  - { id: 817, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 818, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 819, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 820, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 821, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 822, class: sgpr_128, preferred-register: '', flags: [  ] }
  - { id: 823, class: sreg_64, preferred-register: '', flags: [  ] }
  - { id: 824, class: vreg_64, preferred-register: '', flags: [  ] }
  - { id: 825, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 826, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 827, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 828, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 829, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 830, class: sgpr_128, preferred-register: '', flags: [  ] }
  - { id: 831, class: sreg_64, preferred-register: '', flags: [  ] }
  - { id: 832, class: vreg_64, preferred-register: '', flags: [  ] }
  - { id: 833, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 834, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 835, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 836, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 837, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 838, class: sgpr_128, preferred-register: '', flags: [  ] }
  - { id: 839, class: sreg_64, preferred-register: '', flags: [  ] }
  - { id: 840, class: vreg_64, preferred-register: '', flags: [  ] }
  - { id: 841, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 842, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 843, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 844, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 845, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 846, class: sgpr_128, preferred-register: '', flags: [  ] }
  - { id: 847, class: sreg_64, preferred-register: '', flags: [  ] }
  - { id: 848, class: vreg_64, preferred-register: '', flags: [  ] }
  - { id: 849, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 850, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 851, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 852, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 853, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 854, class: sgpr_128, preferred-register: '', flags: [  ] }
  - { id: 855, class: sreg_64, preferred-register: '', flags: [  ] }
  - { id: 856, class: vreg_64, preferred-register: '', flags: [  ] }
  - { id: 857, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 858, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 859, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 860, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 861, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 862, class: sgpr_128, preferred-register: '', flags: [  ] }
  - { id: 863, class: sreg_64, preferred-register: '', flags: [  ] }
  - { id: 864, class: vreg_64, preferred-register: '', flags: [  ] }
  - { id: 865, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 866, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 867, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 868, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 869, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 870, class: sgpr_128, preferred-register: '', flags: [  ] }
  - { id: 871, class: sreg_64, preferred-register: '', flags: [  ] }
  - { id: 872, class: vreg_64, preferred-register: '', flags: [  ] }
  - { id: 873, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 874, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 875, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 876, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 877, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 878, class: sgpr_128, preferred-register: '', flags: [  ] }
  - { id: 879, class: sreg_64, preferred-register: '', flags: [  ] }
  - { id: 880, class: vreg_64, preferred-register: '', flags: [  ] }
  - { id: 881, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 882, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 883, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 884, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 885, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 886, class: sgpr_128, preferred-register: '', flags: [  ] }
  - { id: 887, class: sreg_64, preferred-register: '', flags: [  ] }
  - { id: 888, class: vreg_64, preferred-register: '', flags: [  ] }
  - { id: 889, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 890, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 891, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 892, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 893, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 894, class: sgpr_128, preferred-register: '', flags: [  ] }
  - { id: 895, class: sreg_64, preferred-register: '', flags: [  ] }
  - { id: 896, class: vreg_64, preferred-register: '', flags: [  ] }
  - { id: 897, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 898, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 899, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 900, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 901, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 902, class: sgpr_128, preferred-register: '', flags: [  ] }
  - { id: 903, class: sreg_64, preferred-register: '', flags: [  ] }
  - { id: 904, class: vreg_64, preferred-register: '', flags: [  ] }
  - { id: 905, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 906, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 907, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 908, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 909, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 910, class: sgpr_128, preferred-register: '', flags: [  ] }
  - { id: 911, class: sreg_64, preferred-register: '', flags: [  ] }
  - { id: 912, class: vreg_64, preferred-register: '', flags: [  ] }
  - { id: 913, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 914, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 915, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 916, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 917, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 918, class: sgpr_128, preferred-register: '', flags: [  ] }
  - { id: 919, class: sreg_64, preferred-register: '', flags: [  ] }
  - { id: 920, class: vreg_64, preferred-register: '', flags: [  ] }
  - { id: 921, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 922, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 923, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 924, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 925, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 926, class: sgpr_128, preferred-register: '', flags: [  ] }
  - { id: 927, class: sreg_64, preferred-register: '', flags: [  ] }
  - { id: 928, class: vreg_64, preferred-register: '', flags: [  ] }
  - { id: 929, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 930, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 931, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 932, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 933, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 934, class: sgpr_128, preferred-register: '', flags: [  ] }
  - { id: 935, class: sreg_64, preferred-register: '', flags: [  ] }
  - { id: 936, class: vreg_64, preferred-register: '', flags: [  ] }
  - { id: 937, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 938, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 939, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 940, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 941, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 942, class: sgpr_128, preferred-register: '', flags: [  ] }
  - { id: 943, class: sreg_64, preferred-register: '', flags: [  ] }
  - { id: 944, class: vreg_64, preferred-register: '', flags: [  ] }
  - { id: 945, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 946, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 947, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 948, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 949, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 950, class: sgpr_128, preferred-register: '', flags: [  ] }
  - { id: 951, class: sreg_64, preferred-register: '', flags: [  ] }
  - { id: 952, class: vreg_64, preferred-register: '', flags: [  ] }
  - { id: 953, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 954, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 955, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 956, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 957, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 958, class: sgpr_128, preferred-register: '', flags: [  ] }
  - { id: 959, class: sreg_64, preferred-register: '', flags: [  ] }
  - { id: 960, class: vreg_64, preferred-register: '', flags: [  ] }
  - { id: 961, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 962, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 963, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 964, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 965, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 966, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 967, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 968, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 969, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 970, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 971, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 972, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 973, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 974, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 975, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 976, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 977, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 978, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 979, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 980, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 981, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 982, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 983, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 984, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 985, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 986, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 987, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 988, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 989, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 990, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 991, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 992, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 993, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 994, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 995, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 996, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 997, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 998, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 999, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1000, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1001, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1002, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1003, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1004, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1005, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1006, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1007, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1008, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1009, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1010, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1011, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1012, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1013, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1014, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1015, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1016, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1017, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1018, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1019, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1020, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1021, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1022, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1023, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1024, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1025, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1026, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1027, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1028, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1029, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1030, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1031, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1032, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1033, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1034, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1035, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1036, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1037, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1038, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1039, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1040, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1041, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1042, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1043, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1044, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1045, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1046, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1047, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1048, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1049, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1050, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1051, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1052, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1053, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1054, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1055, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1056, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1057, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1058, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1059, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1060, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1061, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1062, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1063, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1064, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1065, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1066, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1067, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1068, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1069, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1070, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1071, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1072, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1073, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1074, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1075, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1076, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1077, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1078, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1079, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1080, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1081, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1082, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1083, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1084, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1085, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1086, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1087, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1088, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1089, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1090, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1091, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1092, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1093, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1094, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1095, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1096, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1097, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1098, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1099, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1100, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1101, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1102, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1103, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1104, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1105, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1106, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1107, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1108, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1109, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1110, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1111, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1112, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1113, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1114, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1115, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1116, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1117, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1118, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1119, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1120, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1121, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1122, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1123, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1124, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1125, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1126, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1127, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1128, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1129, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1130, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1131, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1132, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1133, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1134, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1135, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1136, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1137, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1138, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1139, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1140, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1141, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1142, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1143, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1144, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1145, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1146, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1147, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1148, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1149, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1150, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1151, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1152, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1153, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1154, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1155, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1156, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1157, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1158, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1159, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1160, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1161, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1162, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1163, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1164, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1165, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1166, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1167, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1168, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1169, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1170, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1171, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1172, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1173, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1174, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1175, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1176, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1177, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1178, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1179, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1180, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1181, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1182, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1183, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1184, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1185, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1186, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1187, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1188, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1189, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1190, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1191, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1192, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1193, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1194, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1195, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1196, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1197, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1198, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1199, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1200, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1201, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1202, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1203, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1204, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1205, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1206, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1207, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1208, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1209, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1210, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1211, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1212, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1213, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1214, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1215, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1216, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1217, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1218, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1219, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1220, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1221, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1222, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1223, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1224, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1225, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1226, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1227, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1228, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1229, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1230, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1231, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1232, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1233, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1234, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1235, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1236, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1237, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1238, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1239, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1240, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1241, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1242, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1243, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1244, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1245, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1246, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1247, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1248, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1249, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1250, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1251, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1252, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1253, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1254, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1255, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1256, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1257, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1258, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1259, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1260, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1261, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1262, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1263, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1264, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1265, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1266, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1267, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1268, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1269, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1270, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1271, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1272, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1273, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1274, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1275, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1276, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1277, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1278, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1279, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1280, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1281, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1282, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1283, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1284, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1285, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1286, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1287, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1288, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1289, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1290, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1291, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1292, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1293, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1294, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1295, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1296, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1297, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1298, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1299, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1300, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1301, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1302, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1303, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1304, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1305, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1306, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1307, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1308, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1309, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1310, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1311, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1312, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1313, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1314, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1315, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1316, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1317, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1318, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1319, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1320, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1321, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1322, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1323, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1324, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1325, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1326, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1327, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1328, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1329, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1330, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1331, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1332, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1333, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1334, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1335, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1336, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1337, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1338, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1339, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1340, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1341, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1342, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1343, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1344, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1345, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1346, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1347, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1348, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1349, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1350, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1351, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1352, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1353, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1354, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1355, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1356, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1357, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1358, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1359, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1360, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1361, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1362, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1363, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1364, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1365, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1366, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1367, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1368, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1369, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1370, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1371, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1372, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1373, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1374, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1375, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1376, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1377, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1378, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1379, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1380, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1381, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1382, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1383, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1384, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1385, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1386, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1387, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1388, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1389, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1390, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1391, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1392, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1393, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1394, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1395, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1396, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1397, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1398, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1399, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1400, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1401, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1402, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1403, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1404, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1405, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1406, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1407, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1408, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1409, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1410, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1411, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1412, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1413, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1414, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1415, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1416, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1417, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1418, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1419, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1420, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1421, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1422, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1423, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1424, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1425, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1426, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1427, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1428, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1429, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1430, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1431, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1432, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1433, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1434, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1435, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1436, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1437, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1438, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1439, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1440, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1441, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1442, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1443, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1444, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1445, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1446, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1447, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1448, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1449, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1450, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1451, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1452, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1453, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1454, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1455, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1456, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1457, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1458, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1459, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1460, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1461, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1462, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1463, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1464, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1465, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1466, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1467, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1468, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1469, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1470, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1471, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1472, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1473, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1474, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1475, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1476, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1477, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1478, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1479, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1480, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1481, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1482, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1483, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1484, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1485, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1486, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1487, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1488, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1489, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1490, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1491, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1492, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1493, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1494, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1495, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1496, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1497, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1498, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1499, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1500, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1501, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1502, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1503, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1504, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1505, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1506, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1507, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1508, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1509, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1510, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1511, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1512, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1513, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1514, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1515, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1516, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1517, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1518, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1519, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1520, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1521, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1522, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1523, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1524, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1525, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1526, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1527, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1528, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1529, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1530, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1531, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1532, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1533, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1534, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1535, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1536, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1537, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1538, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1539, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1540, class: sgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1541, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 1542, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 1543, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 1544, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 1545, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 1546, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 1547, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 1548, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 1549, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 1550, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 1551, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 1552, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 1553, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 1554, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 1555, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 1556, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 1557, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 1558, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 1559, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 1560, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 1561, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 1562, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 1563, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 1564, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 1565, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 1566, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 1567, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 1568, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 1569, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 1570, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 1571, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 1572, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 1573, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 1574, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 1575, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 1576, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 1577, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 1578, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 1579, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 1580, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 1581, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 1582, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 1583, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 1584, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 1585, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 1586, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 1587, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 1588, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 1589, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 1590, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 1591, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 1592, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 1593, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 1594, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 1595, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 1596, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 1597, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 1598, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 1599, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 1600, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 1601, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 1602, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 1603, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 1604, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 1605, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 1606, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 1607, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 1608, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 1609, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 1610, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 1611, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 1612, class: vreg_128, preferred-register: '', flags: [  ] }
  - { id: 1613, class: vreg_1024, preferred-register: '', flags: [  ] }
  - { id: 1614, class: vreg_1024, preferred-register: '', flags: [  ] }
  - { id: 1615, class: vreg_1024, preferred-register: '', flags: [  ] }
  - { id: 1616, class: vreg_1024, preferred-register: '', flags: [  ] }
  - { id: 1617, class: vreg_1024, preferred-register: '', flags: [  ] }
  - { id: 1618, class: vreg_1024, preferred-register: '', flags: [  ] }
  - { id: 1619, class: vreg_1024, preferred-register: '', flags: [  ] }
  - { id: 1620, class: vreg_64, preferred-register: '', flags: [  ] }
  - { id: 1621, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1622, class: vreg_64, preferred-register: '', flags: [  ] }
  - { id: 1623, class: vreg_1024, preferred-register: '', flags: [  ] }
  - { id: 1624, class: vreg_1024, preferred-register: '', flags: [  ] }
  - { id: 1625, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1626, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1627, class: sreg_64_xexec, preferred-register: '$vcc', flags: [  ] }
  - { id: 1628, class: sreg_64_xexec, preferred-register: '$vcc', flags: [  ] }
  - { id: 1629, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1630, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1631, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1632, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1633, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1634, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1635, class: sreg_64_xexec, preferred-register: '$vcc', flags: [  ] }
  - { id: 1636, class: sreg_64_xexec, preferred-register: '$vcc', flags: [  ] }
  - { id: 1637, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1638, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1639, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1640, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1641, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1642, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1643, class: sreg_64_xexec, preferred-register: '$vcc', flags: [  ] }
  - { id: 1644, class: sreg_64_xexec, preferred-register: '$vcc', flags: [  ] }
  - { id: 1645, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1646, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1647, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1648, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1649, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1650, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1651, class: sreg_64_xexec, preferred-register: '$vcc', flags: [  ] }
  - { id: 1652, class: sreg_64_xexec, preferred-register: '$vcc', flags: [  ] }
  - { id: 1653, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1654, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1655, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1656, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1657, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1658, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1659, class: sreg_64_xexec, preferred-register: '$vcc', flags: [  ] }
  - { id: 1660, class: sreg_64_xexec, preferred-register: '$vcc', flags: [  ] }
  - { id: 1661, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1662, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1663, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1664, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1665, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1666, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1667, class: sreg_64_xexec, preferred-register: '$vcc', flags: [  ] }
  - { id: 1668, class: sreg_64_xexec, preferred-register: '$vcc', flags: [  ] }
  - { id: 1669, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1670, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1671, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1672, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1673, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1674, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1675, class: sreg_64_xexec, preferred-register: '$vcc', flags: [  ] }
  - { id: 1676, class: sreg_64_xexec, preferred-register: '$vcc', flags: [  ] }
  - { id: 1677, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1678, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1679, class: vgpr_32, preferred-register: '', flags: [  ] }
  - { id: 1680, class: vgpr_32, preferred-register: '', flags: [  ] }
liveins:
  - { reg: '$vgpr0', virtual-reg: '%14' }
  - { reg: '$vgpr1', virtual-reg: '%15' }
  - { reg: '$vgpr2', virtual-reg: '%16' }
  - { reg: '$vgpr3', virtual-reg: '%17' }
  - { reg: '$vgpr4', virtual-reg: '%18' }
  - { reg: '$vgpr5', virtual-reg: '%19' }
  - { reg: '$vgpr6', virtual-reg: '%20' }
  - { reg: '$vgpr7', virtual-reg: '%21' }
  - { reg: '$vgpr8', virtual-reg: '%22' }
  - { reg: '$vgpr9', virtual-reg: '%23' }
  - { reg: '$vgpr10', virtual-reg: '%24' }
  - { reg: '$vgpr11', virtual-reg: '%25' }
  - { reg: '$vgpr12', virtual-reg: '%26' }
  - { reg: '$vgpr13', virtual-reg: '%27' }
  - { reg: '$vgpr14', virtual-reg: '%28' }
  - { reg: '$vgpr15', virtual-reg: '%29' }
  - { reg: '$vgpr16', virtual-reg: '%30' }
  - { reg: '$vgpr17', virtual-reg: '%31' }
  - { reg: '$vgpr18', virtual-reg: '%32' }
  - { reg: '$vgpr19', virtual-reg: '%33' }
  - { reg: '$vgpr20', virtual-reg: '%34' }
  - { reg: '$vgpr21', virtual-reg: '%35' }
  - { reg: '$vgpr22', virtual-reg: '%36' }
  - { reg: '$vgpr23', virtual-reg: '%37' }
  - { reg: '$vgpr24', virtual-reg: '%38' }
  - { reg: '$vgpr25', virtual-reg: '%39' }
  - { reg: '$vgpr26', virtual-reg: '%40' }
  - { reg: '$vgpr27', virtual-reg: '%41' }
  - { reg: '$vgpr28', virtual-reg: '%42' }
  - { reg: '$vgpr29', virtual-reg: '%43' }
  - { reg: '$vgpr30', virtual-reg: '%44' }
  - { reg: '$vgpr31', virtual-reg: '%47' }
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    16
  adjustsStack:    false
  hasCalls:        false
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 4294967295
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  isCalleeSavedInfoValid: false
  localFrameSize:  0
fixedStack:
  - { id: 0, type: default, offset: 0, size: 4, alignment: 16, stack-id: default,
      isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 1, type: default, offset: 4, size: 4, alignment: 4, stack-id: default,
      isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 2, type: default, offset: 8, size: 4, alignment: 8, stack-id: default,
      isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 3, type: default, offset: 12, size: 4, alignment: 4, stack-id: default,
      isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 4, type: default, offset: 16, size: 4, alignment: 16, stack-id: default,
      isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 5, type: default, offset: 20, size: 4, alignment: 4, stack-id: default,
      isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 6, type: default, offset: 24, size: 4, alignment: 8, stack-id: default,
      isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 7, type: default, offset: 28, size: 4, alignment: 4, stack-id: default,
      isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 8, type: default, offset: 32, size: 4, alignment: 16, stack-id: default,
      isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 9, type: default, offset: 36, size: 4, alignment: 4, stack-id: default,
      isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 10, type: default, offset: 40, size: 4, alignment: 8, stack-id: default,
      isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 11, type: default, offset: 44, size: 4, alignment: 4, stack-id: default,
      isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 12, type: default, offset: 48, size: 4, alignment: 16, stack-id: default,
      isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 13, type: default, offset: 52, size: 4, alignment: 4, stack-id: default,
      isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 14, type: default, offset: 56, size: 4, alignment: 8, stack-id: default,
      isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 15, type: default, offset: 60, size: 4, alignment: 4, stack-id: default,
      isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 16, type: default, offset: 64, size: 4, alignment: 16, stack-id: default,
      isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 17, type: default, offset: 68, size: 4, alignment: 4, stack-id: default,
      isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 18, type: default, offset: 72, size: 4, alignment: 8, stack-id: default,
      isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 19, type: default, offset: 76, size: 4, alignment: 4, stack-id: default,
      isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 20, type: default, offset: 80, size: 4, alignment: 16, stack-id: default,
      isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 21, type: default, offset: 84, size: 4, alignment: 4, stack-id: default,
      isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 22, type: default, offset: 88, size: 4, alignment: 8, stack-id: default,
      isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 23, type: default, offset: 92, size: 4, alignment: 4, stack-id: default,
      isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 24, type: default, offset: 96, size: 4, alignment: 16, stack-id: default,
      isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 25, type: default, offset: 100, size: 4, alignment: 4, stack-id: default,
      isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 26, type: default, offset: 104, size: 4, alignment: 8, stack-id: default,
      isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 27, type: default, offset: 108, size: 4, alignment: 4, stack-id: default,
      isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 28, type: default, offset: 112, size: 4, alignment: 16, stack-id: default,
      isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 29, type: default, offset: 116, size: 4, alignment: 4, stack-id: default,
      isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 30, type: default, offset: 120, size: 4, alignment: 8, stack-id: default,
      isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 31, type: default, offset: 124, size: 4, alignment: 4, stack-id: default,
      isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 32, type: default, offset: 128, size: 4, alignment: 16, stack-id: default,
      isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 33, type: default, offset: 132, size: 4, alignment: 4, stack-id: default,
      isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 34, type: default, offset: 136, size: 4, alignment: 8, stack-id: default,
      isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
stack:           []
entry_values:    []
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo:
  explicitKernArgSize: 0
  maxKernArgAlign: 1
  ldsSize:         0
  gdsSize:         0
  dynLDSAlign:     1
  isEntryFunction: false
  isChainFunction: false
  noSignedZerosFPMath: false
  memoryBound:     true
  waveLimiter:     false
  hasSpilledSGPRs: false
  hasSpilledVGPRs: false
  numWaveDispatchSGPRs: 0
  numWaveDispatchVGPRs: 0
  scratchRSrcReg:  '$sgpr0_sgpr1_sgpr2_sgpr3'
  frameOffsetReg:  '$sgpr33'
  stackPtrOffsetReg: '$sgpr32'
  bytesInStackArgArea: 140
  returnsVoid:     true
  argumentInfo:
    privateSegmentBuffer: { reg: '$sgpr0_sgpr1_sgpr2_sgpr3' }
    dispatchPtr:     { reg: '$sgpr4_sgpr5' }
    queuePtr:        { reg: '$sgpr6_sgpr7' }
    dispatchID:      { reg: '$sgpr10_sgpr11' }
    workGroupIDX:    { reg: '$sgpr12' }
    workGroupIDY:    { reg: '$sgpr13' }
    workGroupIDZ:    { reg: '$sgpr14' }
    LDSKernelId:     { reg: '$sgpr15' }
    implicitArgPtr:  { reg: '$sgpr8_sgpr9' }
    workItemIDX:     { reg: '$vgpr31', mask: 1023 }
    workItemIDY:     { reg: '$vgpr31', mask: 1047552 }
    workItemIDZ:     { reg: '$vgpr31', mask: 1072693248 }
  psInputAddr:     0
  psInputEnable:   0
  maxMemoryClusterDWords: 8
  mode:
    ieee:            true
    dx10-clamp:      true
    fp32-input-denormals: true
    fp32-output-denormals: true
    fp64-fp16-input-denormals: true
    fp64-fp16-output-denormals: true
  highBitsOf32BitAddress: 0
  occupancy:       10
  vgprForAGPRCopy: ''
  sgprForEXECCopy: '$sgpr100_sgpr101'
  longBranchReservedReg: ''
  hasInitWholeWave: false
  dynamicVGPRBlockSize: 0
  scratchReservedForDynamicVGPRs: 0
  isWholeWaveFunction: false
body:             |
  ; CHECK-LABEL: name: stack_args_vgpr_spill
  ; CHECK: bb.0 (%ir-block.0):
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $vgpr0, $vgpr1, $vgpr2, $vgpr3, $vgpr4, $vgpr5, $vgpr6, $vgpr7, $vgpr8, $vgpr9, $vgpr10, $vgpr11, $vgpr12, $vgpr13, $vgpr14, $vgpr15, $vgpr16, $vgpr17, $vgpr18, $vgpr19, $vgpr20, $vgpr21, $vgpr22, $vgpr23, $vgpr24, $vgpr25, $vgpr26, $vgpr27, $vgpr28, $vgpr29, $vgpr30, $vgpr31
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr31
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:vgpr_32 = COPY $vgpr30
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:vgpr_32 = COPY $vgpr29
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:vgpr_32 = COPY $vgpr28
  ; CHECK-NEXT:   [[COPY4:%[0-9]+]]:vgpr_32 = COPY $vgpr27
  ; CHECK-NEXT:   [[COPY5:%[0-9]+]]:vgpr_32 = COPY $vgpr26
  ; CHECK-NEXT:   [[COPY6:%[0-9]+]]:vgpr_32 = COPY $vgpr25
  ; CHECK-NEXT:   [[COPY7:%[0-9]+]]:vgpr_32 = COPY $vgpr24
  ; CHECK-NEXT:   [[COPY8:%[0-9]+]]:vgpr_32 = COPY $vgpr23
  ; CHECK-NEXT:   [[COPY9:%[0-9]+]]:vgpr_32 = COPY $vgpr22
  ; CHECK-NEXT:   [[COPY10:%[0-9]+]]:vgpr_32 = COPY $vgpr21
  ; CHECK-NEXT:   [[COPY11:%[0-9]+]]:vgpr_32 = COPY $vgpr20
  ; CHECK-NEXT:   [[COPY12:%[0-9]+]]:vgpr_32 = COPY $vgpr19
  ; CHECK-NEXT:   [[COPY13:%[0-9]+]]:vgpr_32 = COPY $vgpr18
  ; CHECK-NEXT:   [[COPY14:%[0-9]+]]:vgpr_32 = COPY $vgpr17
  ; CHECK-NEXT:   [[COPY15:%[0-9]+]]:vgpr_32 = COPY $vgpr16
  ; CHECK-NEXT:   [[COPY16:%[0-9]+]]:vgpr_32 = COPY $vgpr15
  ; CHECK-NEXT:   [[COPY17:%[0-9]+]]:vgpr_32 = COPY $vgpr14
  ; CHECK-NEXT:   [[COPY18:%[0-9]+]]:vgpr_32 = COPY $vgpr13
  ; CHECK-NEXT:   [[COPY19:%[0-9]+]]:vgpr_32 = COPY $vgpr12
  ; CHECK-NEXT:   [[COPY20:%[0-9]+]]:vgpr_32 = COPY $vgpr11
  ; CHECK-NEXT:   [[COPY21:%[0-9]+]]:vgpr_32 = COPY $vgpr10
  ; CHECK-NEXT:   [[COPY22:%[0-9]+]]:vgpr_32 = COPY $vgpr9
  ; CHECK-NEXT:   [[COPY23:%[0-9]+]]:vgpr_32 = COPY $vgpr8
  ; CHECK-NEXT:   [[COPY24:%[0-9]+]]:vgpr_32 = COPY $vgpr7
  ; CHECK-NEXT:   [[COPY25:%[0-9]+]]:vgpr_32 = COPY $vgpr6
  ; CHECK-NEXT:   [[COPY26:%[0-9]+]]:vgpr_32 = COPY $vgpr5
  ; CHECK-NEXT:   [[COPY27:%[0-9]+]]:vgpr_32 = COPY $vgpr4
  ; CHECK-NEXT:   [[COPY28:%[0-9]+]]:vgpr_32 = COPY $vgpr3
  ; CHECK-NEXT:   [[COPY29:%[0-9]+]]:vgpr_32 = COPY $vgpr2
  ; CHECK-NEXT:   [[COPY30:%[0-9]+]]:vgpr_32 = COPY $vgpr1
  ; CHECK-NEXT:   [[COPY31:%[0-9]+]]:vgpr_32 = COPY $vgpr0
  ; CHECK-NEXT:   [[BUFFER_LOAD_DWORD_OFFEN:%[0-9]+]]:vgpr_32 = BUFFER_LOAD_DWORD_OFFEN %fixed-stack.2, $sgpr0_sgpr1_sgpr2_sgpr3, 0, 0, 0, 0, implicit $exec :: (load (s32) from %fixed-stack.2, align 16, addrspace 5)
  ; CHECK-NEXT:   [[BUFFER_LOAD_DWORD_OFFEN1:%[0-9]+]]:vgpr_32 = BUFFER_LOAD_DWORD_OFFEN %fixed-stack.3, $sgpr0_sgpr1_sgpr2_sgpr3, 0, 0, 0, 0, implicit $exec :: (load (s32) from %fixed-stack.3, addrspace 5)
  ; CHECK-NEXT:   [[BUFFER_LOAD_DWORD_OFFEN2:%[0-9]+]]:vgpr_32 = BUFFER_LOAD_DWORD_OFFEN %fixed-stack.4, $sgpr0_sgpr1_sgpr2_sgpr3, 0, 0, 0, 0, implicit $exec :: (load (s32) from %fixed-stack.4, align 8, addrspace 5)
  ; CHECK-NEXT:   [[BUFFER_LOAD_DWORD_OFFEN3:%[0-9]+]]:vgpr_32 = BUFFER_LOAD_DWORD_OFFEN %fixed-stack.5, $sgpr0_sgpr1_sgpr2_sgpr3, 0, 0, 0, 0, implicit $exec :: (load (s32) from %fixed-stack.5, addrspace 5)
  ; CHECK-NEXT:   [[BUFFER_LOAD_DWORD_OFFEN4:%[0-9]+]]:vgpr_32 = BUFFER_LOAD_DWORD_OFFEN %fixed-stack.6, $sgpr0_sgpr1_sgpr2_sgpr3, 0, 0, 0, 0, implicit $exec :: (load (s32) from %fixed-stack.6, align 16, addrspace 5)
  ; CHECK-NEXT:   [[BUFFER_LOAD_DWORD_OFFEN5:%[0-9]+]]:vgpr_32 = BUFFER_LOAD_DWORD_OFFEN %fixed-stack.7, $sgpr0_sgpr1_sgpr2_sgpr3, 0, 0, 0, 0, implicit $exec :: (load (s32) from %fixed-stack.7, addrspace 5)
  ; CHECK-NEXT:   [[BUFFER_LOAD_DWORD_OFFEN6:%[0-9]+]]:vgpr_32 = BUFFER_LOAD_DWORD_OFFEN %fixed-stack.8, $sgpr0_sgpr1_sgpr2_sgpr3, 0, 0, 0, 0, implicit $exec :: (load (s32) from %fixed-stack.8, align 8, addrspace 5)
  ; CHECK-NEXT:   [[BUFFER_LOAD_DWORD_OFFEN7:%[0-9]+]]:vgpr_32 = BUFFER_LOAD_DWORD_OFFEN %fixed-stack.9, $sgpr0_sgpr1_sgpr2_sgpr3, 0, 0, 0, 0, implicit $exec :: (load (s32) from %fixed-stack.9, addrspace 5)
  ; CHECK-NEXT:   [[BUFFER_LOAD_DWORD_OFFEN8:%[0-9]+]]:vgpr_32 = BUFFER_LOAD_DWORD_OFFEN %fixed-stack.10, $sgpr0_sgpr1_sgpr2_sgpr3, 0, 0, 0, 0, implicit $exec :: (load (s32) from %fixed-stack.10, align 16, addrspace 5)
  ; CHECK-NEXT:   [[BUFFER_LOAD_DWORD_OFFEN9:%[0-9]+]]:vgpr_32 = BUFFER_LOAD_DWORD_OFFEN %fixed-stack.11, $sgpr0_sgpr1_sgpr2_sgpr3, 0, 0, 0, 0, implicit $exec :: (load (s32) from %fixed-stack.11, addrspace 5)
  ; CHECK-NEXT:   [[BUFFER_LOAD_DWORD_OFFEN10:%[0-9]+]]:vgpr_32 = BUFFER_LOAD_DWORD_OFFEN %fixed-stack.12, $sgpr0_sgpr1_sgpr2_sgpr3, 0, 0, 0, 0, implicit $exec :: (load (s32) from %fixed-stack.12, align 8, addrspace 5)
  ; CHECK-NEXT:   [[BUFFER_LOAD_DWORD_OFFEN11:%[0-9]+]]:vgpr_32 = BUFFER_LOAD_DWORD_OFFEN %fixed-stack.13, $sgpr0_sgpr1_sgpr2_sgpr3, 0, 0, 0, 0, implicit $exec :: (load (s32) from %fixed-stack.13, addrspace 5)
  ; CHECK-NEXT:   [[BUFFER_LOAD_DWORD_OFFEN12:%[0-9]+]]:vgpr_32 = BUFFER_LOAD_DWORD_OFFEN %fixed-stack.14, $sgpr0_sgpr1_sgpr2_sgpr3, 0, 0, 0, 0, implicit $exec :: (load (s32) from %fixed-stack.14, align 16, addrspace 5)
  ; CHECK-NEXT:   [[BUFFER_LOAD_DWORD_OFFEN13:%[0-9]+]]:vgpr_32 = BUFFER_LOAD_DWORD_OFFEN %fixed-stack.15, $sgpr0_sgpr1_sgpr2_sgpr3, 0, 0, 0, 0, implicit $exec :: (load (s32) from %fixed-stack.15, addrspace 5)
  ; CHECK-NEXT:   [[BUFFER_LOAD_DWORD_OFFEN14:%[0-9]+]]:vgpr_32 = BUFFER_LOAD_DWORD_OFFEN %fixed-stack.16, $sgpr0_sgpr1_sgpr2_sgpr3, 0, 0, 0, 0, implicit $exec :: (load (s32) from %fixed-stack.16, align 8, addrspace 5)
  ; CHECK-NEXT:   [[BUFFER_LOAD_DWORD_OFFEN15:%[0-9]+]]:vgpr_32 = BUFFER_LOAD_DWORD_OFFEN %fixed-stack.17, $sgpr0_sgpr1_sgpr2_sgpr3, 0, 0, 0, 0, implicit $exec :: (load (s32) from %fixed-stack.17, addrspace 5)
  ; CHECK-NEXT:   [[BUFFER_LOAD_DWORD_OFFEN16:%[0-9]+]]:vgpr_32 = BUFFER_LOAD_DWORD_OFFEN %fixed-stack.18, $sgpr0_sgpr1_sgpr2_sgpr3, 0, 0, 0, 0, implicit $exec :: (load (s32) from %fixed-stack.18, align 16, addrspace 5)
  ; CHECK-NEXT:   [[BUFFER_LOAD_DWORD_OFFEN17:%[0-9]+]]:vgpr_32 = BUFFER_LOAD_DWORD_OFFEN %fixed-stack.19, $sgpr0_sgpr1_sgpr2_sgpr3, 0, 0, 0, 0, implicit $exec :: (load (s32) from %fixed-stack.19, addrspace 5)
  ; CHECK-NEXT:   [[BUFFER_LOAD_DWORD_OFFEN18:%[0-9]+]]:vgpr_32 = BUFFER_LOAD_DWORD_OFFEN %fixed-stack.20, $sgpr0_sgpr1_sgpr2_sgpr3, 0, 0, 0, 0, implicit $exec :: (load (s32) from %fixed-stack.20, align 8, addrspace 5)
  ; CHECK-NEXT:   [[BUFFER_LOAD_DWORD_OFFEN19:%[0-9]+]]:vgpr_32 = BUFFER_LOAD_DWORD_OFFEN %fixed-stack.21, $sgpr0_sgpr1_sgpr2_sgpr3, 0, 0, 0, 0, implicit $exec :: (load (s32) from %fixed-stack.21, addrspace 5)
  ; CHECK-NEXT:   [[BUFFER_LOAD_DWORD_OFFEN20:%[0-9]+]]:vgpr_32 = BUFFER_LOAD_DWORD_OFFEN %fixed-stack.22, $sgpr0_sgpr1_sgpr2_sgpr3, 0, 0, 0, 0, implicit $exec :: (load (s32) from %fixed-stack.22, align 16, addrspace 5)
  ; CHECK-NEXT:   [[BUFFER_LOAD_DWORD_OFFEN21:%[0-9]+]]:vgpr_32 = BUFFER_LOAD_DWORD_OFFEN %fixed-stack.23, $sgpr0_sgpr1_sgpr2_sgpr3, 0, 0, 0, 0, implicit $exec :: (load (s32) from %fixed-stack.23, addrspace 5)
  ; CHECK-NEXT:   [[BUFFER_LOAD_DWORD_OFFEN22:%[0-9]+]]:vgpr_32 = BUFFER_LOAD_DWORD_OFFEN %fixed-stack.24, $sgpr0_sgpr1_sgpr2_sgpr3, 0, 0, 0, 0, implicit $exec :: (load (s32) from %fixed-stack.24, align 8, addrspace 5)
  ; CHECK-NEXT:   [[BUFFER_LOAD_DWORD_OFFEN23:%[0-9]+]]:vgpr_32 = BUFFER_LOAD_DWORD_OFFEN %fixed-stack.25, $sgpr0_sgpr1_sgpr2_sgpr3, 0, 0, 0, 0, implicit $exec :: (load (s32) from %fixed-stack.25, addrspace 5)
  ; CHECK-NEXT:   [[BUFFER_LOAD_DWORD_OFFEN24:%[0-9]+]]:vgpr_32 = BUFFER_LOAD_DWORD_OFFEN %fixed-stack.26, $sgpr0_sgpr1_sgpr2_sgpr3, 0, 0, 0, 0, implicit $exec :: (load (s32) from %fixed-stack.26, align 16, addrspace 5)
  ; CHECK-NEXT:   [[BUFFER_LOAD_DWORD_OFFEN25:%[0-9]+]]:vgpr_32 = BUFFER_LOAD_DWORD_OFFEN %fixed-stack.27, $sgpr0_sgpr1_sgpr2_sgpr3, 0, 0, 0, 0, implicit $exec :: (load (s32) from %fixed-stack.27, addrspace 5)
  ; CHECK-NEXT:   [[BUFFER_LOAD_DWORD_OFFEN26:%[0-9]+]]:vgpr_32 = BUFFER_LOAD_DWORD_OFFEN %fixed-stack.28, $sgpr0_sgpr1_sgpr2_sgpr3, 0, 0, 0, 0, implicit $exec :: (load (s32) from %fixed-stack.28, align 8, addrspace 5)
  ; CHECK-NEXT:   [[BUFFER_LOAD_DWORD_OFFEN27:%[0-9]+]]:vgpr_32 = BUFFER_LOAD_DWORD_OFFEN %fixed-stack.29, $sgpr0_sgpr1_sgpr2_sgpr3, 0, 0, 0, 0, implicit $exec :: (load (s32) from %fixed-stack.29, addrspace 5)
  ; CHECK-NEXT:   [[BUFFER_LOAD_DWORD_OFFEN28:%[0-9]+]]:vgpr_32 = BUFFER_LOAD_DWORD_OFFEN %fixed-stack.30, $sgpr0_sgpr1_sgpr2_sgpr3, 0, 0, 0, 0, implicit $exec :: (load (s32) from %fixed-stack.30, align 16, addrspace 5)
  ; CHECK-NEXT:   [[BUFFER_LOAD_DWORD_OFFEN29:%[0-9]+]]:vgpr_32 = BUFFER_LOAD_DWORD_OFFEN %fixed-stack.31, $sgpr0_sgpr1_sgpr2_sgpr3, 0, 0, 0, 0, implicit $exec :: (load (s32) from %fixed-stack.31, addrspace 5)
  ; CHECK-NEXT:   [[BUFFER_LOAD_DWORD_OFFEN30:%[0-9]+]]:vgpr_32 = BUFFER_LOAD_DWORD_OFFEN %fixed-stack.32, $sgpr0_sgpr1_sgpr2_sgpr3, 0, 0, 0, 0, implicit $exec :: (load (s32) from %fixed-stack.32, align 8, addrspace 5)
  ; CHECK-NEXT:   [[BUFFER_LOAD_DWORD_OFFEN31:%[0-9]+]]:vgpr_32 = BUFFER_LOAD_DWORD_OFFEN %fixed-stack.33, $sgpr0_sgpr1_sgpr2_sgpr3, 0, 0, 0, 0, implicit $exec :: (load (s32) from %fixed-stack.33, addrspace 5)
  ; CHECK-NEXT:   [[REG_SEQUENCE:%[0-9]+]]:vreg_1024 = REG_SEQUENCE [[BUFFER_LOAD_DWORD_OFFEN31]], %subreg.sub0, [[BUFFER_LOAD_DWORD_OFFEN30]], %subreg.sub1, [[BUFFER_LOAD_DWORD_OFFEN29]], %subreg.sub2, [[BUFFER_LOAD_DWORD_OFFEN28]], %subreg.sub3, [[BUFFER_LOAD_DWORD_OFFEN27]], %subreg.sub4, [[BUFFER_LOAD_DWORD_OFFEN26]], %subreg.sub5, [[BUFFER_LOAD_DWORD_OFFEN25]], %subreg.sub6, [[BUFFER_LOAD_DWORD_OFFEN24]], %subreg.sub7, [[BUFFER_LOAD_DWORD_OFFEN23]], %subreg.sub8, [[BUFFER_LOAD_DWORD_OFFEN22]], %subreg.sub9, [[BUFFER_LOAD_DWORD_OFFEN21]], %subreg.sub10, [[BUFFER_LOAD_DWORD_OFFEN20]], %subreg.sub11, [[BUFFER_LOAD_DWORD_OFFEN19]], %subreg.sub12, [[BUFFER_LOAD_DWORD_OFFEN18]], %subreg.sub13, [[BUFFER_LOAD_DWORD_OFFEN17]], %subreg.sub14, [[BUFFER_LOAD_DWORD_OFFEN16]], %subreg.sub15, [[BUFFER_LOAD_DWORD_OFFEN15]], %subreg.sub16, [[BUFFER_LOAD_DWORD_OFFEN14]], %subreg.sub17, [[BUFFER_LOAD_DWORD_OFFEN13]], %subreg.sub18, [[BUFFER_LOAD_DWORD_OFFEN12]], %subreg.sub19, [[BUFFER_LOAD_DWORD_OFFEN11]], %subreg.sub20, [[BUFFER_LOAD_DWORD_OFFEN10]], %subreg.sub21, [[BUFFER_LOAD_DWORD_OFFEN9]], %subreg.sub22, [[BUFFER_LOAD_DWORD_OFFEN8]], %subreg.sub23, [[BUFFER_LOAD_DWORD_OFFEN7]], %subreg.sub24, [[BUFFER_LOAD_DWORD_OFFEN6]], %subreg.sub25, [[BUFFER_LOAD_DWORD_OFFEN5]], %subreg.sub26, [[BUFFER_LOAD_DWORD_OFFEN4]], %subreg.sub27, [[BUFFER_LOAD_DWORD_OFFEN3]], %subreg.sub28, [[BUFFER_LOAD_DWORD_OFFEN2]], %subreg.sub29, [[BUFFER_LOAD_DWORD_OFFEN1]], %subreg.sub30, [[BUFFER_LOAD_DWORD_OFFEN]], %subreg.sub31
  ; CHECK-NEXT:   [[BUFFER_LOAD_DWORD_OFFEN32:%[0-9]+]]:vgpr_32 = BUFFER_LOAD_DWORD_OFFEN %fixed-stack.34, $sgpr0_sgpr1_sgpr2_sgpr3, 0, 0, 0, 0, implicit $exec :: (load (s32) from %fixed-stack.34, align 16, addrspace 5)
  ; CHECK-NEXT:   [[REG_SEQUENCE1:%[0-9]+]]:vreg_1024 = REG_SEQUENCE [[COPY31]], %subreg.sub0, [[COPY30]], %subreg.sub1, [[COPY29]], %subreg.sub2, [[COPY28]], %subreg.sub3, [[COPY27]], %subreg.sub4, [[COPY26]], %subreg.sub5, [[COPY25]], %subreg.sub6, [[COPY24]], %subreg.sub7, [[COPY23]], %subreg.sub8, [[COPY22]], %subreg.sub9, [[COPY21]], %subreg.sub10, [[COPY20]], %subreg.sub11, [[COPY19]], %subreg.sub12, [[COPY18]], %subreg.sub13, [[COPY17]], %subreg.sub14, [[COPY16]], %subreg.sub15, [[COPY15]], %subreg.sub16, [[COPY14]], %subreg.sub17, [[COPY13]], %subreg.sub18, [[COPY12]], %subreg.sub19, [[COPY11]], %subreg.sub20, [[COPY10]], %subreg.sub21, [[COPY9]], %subreg.sub22, [[COPY8]], %subreg.sub23, [[COPY7]], %subreg.sub24, [[COPY6]], %subreg.sub25, [[COPY5]], %subreg.sub26, [[COPY4]], %subreg.sub27, [[COPY3]], %subreg.sub28, [[COPY2]], %subreg.sub29, [[COPY1]], %subreg.sub30, [[BUFFER_LOAD_DWORD_OFFEN32]], %subreg.sub31
  ; CHECK-NEXT:   [[BUFFER_LOAD_DWORD_OFFEN33:%[0-9]+]]:vgpr_32 = BUFFER_LOAD_DWORD_OFFEN %fixed-stack.0, $sgpr0_sgpr1_sgpr2_sgpr3, 0, 0, 0, 0, implicit $exec :: (load (s32) from %fixed-stack.0, align 8, addrspace 5)
  ; CHECK-NEXT:   [[BUFFER_LOAD_DWORD_OFFEN34:%[0-9]+]]:vgpr_32 = BUFFER_LOAD_DWORD_OFFEN %fixed-stack.1, $sgpr0_sgpr1_sgpr2_sgpr3, 0, 0, 0, 0, implicit $exec :: (load (s32) from %fixed-stack.1, addrspace 5)
  ; CHECK-NEXT:   [[COPY32:%[0-9]+]]:vreg_1024 = COPY [[REG_SEQUENCE]]
  ; CHECK-NEXT:   [[COPY33:%[0-9]+]]:vreg_1024 = COPY [[REG_SEQUENCE1]]
  ; CHECK-NEXT:   [[V_AND_B32_e32_:%[0-9]+]]:vgpr_32 = V_AND_B32_e32 1023, [[COPY]], implicit $exec
  ; CHECK-NEXT:   [[V_LSHLREV_B32_e32_:%[0-9]+]]:vgpr_32 = nuw nsw V_LSHLREV_B32_e32 7, [[V_AND_B32_e32_]], implicit $exec
  ; CHECK-NEXT:   [[V_ADD_CO_U32_e64_:%[0-9]+]]:vgpr_32, [[V_ADD_CO_U32_e64_1:%[0-9]+]]:sreg_64_xexec = V_ADD_CO_U32_e64 [[BUFFER_LOAD_DWORD_OFFEN34]], [[V_LSHLREV_B32_e32_]], 0, implicit $exec
  ; CHECK-NEXT:   [[V_ADDC_U32_e64_:%[0-9]+]]:vgpr_32, dead [[V_ADDC_U32_e64_1:%[0-9]+]]:sreg_64_xexec = V_ADDC_U32_e64 0, [[BUFFER_LOAD_DWORD_OFFEN33]], [[V_ADD_CO_U32_e64_1]], 0, implicit $exec
  ; CHECK-NEXT:   [[REG_SEQUENCE2:%[0-9]+]]:vreg_64 = REG_SEQUENCE [[V_ADD_CO_U32_e64_]], %subreg.sub0, [[V_ADDC_U32_e64_]], %subreg.sub1
  ; CHECK-NEXT:   [[V_ADD_CO_U32_e64_2:%[0-9]+]]:vgpr_32, [[V_ADD_CO_U32_e64_3:%[0-9]+]]:sreg_64_xexec = V_ADD_CO_U32_e64 [[V_ADD_CO_U32_e64_]], [[V_LSHLREV_B32_e32_]], 0, implicit $exec
  ; CHECK-NEXT:   [[V_ADDC_U32_e64_2:%[0-9]+]]:vgpr_32, dead [[V_ADDC_U32_e64_3:%[0-9]+]]:sreg_64_xexec = V_ADDC_U32_e64 0, [[V_ADDC_U32_e64_]], [[V_ADD_CO_U32_e64_3]], 0, implicit $exec
  ; CHECK-NEXT:   [[REG_SEQUENCE3:%[0-9]+]]:vreg_64 = REG_SEQUENCE [[V_ADD_CO_U32_e64_2]], %subreg.sub0, [[V_ADDC_U32_e64_2]], %subreg.sub1
  ; CHECK-NEXT:   [[V_ADD_CO_U32_e64_4:%[0-9]+]]:vgpr_32, [[V_ADD_CO_U32_e64_5:%[0-9]+]]:sreg_64_xexec = V_ADD_CO_U32_e64 [[V_ADD_CO_U32_e64_2]], [[V_LSHLREV_B32_e32_]], 0, implicit $exec
  ; CHECK-NEXT:   [[V_ADDC_U32_e64_4:%[0-9]+]]:vgpr_32, dead [[V_ADDC_U32_e64_5:%[0-9]+]]:sreg_64_xexec = V_ADDC_U32_e64 0, [[V_ADDC_U32_e64_2]], [[V_ADD_CO_U32_e64_5]], 0, implicit $exec
  ; CHECK-NEXT:   [[REG_SEQUENCE4:%[0-9]+]]:vreg_64 = REG_SEQUENCE [[V_ADD_CO_U32_e64_4]], %subreg.sub0, [[V_ADDC_U32_e64_4]], %subreg.sub1
  ; CHECK-NEXT:   [[V_ADD_CO_U32_e64_6:%[0-9]+]]:vgpr_32, [[V_ADD_CO_U32_e64_7:%[0-9]+]]:sreg_64_xexec = V_ADD_CO_U32_e64 [[V_ADD_CO_U32_e64_4]], [[V_LSHLREV_B32_e32_]], 0, implicit $exec
  ; CHECK-NEXT:   [[V_ADDC_U32_e64_6:%[0-9]+]]:vgpr_32, dead [[V_ADDC_U32_e64_7:%[0-9]+]]:sreg_64_xexec = V_ADDC_U32_e64 0, [[V_ADDC_U32_e64_4]], [[V_ADD_CO_U32_e64_7]], 0, implicit $exec
  ; CHECK-NEXT:   [[REG_SEQUENCE5:%[0-9]+]]:vreg_64 = REG_SEQUENCE [[V_ADD_CO_U32_e64_6]], %subreg.sub0, [[V_ADDC_U32_e64_6]], %subreg.sub1
  ; CHECK-NEXT:   [[V_ADD_CO_U32_e64_8:%[0-9]+]]:vgpr_32, [[V_ADD_CO_U32_e64_9:%[0-9]+]]:sreg_64_xexec = V_ADD_CO_U32_e64 [[V_ADD_CO_U32_e64_6]], [[V_LSHLREV_B32_e32_]], 0, implicit $exec
  ; CHECK-NEXT:   [[V_ADDC_U32_e64_8:%[0-9]+]]:vgpr_32, dead [[V_ADDC_U32_e64_9:%[0-9]+]]:sreg_64_xexec = V_ADDC_U32_e64 0, [[V_ADDC_U32_e64_6]], [[V_ADD_CO_U32_e64_9]], 0, implicit $exec
  ; CHECK-NEXT:   [[REG_SEQUENCE6:%[0-9]+]]:vreg_64 = REG_SEQUENCE [[V_ADD_CO_U32_e64_8]], %subreg.sub0, [[V_ADDC_U32_e64_8]], %subreg.sub1
  ; CHECK-NEXT:   [[V_ADD_CO_U32_e64_10:%[0-9]+]]:vgpr_32, [[V_ADD_CO_U32_e64_11:%[0-9]+]]:sreg_64_xexec = V_ADD_CO_U32_e64 [[V_ADD_CO_U32_e64_8]], [[V_LSHLREV_B32_e32_]], 0, implicit $exec
  ; CHECK-NEXT:   [[V_ADDC_U32_e64_10:%[0-9]+]]:vgpr_32, dead [[V_ADDC_U32_e64_11:%[0-9]+]]:sreg_64_xexec = V_ADDC_U32_e64 0, [[V_ADDC_U32_e64_8]], [[V_ADD_CO_U32_e64_11]], 0, implicit $exec
  ; CHECK-NEXT:   [[REG_SEQUENCE7:%[0-9]+]]:vreg_64 = REG_SEQUENCE [[V_ADD_CO_U32_e64_10]], %subreg.sub0, [[V_ADDC_U32_e64_10]], %subreg.sub1
  ; CHECK-NEXT:   [[V_ADD_CO_U32_e64_12:%[0-9]+]]:vgpr_32, [[V_ADD_CO_U32_e64_13:%[0-9]+]]:sreg_64_xexec = V_ADD_CO_U32_e64 [[V_ADD_CO_U32_e64_10]], [[V_LSHLREV_B32_e32_]], 0, implicit $exec
  ; CHECK-NEXT:   [[V_ADDC_U32_e64_12:%[0-9]+]]:vgpr_32, dead [[V_ADDC_U32_e64_13:%[0-9]+]]:sreg_64_xexec = V_ADDC_U32_e64 0, [[V_ADDC_U32_e64_10]], [[V_ADD_CO_U32_e64_13]], 0, implicit $exec
  ; CHECK-NEXT:   [[REG_SEQUENCE8:%[0-9]+]]:vreg_64 = REG_SEQUENCE [[V_ADD_CO_U32_e64_12]], %subreg.sub0, [[V_ADDC_U32_e64_12]], %subreg.sub1
  ; CHECK-NEXT:   [[GLOBAL_LOAD_DWORDX4_:%[0-9]+]]:vreg_128 = GLOBAL_LOAD_DWORDX4 [[REG_SEQUENCE2]], 112, 0, implicit $exec :: (volatile load (s128) from %ir.p1 + 112, addrspace 1)
  ; CHECK-NEXT:   [[COPY34:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_]].sub3
  ; CHECK-NEXT:   [[COPY35:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_]].sub2
  ; CHECK-NEXT:   [[COPY36:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_]].sub1
  ; CHECK-NEXT:   [[COPY37:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_]].sub0
  ; CHECK-NEXT:   [[GLOBAL_LOAD_DWORDX4_1:%[0-9]+]]:vreg_128 = GLOBAL_LOAD_DWORDX4 [[REG_SEQUENCE2]], 96, 0, implicit $exec :: (volatile load (s128) from %ir.p1 + 96, align 32, addrspace 1)
  ; CHECK-NEXT:   [[COPY38:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_1]].sub3
  ; CHECK-NEXT:   [[COPY39:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_1]].sub2
  ; CHECK-NEXT:   [[COPY40:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_1]].sub1
  ; CHECK-NEXT:   [[COPY41:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_1]].sub0
  ; CHECK-NEXT:   [[GLOBAL_LOAD_DWORDX4_2:%[0-9]+]]:vreg_128 = GLOBAL_LOAD_DWORDX4 [[REG_SEQUENCE2]], 80, 0, implicit $exec :: (volatile load (s128) from %ir.p1 + 80, addrspace 1)
  ; CHECK-NEXT:   [[COPY42:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_2]].sub3
  ; CHECK-NEXT:   [[COPY43:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_2]].sub2
  ; CHECK-NEXT:   [[COPY44:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_2]].sub1
  ; CHECK-NEXT:   [[COPY45:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_2]].sub0
  ; CHECK-NEXT:   [[GLOBAL_LOAD_DWORDX4_3:%[0-9]+]]:vreg_128 = GLOBAL_LOAD_DWORDX4 [[REG_SEQUENCE2]], 64, 0, implicit $exec :: (volatile load (s128) from %ir.p1 + 64, align 64, addrspace 1)
  ; CHECK-NEXT:   [[COPY46:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_3]].sub3
  ; CHECK-NEXT:   [[COPY47:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_3]].sub2
  ; CHECK-NEXT:   [[COPY48:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_3]].sub1
  ; CHECK-NEXT:   [[COPY49:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_3]].sub0
  ; CHECK-NEXT:   [[GLOBAL_LOAD_DWORDX4_4:%[0-9]+]]:vreg_128 = GLOBAL_LOAD_DWORDX4 [[REG_SEQUENCE2]], 48, 0, implicit $exec :: (volatile load (s128) from %ir.p1 + 48, addrspace 1)
  ; CHECK-NEXT:   [[COPY50:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_4]].sub3
  ; CHECK-NEXT:   [[COPY51:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_4]].sub2
  ; CHECK-NEXT:   [[COPY52:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_4]].sub1
  ; CHECK-NEXT:   [[COPY53:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_4]].sub0
  ; CHECK-NEXT:   [[GLOBAL_LOAD_DWORDX4_5:%[0-9]+]]:vreg_128 = GLOBAL_LOAD_DWORDX4 [[REG_SEQUENCE2]], 32, 0, implicit $exec :: (volatile load (s128) from %ir.p1 + 32, align 32, addrspace 1)
  ; CHECK-NEXT:   [[COPY54:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_5]].sub3
  ; CHECK-NEXT:   [[COPY55:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_5]].sub2
  ; CHECK-NEXT:   [[COPY56:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_5]].sub1
  ; CHECK-NEXT:   [[COPY57:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_5]].sub0
  ; CHECK-NEXT:   [[GLOBAL_LOAD_DWORDX4_6:%[0-9]+]]:vreg_128 = GLOBAL_LOAD_DWORDX4 [[REG_SEQUENCE2]], 16, 0, implicit $exec :: (volatile load (s128) from %ir.p1 + 16, addrspace 1)
  ; CHECK-NEXT:   [[COPY58:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_6]].sub3
  ; CHECK-NEXT:   [[COPY59:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_6]].sub2
  ; CHECK-NEXT:   [[COPY60:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_6]].sub1
  ; CHECK-NEXT:   [[COPY61:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_6]].sub0
  ; CHECK-NEXT:   [[GLOBAL_LOAD_DWORDX4_7:%[0-9]+]]:vreg_128 = GLOBAL_LOAD_DWORDX4 [[REG_SEQUENCE2]], 0, 0, implicit $exec :: (volatile load (s128) from %ir.p1, align 128, addrspace 1)
  ; CHECK-NEXT:   [[COPY62:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_7]].sub3
  ; CHECK-NEXT:   [[COPY63:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_7]].sub2
  ; CHECK-NEXT:   [[COPY64:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_7]].sub1
  ; CHECK-NEXT:   [[COPY65:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_7]].sub0
  ; CHECK-NEXT:   [[REG_SEQUENCE9:%[0-9]+]]:vreg_1024 = REG_SEQUENCE [[COPY65]], %subreg.sub0, [[COPY64]], %subreg.sub1, [[COPY63]], %subreg.sub2, [[COPY62]], %subreg.sub3, [[COPY61]], %subreg.sub4, [[COPY60]], %subreg.sub5, [[COPY59]], %subreg.sub6, [[COPY58]], %subreg.sub7, [[COPY57]], %subreg.sub8, [[COPY56]], %subreg.sub9, [[COPY55]], %subreg.sub10, [[COPY54]], %subreg.sub11, [[COPY53]], %subreg.sub12, [[COPY52]], %subreg.sub13, [[COPY51]], %subreg.sub14, [[COPY50]], %subreg.sub15, [[COPY49]], %subreg.sub16, [[COPY48]], %subreg.sub17, [[COPY47]], %subreg.sub18, [[COPY46]], %subreg.sub19, [[COPY45]], %subreg.sub20, [[COPY44]], %subreg.sub21, [[COPY43]], %subreg.sub22, [[COPY42]], %subreg.sub23, [[COPY41]], %subreg.sub24, [[COPY40]], %subreg.sub25, [[COPY39]], %subreg.sub26, [[COPY38]], %subreg.sub27, [[COPY37]], %subreg.sub28, [[COPY36]], %subreg.sub29, [[COPY35]], %subreg.sub30, [[COPY34]], %subreg.sub31
  ; CHECK-NEXT:   [[COPY66:%[0-9]+]]:vreg_1024 = COPY [[REG_SEQUENCE9]]
  ; CHECK-NEXT:   [[GLOBAL_LOAD_DWORDX4_8:%[0-9]+]]:vreg_128 = GLOBAL_LOAD_DWORDX4 [[REG_SEQUENCE3]], 112, 0, implicit $exec :: (volatile load (s128) from %ir.p2 + 112, addrspace 1)
  ; CHECK-NEXT:   [[COPY67:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_8]].sub3
  ; CHECK-NEXT:   [[COPY68:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_8]].sub2
  ; CHECK-NEXT:   [[COPY69:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_8]].sub1
  ; CHECK-NEXT:   [[COPY70:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_8]].sub0
  ; CHECK-NEXT:   [[GLOBAL_LOAD_DWORDX4_9:%[0-9]+]]:vreg_128 = GLOBAL_LOAD_DWORDX4 [[REG_SEQUENCE3]], 96, 0, implicit $exec :: (volatile load (s128) from %ir.p2 + 96, align 32, addrspace 1)
  ; CHECK-NEXT:   [[COPY71:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_9]].sub3
  ; CHECK-NEXT:   [[COPY72:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_9]].sub2
  ; CHECK-NEXT:   [[COPY73:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_9]].sub1
  ; CHECK-NEXT:   [[COPY74:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_9]].sub0
  ; CHECK-NEXT:   [[GLOBAL_LOAD_DWORDX4_10:%[0-9]+]]:vreg_128 = GLOBAL_LOAD_DWORDX4 [[REG_SEQUENCE3]], 80, 0, implicit $exec :: (volatile load (s128) from %ir.p2 + 80, addrspace 1)
  ; CHECK-NEXT:   [[COPY75:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_10]].sub3
  ; CHECK-NEXT:   [[COPY76:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_10]].sub2
  ; CHECK-NEXT:   [[COPY77:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_10]].sub1
  ; CHECK-NEXT:   [[COPY78:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_10]].sub0
  ; CHECK-NEXT:   [[GLOBAL_LOAD_DWORDX4_11:%[0-9]+]]:vreg_128 = GLOBAL_LOAD_DWORDX4 [[REG_SEQUENCE3]], 64, 0, implicit $exec :: (volatile load (s128) from %ir.p2 + 64, align 64, addrspace 1)
  ; CHECK-NEXT:   [[COPY79:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_11]].sub3
  ; CHECK-NEXT:   [[COPY80:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_11]].sub2
  ; CHECK-NEXT:   [[COPY81:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_11]].sub1
  ; CHECK-NEXT:   [[COPY82:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_11]].sub0
  ; CHECK-NEXT:   [[GLOBAL_LOAD_DWORDX4_12:%[0-9]+]]:vreg_128 = GLOBAL_LOAD_DWORDX4 [[REG_SEQUENCE3]], 48, 0, implicit $exec :: (volatile load (s128) from %ir.p2 + 48, addrspace 1)
  ; CHECK-NEXT:   [[COPY83:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_12]].sub3
  ; CHECK-NEXT:   [[COPY84:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_12]].sub2
  ; CHECK-NEXT:   [[COPY85:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_12]].sub1
  ; CHECK-NEXT:   [[COPY86:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_12]].sub0
  ; CHECK-NEXT:   [[GLOBAL_LOAD_DWORDX4_13:%[0-9]+]]:vreg_128 = GLOBAL_LOAD_DWORDX4 [[REG_SEQUENCE3]], 32, 0, implicit $exec :: (volatile load (s128) from %ir.p2 + 32, align 32, addrspace 1)
  ; CHECK-NEXT:   [[COPY87:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_13]].sub3
  ; CHECK-NEXT:   [[COPY88:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_13]].sub2
  ; CHECK-NEXT:   [[COPY89:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_13]].sub1
  ; CHECK-NEXT:   [[COPY90:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_13]].sub0
  ; CHECK-NEXT:   [[GLOBAL_LOAD_DWORDX4_14:%[0-9]+]]:vreg_128 = GLOBAL_LOAD_DWORDX4 [[REG_SEQUENCE3]], 16, 0, implicit $exec :: (volatile load (s128) from %ir.p2 + 16, addrspace 1)
  ; CHECK-NEXT:   [[COPY91:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_14]].sub3
  ; CHECK-NEXT:   [[COPY92:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_14]].sub2
  ; CHECK-NEXT:   [[COPY93:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_14]].sub1
  ; CHECK-NEXT:   [[COPY94:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_14]].sub0
  ; CHECK-NEXT:   [[GLOBAL_LOAD_DWORDX4_15:%[0-9]+]]:vreg_128 = GLOBAL_LOAD_DWORDX4 [[REG_SEQUENCE3]], 0, 0, implicit $exec :: (volatile load (s128) from %ir.p2, align 128, addrspace 1)
  ; CHECK-NEXT:   [[COPY95:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_15]].sub3
  ; CHECK-NEXT:   [[COPY96:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_15]].sub2
  ; CHECK-NEXT:   [[COPY97:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_15]].sub1
  ; CHECK-NEXT:   [[COPY98:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_15]].sub0
  ; CHECK-NEXT:   [[REG_SEQUENCE10:%[0-9]+]]:vreg_1024 = REG_SEQUENCE [[COPY98]], %subreg.sub0, [[COPY97]], %subreg.sub1, [[COPY96]], %subreg.sub2, [[COPY95]], %subreg.sub3, [[COPY94]], %subreg.sub4, [[COPY93]], %subreg.sub5, [[COPY92]], %subreg.sub6, [[COPY91]], %subreg.sub7, [[COPY90]], %subreg.sub8, [[COPY89]], %subreg.sub9, [[COPY88]], %subreg.sub10, [[COPY87]], %subreg.sub11, [[COPY86]], %subreg.sub12, [[COPY85]], %subreg.sub13, [[COPY84]], %subreg.sub14, [[COPY83]], %subreg.sub15, [[COPY82]], %subreg.sub16, [[COPY81]], %subreg.sub17, [[COPY80]], %subreg.sub18, [[COPY79]], %subreg.sub19, [[COPY78]], %subreg.sub20, [[COPY77]], %subreg.sub21, [[COPY76]], %subreg.sub22, [[COPY75]], %subreg.sub23, [[COPY74]], %subreg.sub24, [[COPY73]], %subreg.sub25, [[COPY72]], %subreg.sub26, [[COPY71]], %subreg.sub27, [[COPY70]], %subreg.sub28, [[COPY69]], %subreg.sub29, [[COPY68]], %subreg.sub30, [[COPY67]], %subreg.sub31
  ; CHECK-NEXT:   [[COPY99:%[0-9]+]]:vreg_1024 = COPY [[REG_SEQUENCE10]]
  ; CHECK-NEXT:   [[GLOBAL_LOAD_DWORDX4_16:%[0-9]+]]:vreg_128 = GLOBAL_LOAD_DWORDX4 [[REG_SEQUENCE4]], 112, 0, implicit $exec :: (volatile load (s128) from %ir.p3 + 112, addrspace 1)
  ; CHECK-NEXT:   [[COPY100:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_16]].sub3
  ; CHECK-NEXT:   [[COPY101:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_16]].sub2
  ; CHECK-NEXT:   [[COPY102:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_16]].sub1
  ; CHECK-NEXT:   [[COPY103:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_16]].sub0
  ; CHECK-NEXT:   [[GLOBAL_LOAD_DWORDX4_17:%[0-9]+]]:vreg_128 = GLOBAL_LOAD_DWORDX4 [[REG_SEQUENCE4]], 96, 0, implicit $exec :: (volatile load (s128) from %ir.p3 + 96, align 32, addrspace 1)
  ; CHECK-NEXT:   [[COPY104:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_17]].sub3
  ; CHECK-NEXT:   [[COPY105:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_17]].sub2
  ; CHECK-NEXT:   [[COPY106:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_17]].sub1
  ; CHECK-NEXT:   [[COPY107:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_17]].sub0
  ; CHECK-NEXT:   [[GLOBAL_LOAD_DWORDX4_18:%[0-9]+]]:vreg_128 = GLOBAL_LOAD_DWORDX4 [[REG_SEQUENCE4]], 80, 0, implicit $exec :: (volatile load (s128) from %ir.p3 + 80, addrspace 1)
  ; CHECK-NEXT:   [[COPY108:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_18]].sub3
  ; CHECK-NEXT:   [[COPY109:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_18]].sub2
  ; CHECK-NEXT:   [[COPY110:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_18]].sub1
  ; CHECK-NEXT:   [[COPY111:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_18]].sub0
  ; CHECK-NEXT:   [[GLOBAL_LOAD_DWORDX4_19:%[0-9]+]]:vreg_128 = GLOBAL_LOAD_DWORDX4 [[REG_SEQUENCE4]], 64, 0, implicit $exec :: (volatile load (s128) from %ir.p3 + 64, align 64, addrspace 1)
  ; CHECK-NEXT:   [[COPY112:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_19]].sub3
  ; CHECK-NEXT:   [[COPY113:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_19]].sub2
  ; CHECK-NEXT:   [[COPY114:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_19]].sub1
  ; CHECK-NEXT:   [[COPY115:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_19]].sub0
  ; CHECK-NEXT:   [[GLOBAL_LOAD_DWORDX4_20:%[0-9]+]]:vreg_128 = GLOBAL_LOAD_DWORDX4 [[REG_SEQUENCE4]], 48, 0, implicit $exec :: (volatile load (s128) from %ir.p3 + 48, addrspace 1)
  ; CHECK-NEXT:   [[COPY116:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_20]].sub3
  ; CHECK-NEXT:   [[COPY117:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_20]].sub2
  ; CHECK-NEXT:   [[COPY118:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_20]].sub1
  ; CHECK-NEXT:   [[COPY119:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_20]].sub0
  ; CHECK-NEXT:   [[GLOBAL_LOAD_DWORDX4_21:%[0-9]+]]:vreg_128 = GLOBAL_LOAD_DWORDX4 [[REG_SEQUENCE4]], 32, 0, implicit $exec :: (volatile load (s128) from %ir.p3 + 32, align 32, addrspace 1)
  ; CHECK-NEXT:   [[COPY120:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_21]].sub3
  ; CHECK-NEXT:   [[COPY121:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_21]].sub2
  ; CHECK-NEXT:   [[COPY122:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_21]].sub1
  ; CHECK-NEXT:   [[COPY123:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_21]].sub0
  ; CHECK-NEXT:   [[GLOBAL_LOAD_DWORDX4_22:%[0-9]+]]:vreg_128 = GLOBAL_LOAD_DWORDX4 [[REG_SEQUENCE4]], 16, 0, implicit $exec :: (volatile load (s128) from %ir.p3 + 16, addrspace 1)
  ; CHECK-NEXT:   [[COPY124:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_22]].sub3
  ; CHECK-NEXT:   [[COPY125:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_22]].sub2
  ; CHECK-NEXT:   [[COPY126:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_22]].sub1
  ; CHECK-NEXT:   [[COPY127:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_22]].sub0
  ; CHECK-NEXT:   [[GLOBAL_LOAD_DWORDX4_23:%[0-9]+]]:vreg_128 = GLOBAL_LOAD_DWORDX4 [[REG_SEQUENCE4]], 0, 0, implicit $exec :: (volatile load (s128) from %ir.p3, align 128, addrspace 1)
  ; CHECK-NEXT:   [[COPY128:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_23]].sub3
  ; CHECK-NEXT:   [[COPY129:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_23]].sub2
  ; CHECK-NEXT:   [[COPY130:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_23]].sub1
  ; CHECK-NEXT:   [[COPY131:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_23]].sub0
  ; CHECK-NEXT:   [[REG_SEQUENCE11:%[0-9]+]]:vreg_1024 = REG_SEQUENCE [[COPY131]], %subreg.sub0, [[COPY130]], %subreg.sub1, [[COPY129]], %subreg.sub2, [[COPY128]], %subreg.sub3, [[COPY127]], %subreg.sub4, [[COPY126]], %subreg.sub5, [[COPY125]], %subreg.sub6, [[COPY124]], %subreg.sub7, [[COPY123]], %subreg.sub8, [[COPY122]], %subreg.sub9, [[COPY121]], %subreg.sub10, [[COPY120]], %subreg.sub11, [[COPY119]], %subreg.sub12, [[COPY118]], %subreg.sub13, [[COPY117]], %subreg.sub14, [[COPY116]], %subreg.sub15, [[COPY115]], %subreg.sub16, [[COPY114]], %subreg.sub17, [[COPY113]], %subreg.sub18, [[COPY112]], %subreg.sub19, [[COPY111]], %subreg.sub20, [[COPY110]], %subreg.sub21, [[COPY109]], %subreg.sub22, [[COPY108]], %subreg.sub23, [[COPY107]], %subreg.sub24, [[COPY106]], %subreg.sub25, [[COPY105]], %subreg.sub26, [[COPY104]], %subreg.sub27, [[COPY103]], %subreg.sub28, [[COPY102]], %subreg.sub29, [[COPY101]], %subreg.sub30, [[COPY100]], %subreg.sub31
  ; CHECK-NEXT:   [[COPY132:%[0-9]+]]:vreg_1024 = COPY [[REG_SEQUENCE11]]
  ; CHECK-NEXT:   [[GLOBAL_LOAD_DWORDX4_24:%[0-9]+]]:vreg_128 = GLOBAL_LOAD_DWORDX4 [[REG_SEQUENCE5]], 112, 0, implicit $exec :: (volatile load (s128) from %ir.p4 + 112, addrspace 1)
  ; CHECK-NEXT:   [[COPY133:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_24]].sub3
  ; CHECK-NEXT:   [[COPY134:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_24]].sub2
  ; CHECK-NEXT:   [[COPY135:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_24]].sub1
  ; CHECK-NEXT:   [[COPY136:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_24]].sub0
  ; CHECK-NEXT:   [[GLOBAL_LOAD_DWORDX4_25:%[0-9]+]]:vreg_128 = GLOBAL_LOAD_DWORDX4 [[REG_SEQUENCE5]], 96, 0, implicit $exec :: (volatile load (s128) from %ir.p4 + 96, align 32, addrspace 1)
  ; CHECK-NEXT:   [[COPY137:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_25]].sub3
  ; CHECK-NEXT:   [[COPY138:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_25]].sub2
  ; CHECK-NEXT:   [[COPY139:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_25]].sub1
  ; CHECK-NEXT:   [[COPY140:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_25]].sub0
  ; CHECK-NEXT:   [[GLOBAL_LOAD_DWORDX4_26:%[0-9]+]]:vreg_128 = GLOBAL_LOAD_DWORDX4 [[REG_SEQUENCE5]], 80, 0, implicit $exec :: (volatile load (s128) from %ir.p4 + 80, addrspace 1)
  ; CHECK-NEXT:   [[COPY141:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_26]].sub3
  ; CHECK-NEXT:   [[COPY142:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_26]].sub2
  ; CHECK-NEXT:   [[COPY143:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_26]].sub1
  ; CHECK-NEXT:   [[COPY144:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_26]].sub0
  ; CHECK-NEXT:   [[GLOBAL_LOAD_DWORDX4_27:%[0-9]+]]:vreg_128 = GLOBAL_LOAD_DWORDX4 [[REG_SEQUENCE5]], 64, 0, implicit $exec :: (volatile load (s128) from %ir.p4 + 64, align 64, addrspace 1)
  ; CHECK-NEXT:   [[COPY145:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_27]].sub3
  ; CHECK-NEXT:   [[COPY146:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_27]].sub2
  ; CHECK-NEXT:   [[COPY147:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_27]].sub1
  ; CHECK-NEXT:   [[COPY148:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_27]].sub0
  ; CHECK-NEXT:   [[GLOBAL_LOAD_DWORDX4_28:%[0-9]+]]:vreg_128 = GLOBAL_LOAD_DWORDX4 [[REG_SEQUENCE5]], 48, 0, implicit $exec :: (volatile load (s128) from %ir.p4 + 48, addrspace 1)
  ; CHECK-NEXT:   [[COPY149:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_28]].sub3
  ; CHECK-NEXT:   [[COPY150:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_28]].sub2
  ; CHECK-NEXT:   [[COPY151:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_28]].sub1
  ; CHECK-NEXT:   [[COPY152:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_28]].sub0
  ; CHECK-NEXT:   [[GLOBAL_LOAD_DWORDX4_29:%[0-9]+]]:vreg_128 = GLOBAL_LOAD_DWORDX4 [[REG_SEQUENCE5]], 32, 0, implicit $exec :: (volatile load (s128) from %ir.p4 + 32, align 32, addrspace 1)
  ; CHECK-NEXT:   [[COPY153:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_29]].sub3
  ; CHECK-NEXT:   [[COPY154:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_29]].sub2
  ; CHECK-NEXT:   [[COPY155:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_29]].sub1
  ; CHECK-NEXT:   [[COPY156:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_29]].sub0
  ; CHECK-NEXT:   [[GLOBAL_LOAD_DWORDX4_30:%[0-9]+]]:vreg_128 = GLOBAL_LOAD_DWORDX4 [[REG_SEQUENCE5]], 16, 0, implicit $exec :: (volatile load (s128) from %ir.p4 + 16, addrspace 1)
  ; CHECK-NEXT:   [[COPY157:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_30]].sub3
  ; CHECK-NEXT:   [[COPY158:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_30]].sub2
  ; CHECK-NEXT:   [[COPY159:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_30]].sub1
  ; CHECK-NEXT:   [[COPY160:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_30]].sub0
  ; CHECK-NEXT:   [[GLOBAL_LOAD_DWORDX4_31:%[0-9]+]]:vreg_128 = GLOBAL_LOAD_DWORDX4 [[REG_SEQUENCE5]], 0, 0, implicit $exec :: (volatile load (s128) from %ir.p4, align 128, addrspace 1)
  ; CHECK-NEXT:   [[COPY161:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_31]].sub3
  ; CHECK-NEXT:   [[COPY162:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_31]].sub2
  ; CHECK-NEXT:   [[COPY163:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_31]].sub1
  ; CHECK-NEXT:   [[COPY164:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_31]].sub0
  ; CHECK-NEXT:   [[REG_SEQUENCE12:%[0-9]+]]:vreg_1024 = REG_SEQUENCE [[COPY164]], %subreg.sub0, [[COPY163]], %subreg.sub1, [[COPY162]], %subreg.sub2, [[COPY161]], %subreg.sub3, [[COPY160]], %subreg.sub4, [[COPY159]], %subreg.sub5, [[COPY158]], %subreg.sub6, [[COPY157]], %subreg.sub7, [[COPY156]], %subreg.sub8, [[COPY155]], %subreg.sub9, [[COPY154]], %subreg.sub10, [[COPY153]], %subreg.sub11, [[COPY152]], %subreg.sub12, [[COPY151]], %subreg.sub13, [[COPY150]], %subreg.sub14, [[COPY149]], %subreg.sub15, [[COPY148]], %subreg.sub16, [[COPY147]], %subreg.sub17, [[COPY146]], %subreg.sub18, [[COPY145]], %subreg.sub19, [[COPY144]], %subreg.sub20, [[COPY143]], %subreg.sub21, [[COPY142]], %subreg.sub22, [[COPY141]], %subreg.sub23, [[COPY140]], %subreg.sub24, [[COPY139]], %subreg.sub25, [[COPY138]], %subreg.sub26, [[COPY137]], %subreg.sub27, [[COPY136]], %subreg.sub28, [[COPY135]], %subreg.sub29, [[COPY134]], %subreg.sub30, [[COPY133]], %subreg.sub31
  ; CHECK-NEXT:   [[COPY165:%[0-9]+]]:vreg_1024 = COPY [[REG_SEQUENCE12]]
  ; CHECK-NEXT:   [[GLOBAL_LOAD_DWORDX4_32:%[0-9]+]]:vreg_128 = GLOBAL_LOAD_DWORDX4 [[REG_SEQUENCE6]], 112, 0, implicit $exec :: (volatile load (s128) from %ir.p5 + 112, addrspace 1)
  ; CHECK-NEXT:   [[COPY166:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_32]].sub3
  ; CHECK-NEXT:   [[COPY167:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_32]].sub2
  ; CHECK-NEXT:   [[COPY168:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_32]].sub1
  ; CHECK-NEXT:   [[COPY169:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_32]].sub0
  ; CHECK-NEXT:   [[GLOBAL_LOAD_DWORDX4_33:%[0-9]+]]:vreg_128 = GLOBAL_LOAD_DWORDX4 [[REG_SEQUENCE6]], 96, 0, implicit $exec :: (volatile load (s128) from %ir.p5 + 96, align 32, addrspace 1)
  ; CHECK-NEXT:   [[COPY170:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_33]].sub3
  ; CHECK-NEXT:   [[COPY171:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_33]].sub2
  ; CHECK-NEXT:   [[COPY172:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_33]].sub1
  ; CHECK-NEXT:   [[COPY173:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_33]].sub0
  ; CHECK-NEXT:   [[GLOBAL_LOAD_DWORDX4_34:%[0-9]+]]:vreg_128 = GLOBAL_LOAD_DWORDX4 [[REG_SEQUENCE6]], 80, 0, implicit $exec :: (volatile load (s128) from %ir.p5 + 80, addrspace 1)
  ; CHECK-NEXT:   [[COPY174:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_34]].sub3
  ; CHECK-NEXT:   [[COPY175:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_34]].sub2
  ; CHECK-NEXT:   [[COPY176:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_34]].sub1
  ; CHECK-NEXT:   [[COPY177:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_34]].sub0
  ; CHECK-NEXT:   [[GLOBAL_LOAD_DWORDX4_35:%[0-9]+]]:vreg_128 = GLOBAL_LOAD_DWORDX4 [[REG_SEQUENCE6]], 64, 0, implicit $exec :: (volatile load (s128) from %ir.p5 + 64, align 64, addrspace 1)
  ; CHECK-NEXT:   [[COPY178:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_35]].sub3
  ; CHECK-NEXT:   [[COPY179:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_35]].sub2
  ; CHECK-NEXT:   [[COPY180:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_35]].sub1
  ; CHECK-NEXT:   [[COPY181:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_35]].sub0
  ; CHECK-NEXT:   [[GLOBAL_LOAD_DWORDX4_36:%[0-9]+]]:vreg_128 = GLOBAL_LOAD_DWORDX4 [[REG_SEQUENCE6]], 48, 0, implicit $exec :: (volatile load (s128) from %ir.p5 + 48, addrspace 1)
  ; CHECK-NEXT:   [[COPY182:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_36]].sub3
  ; CHECK-NEXT:   [[COPY183:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_36]].sub2
  ; CHECK-NEXT:   [[COPY184:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_36]].sub1
  ; CHECK-NEXT:   [[COPY185:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_36]].sub0
  ; CHECK-NEXT:   [[GLOBAL_LOAD_DWORDX4_37:%[0-9]+]]:vreg_128 = GLOBAL_LOAD_DWORDX4 [[REG_SEQUENCE6]], 32, 0, implicit $exec :: (volatile load (s128) from %ir.p5 + 32, align 32, addrspace 1)
  ; CHECK-NEXT:   [[COPY186:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_37]].sub3
  ; CHECK-NEXT:   [[COPY187:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_37]].sub2
  ; CHECK-NEXT:   [[COPY188:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_37]].sub1
  ; CHECK-NEXT:   [[COPY189:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_37]].sub0
  ; CHECK-NEXT:   [[GLOBAL_LOAD_DWORDX4_38:%[0-9]+]]:vreg_128 = GLOBAL_LOAD_DWORDX4 [[REG_SEQUENCE6]], 16, 0, implicit $exec :: (volatile load (s128) from %ir.p5 + 16, addrspace 1)
  ; CHECK-NEXT:   [[COPY190:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_38]].sub3
  ; CHECK-NEXT:   [[COPY191:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_38]].sub2
  ; CHECK-NEXT:   [[COPY192:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_38]].sub1
  ; CHECK-NEXT:   [[COPY193:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_38]].sub0
  ; CHECK-NEXT:   [[GLOBAL_LOAD_DWORDX4_39:%[0-9]+]]:vreg_128 = GLOBAL_LOAD_DWORDX4 [[REG_SEQUENCE6]], 0, 0, implicit $exec :: (volatile load (s128) from %ir.p5, align 128, addrspace 1)
  ; CHECK-NEXT:   [[COPY194:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_39]].sub3
  ; CHECK-NEXT:   [[COPY195:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_39]].sub2
  ; CHECK-NEXT:   [[COPY196:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_39]].sub1
  ; CHECK-NEXT:   [[COPY197:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_39]].sub0
  ; CHECK-NEXT:   [[REG_SEQUENCE13:%[0-9]+]]:vreg_1024 = REG_SEQUENCE [[COPY197]], %subreg.sub0, [[COPY196]], %subreg.sub1, [[COPY195]], %subreg.sub2, [[COPY194]], %subreg.sub3, [[COPY193]], %subreg.sub4, [[COPY192]], %subreg.sub5, [[COPY191]], %subreg.sub6, [[COPY190]], %subreg.sub7, [[COPY189]], %subreg.sub8, [[COPY188]], %subreg.sub9, [[COPY187]], %subreg.sub10, [[COPY186]], %subreg.sub11, [[COPY185]], %subreg.sub12, [[COPY184]], %subreg.sub13, [[COPY183]], %subreg.sub14, [[COPY182]], %subreg.sub15, [[COPY181]], %subreg.sub16, [[COPY180]], %subreg.sub17, [[COPY179]], %subreg.sub18, [[COPY178]], %subreg.sub19, [[COPY177]], %subreg.sub20, [[COPY176]], %subreg.sub21, [[COPY175]], %subreg.sub22, [[COPY174]], %subreg.sub23, [[COPY173]], %subreg.sub24, [[COPY172]], %subreg.sub25, [[COPY171]], %subreg.sub26, [[COPY170]], %subreg.sub27, [[COPY169]], %subreg.sub28, [[COPY168]], %subreg.sub29, [[COPY167]], %subreg.sub30, [[COPY166]], %subreg.sub31
  ; CHECK-NEXT:   [[COPY198:%[0-9]+]]:vreg_1024 = COPY [[REG_SEQUENCE13]]
  ; CHECK-NEXT:   SI_SPILL_V32_SAVE [[COPY198]].sub26, %stack.26, $sgpr32, 0, implicit $exec :: (store (s32) into %stack.26, addrspace 5)
  ; CHECK-NEXT:   SI_SPILL_V32_SAVE [[COPY198]].sub25, %stack.25, $sgpr32, 0, implicit $exec :: (store (s32) into %stack.25, addrspace 5)
  ; CHECK-NEXT:   SI_SPILL_V32_SAVE [[COPY198]].sub24, %stack.24, $sgpr32, 0, implicit $exec :: (store (s32) into %stack.24, addrspace 5)
  ; CHECK-NEXT:   SI_SPILL_V32_SAVE [[COPY198]].sub23, %stack.23, $sgpr32, 0, implicit $exec :: (store (s32) into %stack.23, addrspace 5)
  ; CHECK-NEXT:   SI_SPILL_V32_SAVE [[COPY198]].sub22, %stack.22, $sgpr32, 0, implicit $exec :: (store (s32) into %stack.22, addrspace 5)
  ; CHECK-NEXT:   SI_SPILL_V32_SAVE [[COPY198]].sub21, %stack.21, $sgpr32, 0, implicit $exec :: (store (s32) into %stack.21, addrspace 5)
  ; CHECK-NEXT:   SI_SPILL_V32_SAVE [[COPY198]].sub20, %stack.20, $sgpr32, 0, implicit $exec :: (store (s32) into %stack.20, addrspace 5)
  ; CHECK-NEXT:   SI_SPILL_V32_SAVE [[COPY198]].sub19, %stack.19, $sgpr32, 0, implicit $exec :: (store (s32) into %stack.19, addrspace 5)
  ; CHECK-NEXT:   SI_SPILL_V32_SAVE [[COPY198]].sub18, %stack.18, $sgpr32, 0, implicit $exec :: (store (s32) into %stack.18, addrspace 5)
  ; CHECK-NEXT:   SI_SPILL_V32_SAVE [[COPY198]].sub17, %stack.17, $sgpr32, 0, implicit $exec :: (store (s32) into %stack.17, addrspace 5)
  ; CHECK-NEXT:   SI_SPILL_V32_SAVE [[COPY198]].sub16, %stack.16, $sgpr32, 0, implicit $exec :: (store (s32) into %stack.16, addrspace 5)
  ; CHECK-NEXT:   SI_SPILL_V32_SAVE [[COPY198]].sub15, %stack.15, $sgpr32, 0, implicit $exec :: (store (s32) into %stack.15, addrspace 5)
  ; CHECK-NEXT:   SI_SPILL_V32_SAVE [[COPY198]].sub14, %stack.14, $sgpr32, 0, implicit $exec :: (store (s32) into %stack.14, addrspace 5)
  ; CHECK-NEXT:   SI_SPILL_V32_SAVE [[COPY198]].sub13, %stack.13, $sgpr32, 0, implicit $exec :: (store (s32) into %stack.13, addrspace 5)
  ; CHECK-NEXT:   SI_SPILL_V32_SAVE [[COPY198]].sub12, %stack.12, $sgpr32, 0, implicit $exec :: (store (s32) into %stack.12, addrspace 5)
  ; CHECK-NEXT:   SI_SPILL_V32_SAVE [[COPY198]].sub11, %stack.11, $sgpr32, 0, implicit $exec :: (store (s32) into %stack.11, addrspace 5)
  ; CHECK-NEXT:   SI_SPILL_V32_SAVE [[COPY198]].sub10, %stack.10, $sgpr32, 0, implicit $exec :: (store (s32) into %stack.10, addrspace 5)
  ; CHECK-NEXT:   SI_SPILL_V32_SAVE [[COPY198]].sub9, %stack.9, $sgpr32, 0, implicit $exec :: (store (s32) into %stack.9, addrspace 5)
  ; CHECK-NEXT:   SI_SPILL_V32_SAVE [[COPY198]].sub8, %stack.8, $sgpr32, 0, implicit $exec :: (store (s32) into %stack.8, addrspace 5)
  ; CHECK-NEXT:   SI_SPILL_V32_SAVE [[COPY198]].sub7, %stack.7, $sgpr32, 0, implicit $exec :: (store (s32) into %stack.7, addrspace 5)
  ; CHECK-NEXT:   SI_SPILL_V32_SAVE [[COPY198]].sub6, %stack.6, $sgpr32, 0, implicit $exec :: (store (s32) into %stack.6, addrspace 5)
  ; CHECK-NEXT:   SI_SPILL_V32_SAVE [[COPY198]].sub5, %stack.5, $sgpr32, 0, implicit $exec :: (store (s32) into %stack.5, addrspace 5)
  ; CHECK-NEXT:   SI_SPILL_V32_SAVE [[COPY198]].sub4, %stack.4, $sgpr32, 0, implicit $exec :: (store (s32) into %stack.4, addrspace 5)
  ; CHECK-NEXT:   SI_SPILL_V32_SAVE [[COPY198]].sub3, %stack.3, $sgpr32, 0, implicit $exec :: (store (s32) into %stack.3, addrspace 5)
  ; CHECK-NEXT:   SI_SPILL_V32_SAVE [[COPY198]].sub2, %stack.2, $sgpr32, 0, implicit $exec :: (store (s32) into %stack.2, addrspace 5)
  ; CHECK-NEXT:   SI_SPILL_V32_SAVE [[COPY198]].sub1, %stack.1, $sgpr32, 0, implicit $exec :: (store (s32) into %stack.1, addrspace 5)
  ; CHECK-NEXT:   SI_SPILL_V32_SAVE [[COPY198]].sub0, %stack.0, $sgpr32, 0, implicit $exec :: (store (s32) into %stack.0, addrspace 5)
  ; CHECK-NEXT:   [[GLOBAL_LOAD_DWORDX4_40:%[0-9]+]]:vreg_128 = GLOBAL_LOAD_DWORDX4 [[REG_SEQUENCE7]], 112, 0, implicit $exec :: (volatile load (s128) from %ir.p6 + 112, addrspace 1)
  ; CHECK-NEXT:   [[COPY199:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_40]].sub3
  ; CHECK-NEXT:   [[COPY200:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_40]].sub2
  ; CHECK-NEXT:   [[COPY201:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_40]].sub1
  ; CHECK-NEXT:   [[COPY202:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_40]].sub0
  ; CHECK-NEXT:   SI_VIRTUAL_SPILL_MARKER [[COPY198]], 000000000000000C
  ; CHECK-NEXT:   SI_VIRTUAL_SPILL_MARKER [[COPY198]], 0000000000000030
  ; CHECK-NEXT:   SI_VIRTUAL_SPILL_MARKER [[COPY198]], 00000000000000C0
  ; CHECK-NEXT:   SI_VIRTUAL_SPILL_MARKER [[COPY198]], 0000000000000300
  ; CHECK-NEXT:   [[GLOBAL_LOAD_DWORDX4_41:%[0-9]+]]:vreg_128 = GLOBAL_LOAD_DWORDX4 [[REG_SEQUENCE7]], 96, 0, implicit $exec :: (volatile load (s128) from %ir.p6 + 96, align 32, addrspace 1)
  ; CHECK-NEXT:   [[COPY203:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_41]].sub3
  ; CHECK-NEXT:   [[COPY204:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_41]].sub2
  ; CHECK-NEXT:   [[COPY205:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_41]].sub1
  ; CHECK-NEXT:   [[COPY206:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_41]].sub0
  ; CHECK-NEXT:   SI_VIRTUAL_SPILL_MARKER [[COPY198]], 0000000000000C00
  ; CHECK-NEXT:   SI_VIRTUAL_SPILL_MARKER [[COPY198]], 0000000000003000
  ; CHECK-NEXT:   SI_VIRTUAL_SPILL_MARKER [[COPY198]], 000000000000C000
  ; CHECK-NEXT:   SI_VIRTUAL_SPILL_MARKER [[COPY198]], 0000000000030000
  ; CHECK-NEXT:   [[GLOBAL_LOAD_DWORDX4_42:%[0-9]+]]:vreg_128 = GLOBAL_LOAD_DWORDX4 [[REG_SEQUENCE7]], 80, 0, implicit $exec :: (volatile load (s128) from %ir.p6 + 80, addrspace 1)
  ; CHECK-NEXT:   [[COPY207:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_42]].sub3
  ; CHECK-NEXT:   [[COPY208:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_42]].sub2
  ; CHECK-NEXT:   [[COPY209:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_42]].sub1
  ; CHECK-NEXT:   [[COPY210:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_42]].sub0
  ; CHECK-NEXT:   SI_VIRTUAL_SPILL_MARKER [[COPY198]], 00000000000C0000
  ; CHECK-NEXT:   SI_VIRTUAL_SPILL_MARKER [[COPY198]], 0000000000300000
  ; CHECK-NEXT:   SI_VIRTUAL_SPILL_MARKER [[COPY198]], 0000000000C00000
  ; CHECK-NEXT:   SI_VIRTUAL_SPILL_MARKER [[COPY198]], 0000000003000000
  ; CHECK-NEXT:   [[GLOBAL_LOAD_DWORDX4_43:%[0-9]+]]:vreg_128 = GLOBAL_LOAD_DWORDX4 [[REG_SEQUENCE7]], 64, 0, implicit $exec :: (volatile load (s128) from %ir.p6 + 64, align 64, addrspace 1)
  ; CHECK-NEXT:   [[COPY211:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_43]].sub3
  ; CHECK-NEXT:   [[COPY212:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_43]].sub2
  ; CHECK-NEXT:   [[COPY213:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_43]].sub1
  ; CHECK-NEXT:   [[COPY214:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_43]].sub0
  ; CHECK-NEXT:   SI_VIRTUAL_SPILL_MARKER [[COPY198]], 000000000C000000
  ; CHECK-NEXT:   SI_VIRTUAL_SPILL_MARKER [[COPY198]], 0000000030000000
  ; CHECK-NEXT:   SI_VIRTUAL_SPILL_MARKER [[COPY198]], 00000000C0000000
  ; CHECK-NEXT:   SI_VIRTUAL_SPILL_MARKER [[COPY198]], 0000000300000000
  ; CHECK-NEXT:   [[GLOBAL_LOAD_DWORDX4_44:%[0-9]+]]:vreg_128 = GLOBAL_LOAD_DWORDX4 [[REG_SEQUENCE7]], 48, 0, implicit $exec :: (volatile load (s128) from %ir.p6 + 48, addrspace 1)
  ; CHECK-NEXT:   [[COPY215:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_44]].sub3
  ; CHECK-NEXT:   [[COPY216:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_44]].sub2
  ; CHECK-NEXT:   [[COPY217:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_44]].sub1
  ; CHECK-NEXT:   [[COPY218:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_44]].sub0
  ; CHECK-NEXT:   SI_VIRTUAL_SPILL_MARKER [[COPY198]], 0000000C00000000
  ; CHECK-NEXT:   SI_VIRTUAL_SPILL_MARKER [[COPY198]], 0000003000000000
  ; CHECK-NEXT:   SI_VIRTUAL_SPILL_MARKER [[COPY198]], 000000C000000000
  ; CHECK-NEXT:   SI_VIRTUAL_SPILL_MARKER [[COPY198]], 0000030000000000
  ; CHECK-NEXT:   [[GLOBAL_LOAD_DWORDX4_45:%[0-9]+]]:vreg_128 = GLOBAL_LOAD_DWORDX4 [[REG_SEQUENCE7]], 32, 0, implicit $exec :: (volatile load (s128) from %ir.p6 + 32, align 32, addrspace 1)
  ; CHECK-NEXT:   [[COPY219:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_45]].sub3
  ; CHECK-NEXT:   [[COPY220:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_45]].sub2
  ; CHECK-NEXT:   [[COPY221:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_45]].sub1
  ; CHECK-NEXT:   [[COPY222:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_45]].sub0
  ; CHECK-NEXT:   SI_VIRTUAL_SPILL_MARKER [[COPY198]], 00000C0000000000
  ; CHECK-NEXT:   SI_VIRTUAL_SPILL_MARKER [[COPY198]], 0000300000000000
  ; CHECK-NEXT:   SI_VIRTUAL_SPILL_MARKER [[COPY198]], 0000C00000000000
  ; CHECK-NEXT:   SI_VIRTUAL_SPILL_MARKER [[COPY198]], 0003000000000000
  ; CHECK-NEXT:   [[GLOBAL_LOAD_DWORDX4_46:%[0-9]+]]:vreg_128 = GLOBAL_LOAD_DWORDX4 [[REG_SEQUENCE7]], 16, 0, implicit $exec :: (volatile load (s128) from %ir.p6 + 16, addrspace 1)
  ; CHECK-NEXT:   [[COPY223:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_46]].sub3
  ; CHECK-NEXT:   [[COPY224:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_46]].sub2
  ; CHECK-NEXT:   [[COPY225:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_46]].sub1
  ; CHECK-NEXT:   [[COPY226:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_46]].sub0
  ; CHECK-NEXT:   SI_VIRTUAL_SPILL_MARKER [[COPY198]], 000C000000000000
  ; CHECK-NEXT:   SI_VIRTUAL_SPILL_MARKER [[COPY198]], 0030000000000000
  ; CHECK-NEXT:   [[GLOBAL_LOAD_DWORDX4_47:%[0-9]+]]:vreg_128 = GLOBAL_LOAD_DWORDX4 [[REG_SEQUENCE7]], 0, 0, implicit $exec :: (volatile load (s128) from %ir.p6, align 128, addrspace 1)
  ; CHECK-NEXT:   [[COPY227:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_47]].sub3
  ; CHECK-NEXT:   [[COPY228:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_47]].sub2
  ; CHECK-NEXT:   [[COPY229:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_47]].sub1
  ; CHECK-NEXT:   [[COPY230:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_47]].sub0
  ; CHECK-NEXT:   [[REG_SEQUENCE14:%[0-9]+]]:vreg_1024 = REG_SEQUENCE [[COPY230]], %subreg.sub0, [[COPY229]], %subreg.sub1, [[COPY228]], %subreg.sub2, [[COPY227]], %subreg.sub3, [[COPY226]], %subreg.sub4, [[COPY225]], %subreg.sub5, [[COPY224]], %subreg.sub6, [[COPY223]], %subreg.sub7, [[COPY222]], %subreg.sub8, [[COPY221]], %subreg.sub9, [[COPY220]], %subreg.sub10, [[COPY219]], %subreg.sub11, [[COPY218]], %subreg.sub12, [[COPY217]], %subreg.sub13, [[COPY216]], %subreg.sub14, [[COPY215]], %subreg.sub15, [[COPY214]], %subreg.sub16, [[COPY213]], %subreg.sub17, [[COPY212]], %subreg.sub18, [[COPY211]], %subreg.sub19, [[COPY210]], %subreg.sub20, [[COPY209]], %subreg.sub21, [[COPY208]], %subreg.sub22, [[COPY207]], %subreg.sub23, [[COPY206]], %subreg.sub24, [[COPY205]], %subreg.sub25, [[COPY204]], %subreg.sub26, [[COPY203]], %subreg.sub27, [[COPY202]], %subreg.sub28, [[COPY201]], %subreg.sub29, [[COPY200]], %subreg.sub30, [[COPY199]], %subreg.sub31
  ; CHECK-NEXT:   [[COPY231:%[0-9]+]]:vreg_1024 = COPY [[REG_SEQUENCE14]]
  ; CHECK-NEXT:   SI_SPILL_V32_SAVE [[COPY231]].sub29, %stack.56, $sgpr32, 0, implicit $exec :: (store (s32) into %stack.56, addrspace 5)
  ; CHECK-NEXT:   SI_SPILL_V32_SAVE [[COPY231]].sub28, %stack.55, $sgpr32, 0, implicit $exec :: (store (s32) into %stack.55, addrspace 5)
  ; CHECK-NEXT:   SI_SPILL_V32_SAVE [[COPY231]].sub27, %stack.54, $sgpr32, 0, implicit $exec :: (store (s32) into %stack.54, addrspace 5)
  ; CHECK-NEXT:   SI_SPILL_V32_SAVE [[COPY231]].sub26, %stack.53, $sgpr32, 0, implicit $exec :: (store (s32) into %stack.53, addrspace 5)
  ; CHECK-NEXT:   SI_SPILL_V32_SAVE [[COPY231]].sub25, %stack.52, $sgpr32, 0, implicit $exec :: (store (s32) into %stack.52, addrspace 5)
  ; CHECK-NEXT:   SI_SPILL_V32_SAVE [[COPY231]].sub24, %stack.51, $sgpr32, 0, implicit $exec :: (store (s32) into %stack.51, addrspace 5)
  ; CHECK-NEXT:   SI_SPILL_V32_SAVE [[COPY231]].sub23, %stack.50, $sgpr32, 0, implicit $exec :: (store (s32) into %stack.50, addrspace 5)
  ; CHECK-NEXT:   SI_SPILL_V32_SAVE [[COPY231]].sub22, %stack.49, $sgpr32, 0, implicit $exec :: (store (s32) into %stack.49, addrspace 5)
  ; CHECK-NEXT:   SI_SPILL_V32_SAVE [[COPY231]].sub21, %stack.48, $sgpr32, 0, implicit $exec :: (store (s32) into %stack.48, addrspace 5)
  ; CHECK-NEXT:   SI_SPILL_V32_SAVE [[COPY231]].sub20, %stack.47, $sgpr32, 0, implicit $exec :: (store (s32) into %stack.47, addrspace 5)
  ; CHECK-NEXT:   SI_SPILL_V32_SAVE [[COPY231]].sub19, %stack.46, $sgpr32, 0, implicit $exec :: (store (s32) into %stack.46, addrspace 5)
  ; CHECK-NEXT:   SI_SPILL_V32_SAVE [[COPY231]].sub18, %stack.45, $sgpr32, 0, implicit $exec :: (store (s32) into %stack.45, addrspace 5)
  ; CHECK-NEXT:   SI_SPILL_V32_SAVE [[COPY231]].sub17, %stack.44, $sgpr32, 0, implicit $exec :: (store (s32) into %stack.44, addrspace 5)
  ; CHECK-NEXT:   SI_SPILL_V32_SAVE [[COPY231]].sub16, %stack.43, $sgpr32, 0, implicit $exec :: (store (s32) into %stack.43, addrspace 5)
  ; CHECK-NEXT:   SI_SPILL_V32_SAVE [[COPY231]].sub15, %stack.42, $sgpr32, 0, implicit $exec :: (store (s32) into %stack.42, addrspace 5)
  ; CHECK-NEXT:   SI_SPILL_V32_SAVE [[COPY231]].sub14, %stack.41, $sgpr32, 0, implicit $exec :: (store (s32) into %stack.41, addrspace 5)
  ; CHECK-NEXT:   SI_SPILL_V32_SAVE [[COPY231]].sub13, %stack.40, $sgpr32, 0, implicit $exec :: (store (s32) into %stack.40, addrspace 5)
  ; CHECK-NEXT:   SI_SPILL_V32_SAVE [[COPY231]].sub12, %stack.39, $sgpr32, 0, implicit $exec :: (store (s32) into %stack.39, addrspace 5)
  ; CHECK-NEXT:   SI_SPILL_V32_SAVE [[COPY231]].sub11, %stack.38, $sgpr32, 0, implicit $exec :: (store (s32) into %stack.38, addrspace 5)
  ; CHECK-NEXT:   SI_SPILL_V32_SAVE [[COPY231]].sub10, %stack.37, $sgpr32, 0, implicit $exec :: (store (s32) into %stack.37, addrspace 5)
  ; CHECK-NEXT:   SI_SPILL_V32_SAVE [[COPY231]].sub9, %stack.36, $sgpr32, 0, implicit $exec :: (store (s32) into %stack.36, addrspace 5)
  ; CHECK-NEXT:   SI_SPILL_V32_SAVE [[COPY231]].sub8, %stack.35, $sgpr32, 0, implicit $exec :: (store (s32) into %stack.35, addrspace 5)
  ; CHECK-NEXT:   SI_SPILL_V32_SAVE [[COPY231]].sub7, %stack.34, $sgpr32, 0, implicit $exec :: (store (s32) into %stack.34, addrspace 5)
  ; CHECK-NEXT:   SI_SPILL_V32_SAVE [[COPY231]].sub6, %stack.33, $sgpr32, 0, implicit $exec :: (store (s32) into %stack.33, addrspace 5)
  ; CHECK-NEXT:   SI_SPILL_V32_SAVE [[COPY231]].sub5, %stack.32, $sgpr32, 0, implicit $exec :: (store (s32) into %stack.32, addrspace 5)
  ; CHECK-NEXT:   SI_SPILL_V32_SAVE [[COPY231]].sub4, %stack.31, $sgpr32, 0, implicit $exec :: (store (s32) into %stack.31, addrspace 5)
  ; CHECK-NEXT:   SI_SPILL_V32_SAVE [[COPY231]].sub3, %stack.30, $sgpr32, 0, implicit $exec :: (store (s32) into %stack.30, addrspace 5)
  ; CHECK-NEXT:   SI_SPILL_V32_SAVE [[COPY231]].sub2, %stack.29, $sgpr32, 0, implicit $exec :: (store (s32) into %stack.29, addrspace 5)
  ; CHECK-NEXT:   SI_SPILL_V32_SAVE [[COPY231]].sub1, %stack.28, $sgpr32, 0, implicit $exec :: (store (s32) into %stack.28, addrspace 5)
  ; CHECK-NEXT:   SI_SPILL_V32_SAVE [[COPY231]].sub0, %stack.27, $sgpr32, 0, implicit $exec :: (store (s32) into %stack.27, addrspace 5)
  ; CHECK-NEXT:   SI_VIRTUAL_SPILL_MARKER [[COPY231]], 000000000000000C
  ; CHECK-NEXT:   SI_VIRTUAL_SPILL_MARKER [[COPY231]], 0000000000000030
  ; CHECK-NEXT:   SI_VIRTUAL_SPILL_MARKER [[COPY231]], 00000000000000C0
  ; CHECK-NEXT:   [[GLOBAL_LOAD_DWORDX4_48:%[0-9]+]]:vreg_128 = GLOBAL_LOAD_DWORDX4 [[REG_SEQUENCE8]], 112, 0, implicit $exec :: (volatile load (s128) from %ir.p7 + 112, addrspace 1)
  ; CHECK-NEXT:   [[COPY232:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_48]].sub3
  ; CHECK-NEXT:   [[COPY233:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_48]].sub2
  ; CHECK-NEXT:   [[COPY234:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_48]].sub1
  ; CHECK-NEXT:   [[COPY235:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_48]].sub0
  ; CHECK-NEXT:   SI_VIRTUAL_SPILL_MARKER [[COPY231]], 0000000000000300
  ; CHECK-NEXT:   SI_VIRTUAL_SPILL_MARKER [[COPY231]], 0000000000000C00
  ; CHECK-NEXT:   SI_VIRTUAL_SPILL_MARKER [[COPY231]], 0000000000003000
  ; CHECK-NEXT:   SI_VIRTUAL_SPILL_MARKER [[COPY231]], 000000000000C000
  ; CHECK-NEXT:   [[GLOBAL_LOAD_DWORDX4_49:%[0-9]+]]:vreg_128 = GLOBAL_LOAD_DWORDX4 [[REG_SEQUENCE8]], 96, 0, implicit $exec :: (volatile load (s128) from %ir.p7 + 96, align 32, addrspace 1)
  ; CHECK-NEXT:   [[COPY236:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_49]].sub3
  ; CHECK-NEXT:   [[COPY237:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_49]].sub2
  ; CHECK-NEXT:   [[COPY238:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_49]].sub1
  ; CHECK-NEXT:   [[COPY239:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_49]].sub0
  ; CHECK-NEXT:   SI_VIRTUAL_SPILL_MARKER [[COPY231]], 0000000000030000
  ; CHECK-NEXT:   SI_VIRTUAL_SPILL_MARKER [[COPY231]], 00000000000C0000
  ; CHECK-NEXT:   SI_VIRTUAL_SPILL_MARKER [[COPY231]], 0000000000300000
  ; CHECK-NEXT:   SI_VIRTUAL_SPILL_MARKER [[COPY231]], 0000000000C00000
  ; CHECK-NEXT:   [[GLOBAL_LOAD_DWORDX4_50:%[0-9]+]]:vreg_128 = GLOBAL_LOAD_DWORDX4 [[REG_SEQUENCE8]], 80, 0, implicit $exec :: (volatile load (s128) from %ir.p7 + 80, addrspace 1)
  ; CHECK-NEXT:   [[COPY240:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_50]].sub3
  ; CHECK-NEXT:   [[COPY241:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_50]].sub2
  ; CHECK-NEXT:   [[COPY242:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_50]].sub1
  ; CHECK-NEXT:   [[COPY243:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_50]].sub0
  ; CHECK-NEXT:   SI_VIRTUAL_SPILL_MARKER [[COPY231]], 0000000003000000
  ; CHECK-NEXT:   SI_VIRTUAL_SPILL_MARKER [[COPY231]], 000000000C000000
  ; CHECK-NEXT:   SI_VIRTUAL_SPILL_MARKER [[COPY231]], 0000000030000000
  ; CHECK-NEXT:   SI_VIRTUAL_SPILL_MARKER [[COPY231]], 00000000C0000000
  ; CHECK-NEXT:   [[GLOBAL_LOAD_DWORDX4_51:%[0-9]+]]:vreg_128 = GLOBAL_LOAD_DWORDX4 [[REG_SEQUENCE8]], 64, 0, implicit $exec :: (volatile load (s128) from %ir.p7 + 64, align 64, addrspace 1)
  ; CHECK-NEXT:   [[COPY244:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_51]].sub3
  ; CHECK-NEXT:   [[COPY245:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_51]].sub2
  ; CHECK-NEXT:   [[COPY246:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_51]].sub1
  ; CHECK-NEXT:   [[COPY247:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_51]].sub0
  ; CHECK-NEXT:   SI_VIRTUAL_SPILL_MARKER [[COPY231]], 0000000300000000
  ; CHECK-NEXT:   SI_VIRTUAL_SPILL_MARKER [[COPY231]], 0000000C00000000
  ; CHECK-NEXT:   SI_VIRTUAL_SPILL_MARKER [[COPY231]], 0000003000000000
  ; CHECK-NEXT:   SI_VIRTUAL_SPILL_MARKER [[COPY231]], 000000C000000000
  ; CHECK-NEXT:   [[GLOBAL_LOAD_DWORDX4_52:%[0-9]+]]:vreg_128 = GLOBAL_LOAD_DWORDX4 [[REG_SEQUENCE8]], 48, 0, implicit $exec :: (volatile load (s128) from %ir.p7 + 48, addrspace 1)
  ; CHECK-NEXT:   [[COPY248:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_52]].sub3
  ; CHECK-NEXT:   [[COPY249:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_52]].sub2
  ; CHECK-NEXT:   [[COPY250:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_52]].sub1
  ; CHECK-NEXT:   [[COPY251:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_52]].sub0
  ; CHECK-NEXT:   SI_VIRTUAL_SPILL_MARKER [[COPY231]], 0000030000000000
  ; CHECK-NEXT:   SI_VIRTUAL_SPILL_MARKER [[COPY231]], 00000C0000000000
  ; CHECK-NEXT:   SI_VIRTUAL_SPILL_MARKER [[COPY231]], 0000300000000000
  ; CHECK-NEXT:   SI_VIRTUAL_SPILL_MARKER [[COPY231]], 0000C00000000000
  ; CHECK-NEXT:   [[GLOBAL_LOAD_DWORDX4_53:%[0-9]+]]:vreg_128 = GLOBAL_LOAD_DWORDX4 [[REG_SEQUENCE8]], 32, 0, implicit $exec :: (volatile load (s128) from %ir.p7 + 32, align 32, addrspace 1)
  ; CHECK-NEXT:   [[COPY252:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_53]].sub3
  ; CHECK-NEXT:   [[COPY253:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_53]].sub2
  ; CHECK-NEXT:   [[COPY254:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_53]].sub1
  ; CHECK-NEXT:   [[COPY255:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_53]].sub0
  ; CHECK-NEXT:   SI_VIRTUAL_SPILL_MARKER [[COPY231]], 0003000000000000
  ; CHECK-NEXT:   SI_VIRTUAL_SPILL_MARKER [[COPY231]], 000C000000000000
  ; CHECK-NEXT:   SI_VIRTUAL_SPILL_MARKER [[COPY231]], 0030000000000000
  ; CHECK-NEXT:   SI_VIRTUAL_SPILL_MARKER [[COPY231]], 00C0000000000000
  ; CHECK-NEXT:   [[GLOBAL_LOAD_DWORDX4_54:%[0-9]+]]:vreg_128 = GLOBAL_LOAD_DWORDX4 [[REG_SEQUENCE8]], 16, 0, implicit $exec :: (volatile load (s128) from %ir.p7 + 16, addrspace 1)
  ; CHECK-NEXT:   [[COPY256:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_54]].sub3
  ; CHECK-NEXT:   [[COPY257:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_54]].sub2
  ; CHECK-NEXT:   [[COPY258:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_54]].sub1
  ; CHECK-NEXT:   [[COPY259:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_54]].sub0
  ; CHECK-NEXT:   SI_VIRTUAL_SPILL_MARKER [[COPY231]], 0300000000000000
  ; CHECK-NEXT:   SI_VIRTUAL_SPILL_MARKER [[COPY231]], 0C00000000000000
  ; CHECK-NEXT:   [[GLOBAL_LOAD_DWORDX4_55:%[0-9]+]]:vreg_128 = GLOBAL_LOAD_DWORDX4 [[REG_SEQUENCE8]], 0, 0, implicit $exec :: (volatile load (s128) from %ir.p7, align 128, addrspace 1)
  ; CHECK-NEXT:   [[COPY260:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_55]].sub3
  ; CHECK-NEXT:   [[COPY261:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_55]].sub2
  ; CHECK-NEXT:   [[COPY262:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_55]].sub1
  ; CHECK-NEXT:   [[COPY263:%[0-9]+]]:vgpr_32 = COPY [[GLOBAL_LOAD_DWORDX4_55]].sub0
  ; CHECK-NEXT:   [[REG_SEQUENCE15:%[0-9]+]]:vreg_1024 = REG_SEQUENCE [[COPY263]], %subreg.sub0, [[COPY262]], %subreg.sub1, [[COPY261]], %subreg.sub2, [[COPY260]], %subreg.sub3, [[COPY259]], %subreg.sub4, [[COPY258]], %subreg.sub5, [[COPY257]], %subreg.sub6, [[COPY256]], %subreg.sub7, [[COPY255]], %subreg.sub8, [[COPY254]], %subreg.sub9, [[COPY253]], %subreg.sub10, [[COPY252]], %subreg.sub11, [[COPY251]], %subreg.sub12, [[COPY250]], %subreg.sub13, [[COPY249]], %subreg.sub14, [[COPY248]], %subreg.sub15, [[COPY247]], %subreg.sub16, [[COPY246]], %subreg.sub17, [[COPY245]], %subreg.sub18, [[COPY244]], %subreg.sub19, [[COPY243]], %subreg.sub20, [[COPY242]], %subreg.sub21, [[COPY241]], %subreg.sub22, [[COPY240]], %subreg.sub23, [[COPY239]], %subreg.sub24, [[COPY238]], %subreg.sub25, [[COPY237]], %subreg.sub26, [[COPY236]], %subreg.sub27, [[COPY235]], %subreg.sub28, [[COPY234]], %subreg.sub29, [[COPY233]], %subreg.sub30, [[COPY232]], %subreg.sub31
  ; CHECK-NEXT:   [[COPY264:%[0-9]+]]:vreg_1024 = COPY [[REG_SEQUENCE15]]
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1.st:
  ; CHECK-NEXT:   [[COPY265:%[0-9]+]]:vgpr_32 = COPY [[COPY33]].sub31
  ; CHECK-NEXT:   [[COPY266:%[0-9]+]]:vgpr_32 = COPY [[COPY33]].sub30
  ; CHECK-NEXT:   [[COPY267:%[0-9]+]]:vgpr_32 = COPY [[COPY33]].sub29
  ; CHECK-NEXT:   [[COPY268:%[0-9]+]]:vgpr_32 = COPY [[COPY33]].sub28
  ; CHECK-NEXT:   [[REG_SEQUENCE16:%[0-9]+]]:vreg_128 = REG_SEQUENCE [[COPY268]], %subreg.sub0, [[COPY267]], %subreg.sub1, [[COPY266]], %subreg.sub2, [[COPY265]], %subreg.sub3
  ; CHECK-NEXT:   GLOBAL_STORE_DWORDX4 undef %392:vreg_64, [[REG_SEQUENCE16]], 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 112, addrspace 1)
  ; CHECK-NEXT:   [[COPY269:%[0-9]+]]:vgpr_32 = COPY [[COPY33]].sub27
  ; CHECK-NEXT:   [[COPY270:%[0-9]+]]:vgpr_32 = COPY [[COPY33]].sub26
  ; CHECK-NEXT:   [[COPY271:%[0-9]+]]:vgpr_32 = COPY [[COPY33]].sub25
  ; CHECK-NEXT:   [[COPY272:%[0-9]+]]:vgpr_32 = COPY [[COPY33]].sub24
  ; CHECK-NEXT:   [[REG_SEQUENCE17:%[0-9]+]]:vreg_128 = REG_SEQUENCE [[COPY272]], %subreg.sub0, [[COPY271]], %subreg.sub1, [[COPY270]], %subreg.sub2, [[COPY269]], %subreg.sub3
  ; CHECK-NEXT:   GLOBAL_STORE_DWORDX4 undef %400:vreg_64, [[REG_SEQUENCE17]], 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 96, align 32, addrspace 1)
  ; CHECK-NEXT:   [[COPY273:%[0-9]+]]:vgpr_32 = COPY [[COPY33]].sub23
  ; CHECK-NEXT:   [[COPY274:%[0-9]+]]:vgpr_32 = COPY [[COPY33]].sub22
  ; CHECK-NEXT:   [[COPY275:%[0-9]+]]:vgpr_32 = COPY [[COPY33]].sub21
  ; CHECK-NEXT:   [[COPY276:%[0-9]+]]:vgpr_32 = COPY [[COPY33]].sub20
  ; CHECK-NEXT:   [[REG_SEQUENCE18:%[0-9]+]]:vreg_128 = REG_SEQUENCE [[COPY276]], %subreg.sub0, [[COPY275]], %subreg.sub1, [[COPY274]], %subreg.sub2, [[COPY273]], %subreg.sub3
  ; CHECK-NEXT:   GLOBAL_STORE_DWORDX4 undef %408:vreg_64, [[REG_SEQUENCE18]], 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 80, addrspace 1)
  ; CHECK-NEXT:   [[COPY277:%[0-9]+]]:vgpr_32 = COPY [[COPY33]].sub19
  ; CHECK-NEXT:   [[COPY278:%[0-9]+]]:vgpr_32 = COPY [[COPY33]].sub18
  ; CHECK-NEXT:   [[COPY279:%[0-9]+]]:vgpr_32 = COPY [[COPY33]].sub17
  ; CHECK-NEXT:   [[COPY280:%[0-9]+]]:vgpr_32 = COPY [[COPY33]].sub16
  ; CHECK-NEXT:   [[REG_SEQUENCE19:%[0-9]+]]:vreg_128 = REG_SEQUENCE [[COPY280]], %subreg.sub0, [[COPY279]], %subreg.sub1, [[COPY278]], %subreg.sub2, [[COPY277]], %subreg.sub3
  ; CHECK-NEXT:   GLOBAL_STORE_DWORDX4 undef %416:vreg_64, [[REG_SEQUENCE19]], 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 64, align 64, addrspace 1)
  ; CHECK-NEXT:   [[COPY281:%[0-9]+]]:vgpr_32 = COPY [[COPY33]].sub15
  ; CHECK-NEXT:   [[COPY282:%[0-9]+]]:vgpr_32 = COPY [[COPY33]].sub14
  ; CHECK-NEXT:   [[COPY283:%[0-9]+]]:vgpr_32 = COPY [[COPY33]].sub13
  ; CHECK-NEXT:   [[COPY284:%[0-9]+]]:vgpr_32 = COPY [[COPY33]].sub12
  ; CHECK-NEXT:   [[REG_SEQUENCE20:%[0-9]+]]:vreg_128 = REG_SEQUENCE [[COPY284]], %subreg.sub0, [[COPY283]], %subreg.sub1, [[COPY282]], %subreg.sub2, [[COPY281]], %subreg.sub3
  ; CHECK-NEXT:   GLOBAL_STORE_DWORDX4 undef %424:vreg_64, [[REG_SEQUENCE20]], 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 48, addrspace 1)
  ; CHECK-NEXT:   [[COPY285:%[0-9]+]]:vgpr_32 = COPY [[COPY33]].sub11
  ; CHECK-NEXT:   [[COPY286:%[0-9]+]]:vgpr_32 = COPY [[COPY33]].sub10
  ; CHECK-NEXT:   [[COPY287:%[0-9]+]]:vgpr_32 = COPY [[COPY33]].sub9
  ; CHECK-NEXT:   [[COPY288:%[0-9]+]]:vgpr_32 = COPY [[COPY33]].sub8
  ; CHECK-NEXT:   [[REG_SEQUENCE21:%[0-9]+]]:vreg_128 = REG_SEQUENCE [[COPY288]], %subreg.sub0, [[COPY287]], %subreg.sub1, [[COPY286]], %subreg.sub2, [[COPY285]], %subreg.sub3
  ; CHECK-NEXT:   GLOBAL_STORE_DWORDX4 undef %432:vreg_64, [[REG_SEQUENCE21]], 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 32, align 32, addrspace 1)
  ; CHECK-NEXT:   [[COPY289:%[0-9]+]]:vgpr_32 = COPY [[COPY33]].sub7
  ; CHECK-NEXT:   [[COPY290:%[0-9]+]]:vgpr_32 = COPY [[COPY33]].sub6
  ; CHECK-NEXT:   [[COPY291:%[0-9]+]]:vgpr_32 = COPY [[COPY33]].sub5
  ; CHECK-NEXT:   [[COPY292:%[0-9]+]]:vgpr_32 = COPY [[COPY33]].sub4
  ; CHECK-NEXT:   [[REG_SEQUENCE22:%[0-9]+]]:vreg_128 = REG_SEQUENCE [[COPY292]], %subreg.sub0, [[COPY291]], %subreg.sub1, [[COPY290]], %subreg.sub2, [[COPY289]], %subreg.sub3
  ; CHECK-NEXT:   GLOBAL_STORE_DWORDX4 undef %440:vreg_64, [[REG_SEQUENCE22]], 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 16, addrspace 1)
  ; CHECK-NEXT:   [[COPY293:%[0-9]+]]:vgpr_32 = COPY [[COPY33]].sub3
  ; CHECK-NEXT:   [[COPY294:%[0-9]+]]:vgpr_32 = COPY [[COPY33]].sub2
  ; CHECK-NEXT:   [[COPY295:%[0-9]+]]:vgpr_32 = COPY [[COPY33]].sub1
  ; CHECK-NEXT:   [[COPY296:%[0-9]+]]:vgpr_32 = COPY [[COPY33]].sub0
  ; CHECK-NEXT:   [[REG_SEQUENCE23:%[0-9]+]]:vreg_128 = REG_SEQUENCE [[COPY296]], %subreg.sub0, [[COPY295]], %subreg.sub1, [[COPY294]], %subreg.sub2, [[COPY293]], %subreg.sub3
  ; CHECK-NEXT:   GLOBAL_STORE_DWORDX4 undef %448:vreg_64, [[REG_SEQUENCE23]], 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef`, align 128, addrspace 1)
  ; CHECK-NEXT:   [[COPY297:%[0-9]+]]:vgpr_32 = COPY [[COPY32]].sub31
  ; CHECK-NEXT:   [[COPY298:%[0-9]+]]:vgpr_32 = COPY [[COPY32]].sub30
  ; CHECK-NEXT:   [[COPY299:%[0-9]+]]:vgpr_32 = COPY [[COPY32]].sub29
  ; CHECK-NEXT:   [[COPY300:%[0-9]+]]:vgpr_32 = COPY [[COPY32]].sub28
  ; CHECK-NEXT:   [[REG_SEQUENCE24:%[0-9]+]]:vreg_128 = REG_SEQUENCE [[COPY300]], %subreg.sub0, [[COPY299]], %subreg.sub1, [[COPY298]], %subreg.sub2, [[COPY297]], %subreg.sub3
  ; CHECK-NEXT:   GLOBAL_STORE_DWORDX4 undef %456:vreg_64, [[REG_SEQUENCE24]], 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 112, addrspace 1)
  ; CHECK-NEXT:   [[COPY301:%[0-9]+]]:vgpr_32 = COPY [[COPY32]].sub27
  ; CHECK-NEXT:   [[COPY302:%[0-9]+]]:vgpr_32 = COPY [[COPY32]].sub26
  ; CHECK-NEXT:   [[COPY303:%[0-9]+]]:vgpr_32 = COPY [[COPY32]].sub25
  ; CHECK-NEXT:   [[COPY304:%[0-9]+]]:vgpr_32 = COPY [[COPY32]].sub24
  ; CHECK-NEXT:   [[REG_SEQUENCE25:%[0-9]+]]:vreg_128 = REG_SEQUENCE [[COPY304]], %subreg.sub0, [[COPY303]], %subreg.sub1, [[COPY302]], %subreg.sub2, [[COPY301]], %subreg.sub3
  ; CHECK-NEXT:   GLOBAL_STORE_DWORDX4 undef %464:vreg_64, [[REG_SEQUENCE25]], 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 96, align 32, addrspace 1)
  ; CHECK-NEXT:   [[COPY305:%[0-9]+]]:vgpr_32 = COPY [[COPY32]].sub23
  ; CHECK-NEXT:   [[COPY306:%[0-9]+]]:vgpr_32 = COPY [[COPY32]].sub22
  ; CHECK-NEXT:   [[COPY307:%[0-9]+]]:vgpr_32 = COPY [[COPY32]].sub21
  ; CHECK-NEXT:   [[COPY308:%[0-9]+]]:vgpr_32 = COPY [[COPY32]].sub20
  ; CHECK-NEXT:   [[REG_SEQUENCE26:%[0-9]+]]:vreg_128 = REG_SEQUENCE [[COPY308]], %subreg.sub0, [[COPY307]], %subreg.sub1, [[COPY306]], %subreg.sub2, [[COPY305]], %subreg.sub3
  ; CHECK-NEXT:   GLOBAL_STORE_DWORDX4 undef %472:vreg_64, [[REG_SEQUENCE26]], 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 80, addrspace 1)
  ; CHECK-NEXT:   [[COPY309:%[0-9]+]]:vgpr_32 = COPY [[COPY32]].sub19
  ; CHECK-NEXT:   [[COPY310:%[0-9]+]]:vgpr_32 = COPY [[COPY32]].sub18
  ; CHECK-NEXT:   [[COPY311:%[0-9]+]]:vgpr_32 = COPY [[COPY32]].sub17
  ; CHECK-NEXT:   [[COPY312:%[0-9]+]]:vgpr_32 = COPY [[COPY32]].sub16
  ; CHECK-NEXT:   [[REG_SEQUENCE27:%[0-9]+]]:vreg_128 = REG_SEQUENCE [[COPY312]], %subreg.sub0, [[COPY311]], %subreg.sub1, [[COPY310]], %subreg.sub2, [[COPY309]], %subreg.sub3
  ; CHECK-NEXT:   GLOBAL_STORE_DWORDX4 undef %480:vreg_64, [[REG_SEQUENCE27]], 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 64, align 64, addrspace 1)
  ; CHECK-NEXT:   [[COPY313:%[0-9]+]]:vgpr_32 = COPY [[COPY32]].sub15
  ; CHECK-NEXT:   [[COPY314:%[0-9]+]]:vgpr_32 = COPY [[COPY32]].sub14
  ; CHECK-NEXT:   [[COPY315:%[0-9]+]]:vgpr_32 = COPY [[COPY32]].sub13
  ; CHECK-NEXT:   [[COPY316:%[0-9]+]]:vgpr_32 = COPY [[COPY32]].sub12
  ; CHECK-NEXT:   [[REG_SEQUENCE28:%[0-9]+]]:vreg_128 = REG_SEQUENCE [[COPY316]], %subreg.sub0, [[COPY315]], %subreg.sub1, [[COPY314]], %subreg.sub2, [[COPY313]], %subreg.sub3
  ; CHECK-NEXT:   GLOBAL_STORE_DWORDX4 undef %488:vreg_64, [[REG_SEQUENCE28]], 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 48, addrspace 1)
  ; CHECK-NEXT:   [[COPY317:%[0-9]+]]:vgpr_32 = COPY [[COPY32]].sub11
  ; CHECK-NEXT:   [[COPY318:%[0-9]+]]:vgpr_32 = COPY [[COPY32]].sub10
  ; CHECK-NEXT:   [[COPY319:%[0-9]+]]:vgpr_32 = COPY [[COPY32]].sub9
  ; CHECK-NEXT:   [[COPY320:%[0-9]+]]:vgpr_32 = COPY [[COPY32]].sub8
  ; CHECK-NEXT:   [[REG_SEQUENCE29:%[0-9]+]]:vreg_128 = REG_SEQUENCE [[COPY320]], %subreg.sub0, [[COPY319]], %subreg.sub1, [[COPY318]], %subreg.sub2, [[COPY317]], %subreg.sub3
  ; CHECK-NEXT:   GLOBAL_STORE_DWORDX4 undef %496:vreg_64, [[REG_SEQUENCE29]], 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 32, align 32, addrspace 1)
  ; CHECK-NEXT:   [[COPY321:%[0-9]+]]:vgpr_32 = COPY [[COPY32]].sub7
  ; CHECK-NEXT:   [[COPY322:%[0-9]+]]:vgpr_32 = COPY [[COPY32]].sub6
  ; CHECK-NEXT:   [[COPY323:%[0-9]+]]:vgpr_32 = COPY [[COPY32]].sub5
  ; CHECK-NEXT:   [[COPY324:%[0-9]+]]:vgpr_32 = COPY [[COPY32]].sub4
  ; CHECK-NEXT:   [[REG_SEQUENCE30:%[0-9]+]]:vreg_128 = REG_SEQUENCE [[COPY324]], %subreg.sub0, [[COPY323]], %subreg.sub1, [[COPY322]], %subreg.sub2, [[COPY321]], %subreg.sub3
  ; CHECK-NEXT:   GLOBAL_STORE_DWORDX4 undef %504:vreg_64, [[REG_SEQUENCE30]], 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 16, addrspace 1)
  ; CHECK-NEXT:   [[COPY325:%[0-9]+]]:vgpr_32 = COPY [[COPY32]].sub3
  ; CHECK-NEXT:   [[COPY326:%[0-9]+]]:vgpr_32 = COPY [[COPY32]].sub2
  ; CHECK-NEXT:   [[COPY327:%[0-9]+]]:vgpr_32 = COPY [[COPY32]].sub1
  ; CHECK-NEXT:   [[COPY328:%[0-9]+]]:vgpr_32 = COPY [[COPY32]].sub0
  ; CHECK-NEXT:   [[REG_SEQUENCE31:%[0-9]+]]:vreg_128 = REG_SEQUENCE [[COPY328]], %subreg.sub0, [[COPY327]], %subreg.sub1, [[COPY326]], %subreg.sub2, [[COPY325]], %subreg.sub3
  ; CHECK-NEXT:   GLOBAL_STORE_DWORDX4 undef %512:vreg_64, [[REG_SEQUENCE31]], 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef`, align 128, addrspace 1)
  ; CHECK-NEXT:   [[COPY329:%[0-9]+]]:vgpr_32 = COPY [[COPY66]].sub31
  ; CHECK-NEXT:   [[COPY330:%[0-9]+]]:vgpr_32 = COPY [[COPY66]].sub30
  ; CHECK-NEXT:   [[COPY331:%[0-9]+]]:vgpr_32 = COPY [[COPY66]].sub29
  ; CHECK-NEXT:   [[COPY332:%[0-9]+]]:vgpr_32 = COPY [[COPY66]].sub28
  ; CHECK-NEXT:   [[REG_SEQUENCE32:%[0-9]+]]:vreg_128 = REG_SEQUENCE [[COPY332]], %subreg.sub0, [[COPY331]], %subreg.sub1, [[COPY330]], %subreg.sub2, [[COPY329]], %subreg.sub3
  ; CHECK-NEXT:   GLOBAL_STORE_DWORDX4 undef %520:vreg_64, [[REG_SEQUENCE32]], 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 112, addrspace 1)
  ; CHECK-NEXT:   [[COPY333:%[0-9]+]]:vgpr_32 = COPY [[COPY66]].sub27
  ; CHECK-NEXT:   [[COPY334:%[0-9]+]]:vgpr_32 = COPY [[COPY66]].sub26
  ; CHECK-NEXT:   [[COPY335:%[0-9]+]]:vgpr_32 = COPY [[COPY66]].sub25
  ; CHECK-NEXT:   [[COPY336:%[0-9]+]]:vgpr_32 = COPY [[COPY66]].sub24
  ; CHECK-NEXT:   [[REG_SEQUENCE33:%[0-9]+]]:vreg_128 = REG_SEQUENCE [[COPY336]], %subreg.sub0, [[COPY335]], %subreg.sub1, [[COPY334]], %subreg.sub2, [[COPY333]], %subreg.sub3
  ; CHECK-NEXT:   GLOBAL_STORE_DWORDX4 undef %528:vreg_64, [[REG_SEQUENCE33]], 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 96, align 32, addrspace 1)
  ; CHECK-NEXT:   [[COPY337:%[0-9]+]]:vgpr_32 = COPY [[COPY66]].sub23
  ; CHECK-NEXT:   [[COPY338:%[0-9]+]]:vgpr_32 = COPY [[COPY66]].sub22
  ; CHECK-NEXT:   [[COPY339:%[0-9]+]]:vgpr_32 = COPY [[COPY66]].sub21
  ; CHECK-NEXT:   [[COPY340:%[0-9]+]]:vgpr_32 = COPY [[COPY66]].sub20
  ; CHECK-NEXT:   [[REG_SEQUENCE34:%[0-9]+]]:vreg_128 = REG_SEQUENCE [[COPY340]], %subreg.sub0, [[COPY339]], %subreg.sub1, [[COPY338]], %subreg.sub2, [[COPY337]], %subreg.sub3
  ; CHECK-NEXT:   GLOBAL_STORE_DWORDX4 undef %536:vreg_64, [[REG_SEQUENCE34]], 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 80, addrspace 1)
  ; CHECK-NEXT:   [[COPY341:%[0-9]+]]:vgpr_32 = COPY [[COPY66]].sub19
  ; CHECK-NEXT:   [[COPY342:%[0-9]+]]:vgpr_32 = COPY [[COPY66]].sub18
  ; CHECK-NEXT:   [[COPY343:%[0-9]+]]:vgpr_32 = COPY [[COPY66]].sub17
  ; CHECK-NEXT:   [[COPY344:%[0-9]+]]:vgpr_32 = COPY [[COPY66]].sub16
  ; CHECK-NEXT:   [[REG_SEQUENCE35:%[0-9]+]]:vreg_128 = REG_SEQUENCE [[COPY344]], %subreg.sub0, [[COPY343]], %subreg.sub1, [[COPY342]], %subreg.sub2, [[COPY341]], %subreg.sub3
  ; CHECK-NEXT:   GLOBAL_STORE_DWORDX4 undef %544:vreg_64, [[REG_SEQUENCE35]], 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 64, align 64, addrspace 1)
  ; CHECK-NEXT:   [[COPY345:%[0-9]+]]:vgpr_32 = COPY [[COPY66]].sub15
  ; CHECK-NEXT:   [[COPY346:%[0-9]+]]:vgpr_32 = COPY [[COPY66]].sub14
  ; CHECK-NEXT:   [[COPY347:%[0-9]+]]:vgpr_32 = COPY [[COPY66]].sub13
  ; CHECK-NEXT:   [[COPY348:%[0-9]+]]:vgpr_32 = COPY [[COPY66]].sub12
  ; CHECK-NEXT:   [[REG_SEQUENCE36:%[0-9]+]]:vreg_128 = REG_SEQUENCE [[COPY348]], %subreg.sub0, [[COPY347]], %subreg.sub1, [[COPY346]], %subreg.sub2, [[COPY345]], %subreg.sub3
  ; CHECK-NEXT:   GLOBAL_STORE_DWORDX4 undef %552:vreg_64, [[REG_SEQUENCE36]], 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 48, addrspace 1)
  ; CHECK-NEXT:   [[COPY349:%[0-9]+]]:vgpr_32 = COPY [[COPY66]].sub11
  ; CHECK-NEXT:   [[COPY350:%[0-9]+]]:vgpr_32 = COPY [[COPY66]].sub10
  ; CHECK-NEXT:   [[COPY351:%[0-9]+]]:vgpr_32 = COPY [[COPY66]].sub9
  ; CHECK-NEXT:   [[COPY352:%[0-9]+]]:vgpr_32 = COPY [[COPY66]].sub8
  ; CHECK-NEXT:   [[REG_SEQUENCE37:%[0-9]+]]:vreg_128 = REG_SEQUENCE [[COPY352]], %subreg.sub0, [[COPY351]], %subreg.sub1, [[COPY350]], %subreg.sub2, [[COPY349]], %subreg.sub3
  ; CHECK-NEXT:   GLOBAL_STORE_DWORDX4 undef %560:vreg_64, [[REG_SEQUENCE37]], 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 32, align 32, addrspace 1)
  ; CHECK-NEXT:   [[COPY353:%[0-9]+]]:vgpr_32 = COPY [[COPY66]].sub7
  ; CHECK-NEXT:   [[COPY354:%[0-9]+]]:vgpr_32 = COPY [[COPY66]].sub6
  ; CHECK-NEXT:   [[COPY355:%[0-9]+]]:vgpr_32 = COPY [[COPY66]].sub5
  ; CHECK-NEXT:   [[COPY356:%[0-9]+]]:vgpr_32 = COPY [[COPY66]].sub4
  ; CHECK-NEXT:   [[REG_SEQUENCE38:%[0-9]+]]:vreg_128 = REG_SEQUENCE [[COPY356]], %subreg.sub0, [[COPY355]], %subreg.sub1, [[COPY354]], %subreg.sub2, [[COPY353]], %subreg.sub3
  ; CHECK-NEXT:   GLOBAL_STORE_DWORDX4 undef %568:vreg_64, [[REG_SEQUENCE38]], 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 16, addrspace 1)
  ; CHECK-NEXT:   [[COPY357:%[0-9]+]]:vgpr_32 = COPY [[COPY66]].sub3
  ; CHECK-NEXT:   [[COPY358:%[0-9]+]]:vgpr_32 = COPY [[COPY66]].sub2
  ; CHECK-NEXT:   [[COPY359:%[0-9]+]]:vgpr_32 = COPY [[COPY66]].sub1
  ; CHECK-NEXT:   [[COPY360:%[0-9]+]]:vgpr_32 = COPY [[COPY66]].sub0
  ; CHECK-NEXT:   [[REG_SEQUENCE39:%[0-9]+]]:vreg_128 = REG_SEQUENCE [[COPY360]], %subreg.sub0, [[COPY359]], %subreg.sub1, [[COPY358]], %subreg.sub2, [[COPY357]], %subreg.sub3
  ; CHECK-NEXT:   GLOBAL_STORE_DWORDX4 undef %576:vreg_64, [[REG_SEQUENCE39]], 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef`, align 128, addrspace 1)
  ; CHECK-NEXT:   [[COPY361:%[0-9]+]]:vgpr_32 = COPY [[COPY99]].sub31
  ; CHECK-NEXT:   [[COPY362:%[0-9]+]]:vgpr_32 = COPY [[COPY99]].sub30
  ; CHECK-NEXT:   [[COPY363:%[0-9]+]]:vgpr_32 = COPY [[COPY99]].sub29
  ; CHECK-NEXT:   [[COPY364:%[0-9]+]]:vgpr_32 = COPY [[COPY99]].sub28
  ; CHECK-NEXT:   [[REG_SEQUENCE40:%[0-9]+]]:vreg_128 = REG_SEQUENCE [[COPY364]], %subreg.sub0, [[COPY363]], %subreg.sub1, [[COPY362]], %subreg.sub2, [[COPY361]], %subreg.sub3
  ; CHECK-NEXT:   GLOBAL_STORE_DWORDX4 undef %584:vreg_64, [[REG_SEQUENCE40]], 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 112, addrspace 1)
  ; CHECK-NEXT:   [[COPY365:%[0-9]+]]:vgpr_32 = COPY [[COPY99]].sub27
  ; CHECK-NEXT:   [[COPY366:%[0-9]+]]:vgpr_32 = COPY [[COPY99]].sub26
  ; CHECK-NEXT:   [[COPY367:%[0-9]+]]:vgpr_32 = COPY [[COPY99]].sub25
  ; CHECK-NEXT:   [[COPY368:%[0-9]+]]:vgpr_32 = COPY [[COPY99]].sub24
  ; CHECK-NEXT:   [[REG_SEQUENCE41:%[0-9]+]]:vreg_128 = REG_SEQUENCE [[COPY368]], %subreg.sub0, [[COPY367]], %subreg.sub1, [[COPY366]], %subreg.sub2, [[COPY365]], %subreg.sub3
  ; CHECK-NEXT:   GLOBAL_STORE_DWORDX4 undef %592:vreg_64, [[REG_SEQUENCE41]], 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 96, align 32, addrspace 1)
  ; CHECK-NEXT:   [[COPY369:%[0-9]+]]:vgpr_32 = COPY [[COPY99]].sub23
  ; CHECK-NEXT:   [[COPY370:%[0-9]+]]:vgpr_32 = COPY [[COPY99]].sub22
  ; CHECK-NEXT:   [[COPY371:%[0-9]+]]:vgpr_32 = COPY [[COPY99]].sub21
  ; CHECK-NEXT:   [[COPY372:%[0-9]+]]:vgpr_32 = COPY [[COPY99]].sub20
  ; CHECK-NEXT:   [[REG_SEQUENCE42:%[0-9]+]]:vreg_128 = REG_SEQUENCE [[COPY372]], %subreg.sub0, [[COPY371]], %subreg.sub1, [[COPY370]], %subreg.sub2, [[COPY369]], %subreg.sub3
  ; CHECK-NEXT:   GLOBAL_STORE_DWORDX4 undef %600:vreg_64, [[REG_SEQUENCE42]], 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 80, addrspace 1)
  ; CHECK-NEXT:   [[COPY373:%[0-9]+]]:vgpr_32 = COPY [[COPY99]].sub19
  ; CHECK-NEXT:   [[COPY374:%[0-9]+]]:vgpr_32 = COPY [[COPY99]].sub18
  ; CHECK-NEXT:   [[COPY375:%[0-9]+]]:vgpr_32 = COPY [[COPY99]].sub17
  ; CHECK-NEXT:   [[COPY376:%[0-9]+]]:vgpr_32 = COPY [[COPY99]].sub16
  ; CHECK-NEXT:   [[REG_SEQUENCE43:%[0-9]+]]:vreg_128 = REG_SEQUENCE [[COPY376]], %subreg.sub0, [[COPY375]], %subreg.sub1, [[COPY374]], %subreg.sub2, [[COPY373]], %subreg.sub3
  ; CHECK-NEXT:   GLOBAL_STORE_DWORDX4 undef %608:vreg_64, [[REG_SEQUENCE43]], 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 64, align 64, addrspace 1)
  ; CHECK-NEXT:   [[COPY377:%[0-9]+]]:vgpr_32 = COPY [[COPY99]].sub15
  ; CHECK-NEXT:   [[COPY378:%[0-9]+]]:vgpr_32 = COPY [[COPY99]].sub14
  ; CHECK-NEXT:   [[COPY379:%[0-9]+]]:vgpr_32 = COPY [[COPY99]].sub13
  ; CHECK-NEXT:   [[COPY380:%[0-9]+]]:vgpr_32 = COPY [[COPY99]].sub12
  ; CHECK-NEXT:   [[REG_SEQUENCE44:%[0-9]+]]:vreg_128 = REG_SEQUENCE [[COPY380]], %subreg.sub0, [[COPY379]], %subreg.sub1, [[COPY378]], %subreg.sub2, [[COPY377]], %subreg.sub3
  ; CHECK-NEXT:   GLOBAL_STORE_DWORDX4 undef %616:vreg_64, [[REG_SEQUENCE44]], 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 48, addrspace 1)
  ; CHECK-NEXT:   [[COPY381:%[0-9]+]]:vgpr_32 = COPY [[COPY99]].sub11
  ; CHECK-NEXT:   [[COPY382:%[0-9]+]]:vgpr_32 = COPY [[COPY99]].sub10
  ; CHECK-NEXT:   [[COPY383:%[0-9]+]]:vgpr_32 = COPY [[COPY99]].sub9
  ; CHECK-NEXT:   [[COPY384:%[0-9]+]]:vgpr_32 = COPY [[COPY99]].sub8
  ; CHECK-NEXT:   [[REG_SEQUENCE45:%[0-9]+]]:vreg_128 = REG_SEQUENCE [[COPY384]], %subreg.sub0, [[COPY383]], %subreg.sub1, [[COPY382]], %subreg.sub2, [[COPY381]], %subreg.sub3
  ; CHECK-NEXT:   GLOBAL_STORE_DWORDX4 undef %624:vreg_64, [[REG_SEQUENCE45]], 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 32, align 32, addrspace 1)
  ; CHECK-NEXT:   [[COPY385:%[0-9]+]]:vgpr_32 = COPY [[COPY99]].sub7
  ; CHECK-NEXT:   [[COPY386:%[0-9]+]]:vgpr_32 = COPY [[COPY99]].sub6
  ; CHECK-NEXT:   [[COPY387:%[0-9]+]]:vgpr_32 = COPY [[COPY99]].sub5
  ; CHECK-NEXT:   [[COPY388:%[0-9]+]]:vgpr_32 = COPY [[COPY99]].sub4
  ; CHECK-NEXT:   [[REG_SEQUENCE46:%[0-9]+]]:vreg_128 = REG_SEQUENCE [[COPY388]], %subreg.sub0, [[COPY387]], %subreg.sub1, [[COPY386]], %subreg.sub2, [[COPY385]], %subreg.sub3
  ; CHECK-NEXT:   GLOBAL_STORE_DWORDX4 undef %632:vreg_64, [[REG_SEQUENCE46]], 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 16, addrspace 1)
  ; CHECK-NEXT:   [[COPY389:%[0-9]+]]:vgpr_32 = COPY [[COPY99]].sub3
  ; CHECK-NEXT:   [[COPY390:%[0-9]+]]:vgpr_32 = COPY [[COPY99]].sub2
  ; CHECK-NEXT:   [[COPY391:%[0-9]+]]:vgpr_32 = COPY [[COPY99]].sub1
  ; CHECK-NEXT:   [[COPY392:%[0-9]+]]:vgpr_32 = COPY [[COPY99]].sub0
  ; CHECK-NEXT:   [[REG_SEQUENCE47:%[0-9]+]]:vreg_128 = REG_SEQUENCE [[COPY392]], %subreg.sub0, [[COPY391]], %subreg.sub1, [[COPY390]], %subreg.sub2, [[COPY389]], %subreg.sub3
  ; CHECK-NEXT:   GLOBAL_STORE_DWORDX4 undef %640:vreg_64, [[REG_SEQUENCE47]], 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef`, align 128, addrspace 1)
  ; CHECK-NEXT:   [[COPY393:%[0-9]+]]:vgpr_32 = COPY [[COPY132]].sub31
  ; CHECK-NEXT:   [[COPY394:%[0-9]+]]:vgpr_32 = COPY [[COPY132]].sub30
  ; CHECK-NEXT:   [[COPY395:%[0-9]+]]:vgpr_32 = COPY [[COPY132]].sub29
  ; CHECK-NEXT:   [[COPY396:%[0-9]+]]:vgpr_32 = COPY [[COPY132]].sub28
  ; CHECK-NEXT:   [[REG_SEQUENCE48:%[0-9]+]]:vreg_128 = REG_SEQUENCE [[COPY396]], %subreg.sub0, [[COPY395]], %subreg.sub1, [[COPY394]], %subreg.sub2, [[COPY393]], %subreg.sub3
  ; CHECK-NEXT:   GLOBAL_STORE_DWORDX4 undef %648:vreg_64, [[REG_SEQUENCE48]], 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 112, addrspace 1)
  ; CHECK-NEXT:   [[COPY397:%[0-9]+]]:vgpr_32 = COPY [[COPY132]].sub27
  ; CHECK-NEXT:   [[COPY398:%[0-9]+]]:vgpr_32 = COPY [[COPY132]].sub26
  ; CHECK-NEXT:   [[COPY399:%[0-9]+]]:vgpr_32 = COPY [[COPY132]].sub25
  ; CHECK-NEXT:   [[COPY400:%[0-9]+]]:vgpr_32 = COPY [[COPY132]].sub24
  ; CHECK-NEXT:   [[REG_SEQUENCE49:%[0-9]+]]:vreg_128 = REG_SEQUENCE [[COPY400]], %subreg.sub0, [[COPY399]], %subreg.sub1, [[COPY398]], %subreg.sub2, [[COPY397]], %subreg.sub3
  ; CHECK-NEXT:   GLOBAL_STORE_DWORDX4 undef %656:vreg_64, [[REG_SEQUENCE49]], 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 96, align 32, addrspace 1)
  ; CHECK-NEXT:   [[COPY401:%[0-9]+]]:vgpr_32 = COPY [[COPY132]].sub23
  ; CHECK-NEXT:   [[COPY402:%[0-9]+]]:vgpr_32 = COPY [[COPY132]].sub22
  ; CHECK-NEXT:   [[COPY403:%[0-9]+]]:vgpr_32 = COPY [[COPY132]].sub21
  ; CHECK-NEXT:   [[COPY404:%[0-9]+]]:vgpr_32 = COPY [[COPY132]].sub20
  ; CHECK-NEXT:   [[REG_SEQUENCE50:%[0-9]+]]:vreg_128 = REG_SEQUENCE [[COPY404]], %subreg.sub0, [[COPY403]], %subreg.sub1, [[COPY402]], %subreg.sub2, [[COPY401]], %subreg.sub3
  ; CHECK-NEXT:   GLOBAL_STORE_DWORDX4 undef %664:vreg_64, [[REG_SEQUENCE50]], 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 80, addrspace 1)
  ; CHECK-NEXT:   [[COPY405:%[0-9]+]]:vgpr_32 = COPY [[COPY132]].sub19
  ; CHECK-NEXT:   [[COPY406:%[0-9]+]]:vgpr_32 = COPY [[COPY132]].sub18
  ; CHECK-NEXT:   [[COPY407:%[0-9]+]]:vgpr_32 = COPY [[COPY132]].sub17
  ; CHECK-NEXT:   [[COPY408:%[0-9]+]]:vgpr_32 = COPY [[COPY132]].sub16
  ; CHECK-NEXT:   [[REG_SEQUENCE51:%[0-9]+]]:vreg_128 = REG_SEQUENCE [[COPY408]], %subreg.sub0, [[COPY407]], %subreg.sub1, [[COPY406]], %subreg.sub2, [[COPY405]], %subreg.sub3
  ; CHECK-NEXT:   GLOBAL_STORE_DWORDX4 undef %672:vreg_64, [[REG_SEQUENCE51]], 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 64, align 64, addrspace 1)
  ; CHECK-NEXT:   [[COPY409:%[0-9]+]]:vgpr_32 = COPY [[COPY132]].sub15
  ; CHECK-NEXT:   [[COPY410:%[0-9]+]]:vgpr_32 = COPY [[COPY132]].sub14
  ; CHECK-NEXT:   [[COPY411:%[0-9]+]]:vgpr_32 = COPY [[COPY132]].sub13
  ; CHECK-NEXT:   [[COPY412:%[0-9]+]]:vgpr_32 = COPY [[COPY132]].sub12
  ; CHECK-NEXT:   [[REG_SEQUENCE52:%[0-9]+]]:vreg_128 = REG_SEQUENCE [[COPY412]], %subreg.sub0, [[COPY411]], %subreg.sub1, [[COPY410]], %subreg.sub2, [[COPY409]], %subreg.sub3
  ; CHECK-NEXT:   GLOBAL_STORE_DWORDX4 undef %680:vreg_64, [[REG_SEQUENCE52]], 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 48, addrspace 1)
  ; CHECK-NEXT:   [[COPY413:%[0-9]+]]:vgpr_32 = COPY [[COPY132]].sub11
  ; CHECK-NEXT:   [[COPY414:%[0-9]+]]:vgpr_32 = COPY [[COPY132]].sub10
  ; CHECK-NEXT:   [[COPY415:%[0-9]+]]:vgpr_32 = COPY [[COPY132]].sub9
  ; CHECK-NEXT:   [[COPY416:%[0-9]+]]:vgpr_32 = COPY [[COPY132]].sub8
  ; CHECK-NEXT:   [[REG_SEQUENCE53:%[0-9]+]]:vreg_128 = REG_SEQUENCE [[COPY416]], %subreg.sub0, [[COPY415]], %subreg.sub1, [[COPY414]], %subreg.sub2, [[COPY413]], %subreg.sub3
  ; CHECK-NEXT:   GLOBAL_STORE_DWORDX4 undef %688:vreg_64, [[REG_SEQUENCE53]], 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 32, align 32, addrspace 1)
  ; CHECK-NEXT:   [[COPY417:%[0-9]+]]:vgpr_32 = COPY [[COPY132]].sub7
  ; CHECK-NEXT:   [[COPY418:%[0-9]+]]:vgpr_32 = COPY [[COPY132]].sub6
  ; CHECK-NEXT:   [[COPY419:%[0-9]+]]:vgpr_32 = COPY [[COPY132]].sub5
  ; CHECK-NEXT:   [[COPY420:%[0-9]+]]:vgpr_32 = COPY [[COPY132]].sub4
  ; CHECK-NEXT:   [[REG_SEQUENCE54:%[0-9]+]]:vreg_128 = REG_SEQUENCE [[COPY420]], %subreg.sub0, [[COPY419]], %subreg.sub1, [[COPY418]], %subreg.sub2, [[COPY417]], %subreg.sub3
  ; CHECK-NEXT:   GLOBAL_STORE_DWORDX4 undef %696:vreg_64, [[REG_SEQUENCE54]], 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 16, addrspace 1)
  ; CHECK-NEXT:   [[COPY421:%[0-9]+]]:vgpr_32 = COPY [[COPY132]].sub3
  ; CHECK-NEXT:   [[COPY422:%[0-9]+]]:vgpr_32 = COPY [[COPY132]].sub2
  ; CHECK-NEXT:   [[COPY423:%[0-9]+]]:vgpr_32 = COPY [[COPY132]].sub1
  ; CHECK-NEXT:   [[COPY424:%[0-9]+]]:vgpr_32 = COPY [[COPY132]].sub0
  ; CHECK-NEXT:   [[REG_SEQUENCE55:%[0-9]+]]:vreg_128 = REG_SEQUENCE [[COPY424]], %subreg.sub0, [[COPY423]], %subreg.sub1, [[COPY422]], %subreg.sub2, [[COPY421]], %subreg.sub3
  ; CHECK-NEXT:   GLOBAL_STORE_DWORDX4 undef %704:vreg_64, [[REG_SEQUENCE55]], 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef`, align 128, addrspace 1)
  ; CHECK-NEXT:   [[COPY425:%[0-9]+]]:vgpr_32 = COPY [[COPY165]].sub31
  ; CHECK-NEXT:   [[COPY426:%[0-9]+]]:vgpr_32 = COPY [[COPY165]].sub30
  ; CHECK-NEXT:   [[COPY427:%[0-9]+]]:vgpr_32 = COPY [[COPY165]].sub29
  ; CHECK-NEXT:   [[COPY428:%[0-9]+]]:vgpr_32 = COPY [[COPY165]].sub28
  ; CHECK-NEXT:   [[REG_SEQUENCE56:%[0-9]+]]:vreg_128 = REG_SEQUENCE [[COPY428]], %subreg.sub0, [[COPY427]], %subreg.sub1, [[COPY426]], %subreg.sub2, [[COPY425]], %subreg.sub3
  ; CHECK-NEXT:   GLOBAL_STORE_DWORDX4 undef %712:vreg_64, [[REG_SEQUENCE56]], 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 112, addrspace 1)
  ; CHECK-NEXT:   [[COPY429:%[0-9]+]]:vgpr_32 = COPY [[COPY165]].sub27
  ; CHECK-NEXT:   [[COPY430:%[0-9]+]]:vgpr_32 = COPY [[COPY165]].sub26
  ; CHECK-NEXT:   [[COPY431:%[0-9]+]]:vgpr_32 = COPY [[COPY165]].sub25
  ; CHECK-NEXT:   [[COPY432:%[0-9]+]]:vgpr_32 = COPY [[COPY165]].sub24
  ; CHECK-NEXT:   [[REG_SEQUENCE57:%[0-9]+]]:vreg_128 = REG_SEQUENCE [[COPY432]], %subreg.sub0, [[COPY431]], %subreg.sub1, [[COPY430]], %subreg.sub2, [[COPY429]], %subreg.sub3
  ; CHECK-NEXT:   GLOBAL_STORE_DWORDX4 undef %720:vreg_64, [[REG_SEQUENCE57]], 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 96, align 32, addrspace 1)
  ; CHECK-NEXT:   [[COPY433:%[0-9]+]]:vgpr_32 = COPY [[COPY165]].sub23
  ; CHECK-NEXT:   [[COPY434:%[0-9]+]]:vgpr_32 = COPY [[COPY165]].sub22
  ; CHECK-NEXT:   [[COPY435:%[0-9]+]]:vgpr_32 = COPY [[COPY165]].sub21
  ; CHECK-NEXT:   [[COPY436:%[0-9]+]]:vgpr_32 = COPY [[COPY165]].sub20
  ; CHECK-NEXT:   [[REG_SEQUENCE58:%[0-9]+]]:vreg_128 = REG_SEQUENCE [[COPY436]], %subreg.sub0, [[COPY435]], %subreg.sub1, [[COPY434]], %subreg.sub2, [[COPY433]], %subreg.sub3
  ; CHECK-NEXT:   GLOBAL_STORE_DWORDX4 undef %728:vreg_64, [[REG_SEQUENCE58]], 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 80, addrspace 1)
  ; CHECK-NEXT:   [[COPY437:%[0-9]+]]:vgpr_32 = COPY [[COPY165]].sub19
  ; CHECK-NEXT:   [[COPY438:%[0-9]+]]:vgpr_32 = COPY [[COPY165]].sub18
  ; CHECK-NEXT:   [[COPY439:%[0-9]+]]:vgpr_32 = COPY [[COPY165]].sub17
  ; CHECK-NEXT:   [[COPY440:%[0-9]+]]:vgpr_32 = COPY [[COPY165]].sub16
  ; CHECK-NEXT:   [[REG_SEQUENCE59:%[0-9]+]]:vreg_128 = REG_SEQUENCE [[COPY440]], %subreg.sub0, [[COPY439]], %subreg.sub1, [[COPY438]], %subreg.sub2, [[COPY437]], %subreg.sub3
  ; CHECK-NEXT:   GLOBAL_STORE_DWORDX4 undef %736:vreg_64, [[REG_SEQUENCE59]], 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 64, align 64, addrspace 1)
  ; CHECK-NEXT:   [[COPY441:%[0-9]+]]:vgpr_32 = COPY [[COPY165]].sub15
  ; CHECK-NEXT:   [[COPY442:%[0-9]+]]:vgpr_32 = COPY [[COPY165]].sub14
  ; CHECK-NEXT:   [[COPY443:%[0-9]+]]:vgpr_32 = COPY [[COPY165]].sub13
  ; CHECK-NEXT:   [[COPY444:%[0-9]+]]:vgpr_32 = COPY [[COPY165]].sub12
  ; CHECK-NEXT:   [[REG_SEQUENCE60:%[0-9]+]]:vreg_128 = REG_SEQUENCE [[COPY444]], %subreg.sub0, [[COPY443]], %subreg.sub1, [[COPY442]], %subreg.sub2, [[COPY441]], %subreg.sub3
  ; CHECK-NEXT:   GLOBAL_STORE_DWORDX4 undef %744:vreg_64, [[REG_SEQUENCE60]], 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 48, addrspace 1)
  ; CHECK-NEXT:   [[COPY445:%[0-9]+]]:vgpr_32 = COPY [[COPY165]].sub11
  ; CHECK-NEXT:   [[COPY446:%[0-9]+]]:vgpr_32 = COPY [[COPY165]].sub10
  ; CHECK-NEXT:   [[COPY447:%[0-9]+]]:vgpr_32 = COPY [[COPY165]].sub9
  ; CHECK-NEXT:   [[COPY448:%[0-9]+]]:vgpr_32 = COPY [[COPY165]].sub8
  ; CHECK-NEXT:   [[REG_SEQUENCE61:%[0-9]+]]:vreg_128 = REG_SEQUENCE [[COPY448]], %subreg.sub0, [[COPY447]], %subreg.sub1, [[COPY446]], %subreg.sub2, [[COPY445]], %subreg.sub3
  ; CHECK-NEXT:   GLOBAL_STORE_DWORDX4 undef %752:vreg_64, [[REG_SEQUENCE61]], 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 32, align 32, addrspace 1)
  ; CHECK-NEXT:   [[COPY449:%[0-9]+]]:vgpr_32 = COPY [[COPY165]].sub7
  ; CHECK-NEXT:   [[COPY450:%[0-9]+]]:vgpr_32 = COPY [[COPY165]].sub6
  ; CHECK-NEXT:   [[COPY451:%[0-9]+]]:vgpr_32 = COPY [[COPY165]].sub5
  ; CHECK-NEXT:   [[COPY452:%[0-9]+]]:vgpr_32 = COPY [[COPY165]].sub4
  ; CHECK-NEXT:   [[REG_SEQUENCE62:%[0-9]+]]:vreg_128 = REG_SEQUENCE [[COPY452]], %subreg.sub0, [[COPY451]], %subreg.sub1, [[COPY450]], %subreg.sub2, [[COPY449]], %subreg.sub3
  ; CHECK-NEXT:   GLOBAL_STORE_DWORDX4 undef %760:vreg_64, [[REG_SEQUENCE62]], 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 16, addrspace 1)
  ; CHECK-NEXT:   [[COPY453:%[0-9]+]]:vgpr_32 = COPY [[COPY165]].sub3
  ; CHECK-NEXT:   [[COPY454:%[0-9]+]]:vgpr_32 = COPY [[COPY165]].sub2
  ; CHECK-NEXT:   [[COPY455:%[0-9]+]]:vgpr_32 = COPY [[COPY165]].sub1
  ; CHECK-NEXT:   [[COPY456:%[0-9]+]]:vgpr_32 = COPY [[COPY165]].sub0
  ; CHECK-NEXT:   [[REG_SEQUENCE63:%[0-9]+]]:vreg_128 = REG_SEQUENCE [[COPY456]], %subreg.sub0, [[COPY455]], %subreg.sub1, [[COPY454]], %subreg.sub2, [[COPY453]], %subreg.sub3
  ; CHECK-NEXT:   GLOBAL_STORE_DWORDX4 undef %768:vreg_64, [[REG_SEQUENCE63]], 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef`, align 128, addrspace 1)
  ; CHECK-NEXT:   [[COPY457:%[0-9]+]]:vgpr_32 = COPY [[COPY198]].sub31
  ; CHECK-NEXT:   [[COPY458:%[0-9]+]]:vgpr_32 = COPY [[COPY198]].sub30
  ; CHECK-NEXT:   [[COPY459:%[0-9]+]]:vgpr_32 = COPY [[COPY198]].sub29
  ; CHECK-NEXT:   [[COPY460:%[0-9]+]]:vgpr_32 = COPY [[COPY198]].sub28
  ; CHECK-NEXT:   [[REG_SEQUENCE64:%[0-9]+]]:vreg_128 = REG_SEQUENCE [[COPY460]], %subreg.sub0, [[COPY459]], %subreg.sub1, [[COPY458]], %subreg.sub2, [[COPY457]], %subreg.sub3
  ; CHECK-NEXT:   GLOBAL_STORE_DWORDX4 undef %776:vreg_64, [[REG_SEQUENCE64]], 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 112, addrspace 1)
  ; CHECK-NEXT:   [[COPY461:%[0-9]+]]:vgpr_32 = COPY [[COPY198]].sub27
  ; CHECK-NEXT:   [[SI_SPILL_V32_RESTORE:%[0-9]+]]:vgpr_32 = SI_SPILL_V32_RESTORE %stack.26, $sgpr32, 0, implicit $exec :: (load (s32) from %stack.26, addrspace 5)
  ; CHECK-NEXT:   [[COPY462:%[0-9]+]]:vgpr_32 = COPY [[SI_SPILL_V32_RESTORE]]
  ; CHECK-NEXT:   [[SI_SPILL_V32_RESTORE1:%[0-9]+]]:vgpr_32 = SI_SPILL_V32_RESTORE %stack.25, $sgpr32, 0, implicit $exec :: (load (s32) from %stack.25, addrspace 5)
  ; CHECK-NEXT:   [[COPY463:%[0-9]+]]:vgpr_32 = COPY [[SI_SPILL_V32_RESTORE1]]
  ; CHECK-NEXT:   [[SI_SPILL_V32_RESTORE2:%[0-9]+]]:vgpr_32 = SI_SPILL_V32_RESTORE %stack.24, $sgpr32, 0, implicit $exec :: (load (s32) from %stack.24, addrspace 5)
  ; CHECK-NEXT:   [[COPY464:%[0-9]+]]:vgpr_32 = COPY [[SI_SPILL_V32_RESTORE2]]
  ; CHECK-NEXT:   [[REG_SEQUENCE65:%[0-9]+]]:vreg_128 = REG_SEQUENCE [[COPY464]], %subreg.sub0, [[COPY463]], %subreg.sub1, [[COPY462]], %subreg.sub2, [[COPY461]], %subreg.sub3
  ; CHECK-NEXT:   GLOBAL_STORE_DWORDX4 undef %784:vreg_64, [[REG_SEQUENCE65]], 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 96, align 32, addrspace 1)
  ; CHECK-NEXT:   [[SI_SPILL_V32_RESTORE3:%[0-9]+]]:vgpr_32 = SI_SPILL_V32_RESTORE %stack.23, $sgpr32, 0, implicit $exec :: (load (s32) from %stack.23, addrspace 5)
  ; CHECK-NEXT:   [[COPY465:%[0-9]+]]:vgpr_32 = COPY [[SI_SPILL_V32_RESTORE3]]
  ; CHECK-NEXT:   [[SI_SPILL_V32_RESTORE4:%[0-9]+]]:vgpr_32 = SI_SPILL_V32_RESTORE %stack.22, $sgpr32, 0, implicit $exec :: (load (s32) from %stack.22, addrspace 5)
  ; CHECK-NEXT:   [[COPY466:%[0-9]+]]:vgpr_32 = COPY [[SI_SPILL_V32_RESTORE4]]
  ; CHECK-NEXT:   [[SI_SPILL_V32_RESTORE5:%[0-9]+]]:vgpr_32 = SI_SPILL_V32_RESTORE %stack.21, $sgpr32, 0, implicit $exec :: (load (s32) from %stack.21, addrspace 5)
  ; CHECK-NEXT:   [[COPY467:%[0-9]+]]:vgpr_32 = COPY [[SI_SPILL_V32_RESTORE5]]
  ; CHECK-NEXT:   [[SI_SPILL_V32_RESTORE6:%[0-9]+]]:vgpr_32 = SI_SPILL_V32_RESTORE %stack.20, $sgpr32, 0, implicit $exec :: (load (s32) from %stack.20, addrspace 5)
  ; CHECK-NEXT:   [[COPY468:%[0-9]+]]:vgpr_32 = COPY [[SI_SPILL_V32_RESTORE6]]
  ; CHECK-NEXT:   [[REG_SEQUENCE66:%[0-9]+]]:vreg_128 = REG_SEQUENCE [[COPY468]], %subreg.sub0, [[COPY467]], %subreg.sub1, [[COPY466]], %subreg.sub2, [[COPY465]], %subreg.sub3
  ; CHECK-NEXT:   GLOBAL_STORE_DWORDX4 undef %792:vreg_64, [[REG_SEQUENCE66]], 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 80, addrspace 1)
  ; CHECK-NEXT:   [[SI_SPILL_V32_RESTORE7:%[0-9]+]]:vgpr_32 = SI_SPILL_V32_RESTORE %stack.19, $sgpr32, 0, implicit $exec :: (load (s32) from %stack.19, addrspace 5)
  ; CHECK-NEXT:   [[COPY469:%[0-9]+]]:vgpr_32 = COPY [[SI_SPILL_V32_RESTORE7]]
  ; CHECK-NEXT:   [[SI_SPILL_V32_RESTORE8:%[0-9]+]]:vgpr_32 = SI_SPILL_V32_RESTORE %stack.18, $sgpr32, 0, implicit $exec :: (load (s32) from %stack.18, addrspace 5)
  ; CHECK-NEXT:   [[COPY470:%[0-9]+]]:vgpr_32 = COPY [[SI_SPILL_V32_RESTORE8]]
  ; CHECK-NEXT:   [[SI_SPILL_V32_RESTORE9:%[0-9]+]]:vgpr_32 = SI_SPILL_V32_RESTORE %stack.17, $sgpr32, 0, implicit $exec :: (load (s32) from %stack.17, addrspace 5)
  ; CHECK-NEXT:   [[COPY471:%[0-9]+]]:vgpr_32 = COPY [[SI_SPILL_V32_RESTORE9]]
  ; CHECK-NEXT:   [[SI_SPILL_V32_RESTORE10:%[0-9]+]]:vgpr_32 = SI_SPILL_V32_RESTORE %stack.16, $sgpr32, 0, implicit $exec :: (load (s32) from %stack.16, addrspace 5)
  ; CHECK-NEXT:   [[COPY472:%[0-9]+]]:vgpr_32 = COPY [[SI_SPILL_V32_RESTORE10]]
  ; CHECK-NEXT:   [[REG_SEQUENCE67:%[0-9]+]]:vreg_128 = REG_SEQUENCE [[COPY472]], %subreg.sub0, [[COPY471]], %subreg.sub1, [[COPY470]], %subreg.sub2, [[COPY469]], %subreg.sub3
  ; CHECK-NEXT:   GLOBAL_STORE_DWORDX4 undef %800:vreg_64, [[REG_SEQUENCE67]], 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 64, align 64, addrspace 1)
  ; CHECK-NEXT:   [[SI_SPILL_V32_RESTORE11:%[0-9]+]]:vgpr_32 = SI_SPILL_V32_RESTORE %stack.15, $sgpr32, 0, implicit $exec :: (load (s32) from %stack.15, addrspace 5)
  ; CHECK-NEXT:   [[COPY473:%[0-9]+]]:vgpr_32 = COPY [[SI_SPILL_V32_RESTORE11]]
  ; CHECK-NEXT:   [[SI_SPILL_V32_RESTORE12:%[0-9]+]]:vgpr_32 = SI_SPILL_V32_RESTORE %stack.14, $sgpr32, 0, implicit $exec :: (load (s32) from %stack.14, addrspace 5)
  ; CHECK-NEXT:   [[COPY474:%[0-9]+]]:vgpr_32 = COPY [[SI_SPILL_V32_RESTORE12]]
  ; CHECK-NEXT:   [[SI_SPILL_V32_RESTORE13:%[0-9]+]]:vgpr_32 = SI_SPILL_V32_RESTORE %stack.13, $sgpr32, 0, implicit $exec :: (load (s32) from %stack.13, addrspace 5)
  ; CHECK-NEXT:   [[COPY475:%[0-9]+]]:vgpr_32 = COPY [[SI_SPILL_V32_RESTORE13]]
  ; CHECK-NEXT:   [[SI_SPILL_V32_RESTORE14:%[0-9]+]]:vgpr_32 = SI_SPILL_V32_RESTORE %stack.12, $sgpr32, 0, implicit $exec :: (load (s32) from %stack.12, addrspace 5)
  ; CHECK-NEXT:   [[COPY476:%[0-9]+]]:vgpr_32 = COPY [[SI_SPILL_V32_RESTORE14]]
  ; CHECK-NEXT:   [[REG_SEQUENCE68:%[0-9]+]]:vreg_128 = REG_SEQUENCE [[COPY476]], %subreg.sub0, [[COPY475]], %subreg.sub1, [[COPY474]], %subreg.sub2, [[COPY473]], %subreg.sub3
  ; CHECK-NEXT:   GLOBAL_STORE_DWORDX4 undef %808:vreg_64, [[REG_SEQUENCE68]], 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 48, addrspace 1)
  ; CHECK-NEXT:   [[SI_SPILL_V32_RESTORE15:%[0-9]+]]:vgpr_32 = SI_SPILL_V32_RESTORE %stack.11, $sgpr32, 0, implicit $exec :: (load (s32) from %stack.11, addrspace 5)
  ; CHECK-NEXT:   [[COPY477:%[0-9]+]]:vgpr_32 = COPY [[SI_SPILL_V32_RESTORE15]]
  ; CHECK-NEXT:   [[SI_SPILL_V32_RESTORE16:%[0-9]+]]:vgpr_32 = SI_SPILL_V32_RESTORE %stack.10, $sgpr32, 0, implicit $exec :: (load (s32) from %stack.10, addrspace 5)
  ; CHECK-NEXT:   [[COPY478:%[0-9]+]]:vgpr_32 = COPY [[SI_SPILL_V32_RESTORE16]]
  ; CHECK-NEXT:   [[SI_SPILL_V32_RESTORE17:%[0-9]+]]:vgpr_32 = SI_SPILL_V32_RESTORE %stack.9, $sgpr32, 0, implicit $exec :: (load (s32) from %stack.9, addrspace 5)
  ; CHECK-NEXT:   [[COPY479:%[0-9]+]]:vgpr_32 = COPY [[SI_SPILL_V32_RESTORE17]]
  ; CHECK-NEXT:   [[SI_SPILL_V32_RESTORE18:%[0-9]+]]:vgpr_32 = SI_SPILL_V32_RESTORE %stack.8, $sgpr32, 0, implicit $exec :: (load (s32) from %stack.8, addrspace 5)
  ; CHECK-NEXT:   [[COPY480:%[0-9]+]]:vgpr_32 = COPY [[SI_SPILL_V32_RESTORE18]]
  ; CHECK-NEXT:   [[REG_SEQUENCE69:%[0-9]+]]:vreg_128 = REG_SEQUENCE [[COPY480]], %subreg.sub0, [[COPY479]], %subreg.sub1, [[COPY478]], %subreg.sub2, [[COPY477]], %subreg.sub3
  ; CHECK-NEXT:   GLOBAL_STORE_DWORDX4 undef %816:vreg_64, [[REG_SEQUENCE69]], 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 32, align 32, addrspace 1)
  ; CHECK-NEXT:   [[SI_SPILL_V32_RESTORE19:%[0-9]+]]:vgpr_32 = SI_SPILL_V32_RESTORE %stack.7, $sgpr32, 0, implicit $exec :: (load (s32) from %stack.7, addrspace 5)
  ; CHECK-NEXT:   [[COPY481:%[0-9]+]]:vgpr_32 = COPY [[SI_SPILL_V32_RESTORE19]]
  ; CHECK-NEXT:   [[SI_SPILL_V32_RESTORE20:%[0-9]+]]:vgpr_32 = SI_SPILL_V32_RESTORE %stack.6, $sgpr32, 0, implicit $exec :: (load (s32) from %stack.6, addrspace 5)
  ; CHECK-NEXT:   [[COPY482:%[0-9]+]]:vgpr_32 = COPY [[SI_SPILL_V32_RESTORE20]]
  ; CHECK-NEXT:   [[SI_SPILL_V32_RESTORE21:%[0-9]+]]:vgpr_32 = SI_SPILL_V32_RESTORE %stack.5, $sgpr32, 0, implicit $exec :: (load (s32) from %stack.5, addrspace 5)
  ; CHECK-NEXT:   [[COPY483:%[0-9]+]]:vgpr_32 = COPY [[SI_SPILL_V32_RESTORE21]]
  ; CHECK-NEXT:   [[SI_SPILL_V32_RESTORE22:%[0-9]+]]:vgpr_32 = SI_SPILL_V32_RESTORE %stack.4, $sgpr32, 0, implicit $exec :: (load (s32) from %stack.4, addrspace 5)
  ; CHECK-NEXT:   [[COPY484:%[0-9]+]]:vgpr_32 = COPY [[SI_SPILL_V32_RESTORE22]]
  ; CHECK-NEXT:   [[REG_SEQUENCE70:%[0-9]+]]:vreg_128 = REG_SEQUENCE [[COPY484]], %subreg.sub0, [[COPY483]], %subreg.sub1, [[COPY482]], %subreg.sub2, [[COPY481]], %subreg.sub3
  ; CHECK-NEXT:   GLOBAL_STORE_DWORDX4 undef %824:vreg_64, [[REG_SEQUENCE70]], 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 16, addrspace 1)
  ; CHECK-NEXT:   [[SI_SPILL_V32_RESTORE23:%[0-9]+]]:vgpr_32 = SI_SPILL_V32_RESTORE %stack.3, $sgpr32, 0, implicit $exec :: (load (s32) from %stack.3, addrspace 5)
  ; CHECK-NEXT:   [[COPY485:%[0-9]+]]:vgpr_32 = COPY [[SI_SPILL_V32_RESTORE23]]
  ; CHECK-NEXT:   [[SI_SPILL_V32_RESTORE24:%[0-9]+]]:vgpr_32 = SI_SPILL_V32_RESTORE %stack.2, $sgpr32, 0, implicit $exec :: (load (s32) from %stack.2, addrspace 5)
  ; CHECK-NEXT:   [[COPY486:%[0-9]+]]:vgpr_32 = COPY [[SI_SPILL_V32_RESTORE24]]
  ; CHECK-NEXT:   [[SI_SPILL_V32_RESTORE25:%[0-9]+]]:vgpr_32 = SI_SPILL_V32_RESTORE %stack.1, $sgpr32, 0, implicit $exec :: (load (s32) from %stack.1, addrspace 5)
  ; CHECK-NEXT:   [[COPY487:%[0-9]+]]:vgpr_32 = COPY [[SI_SPILL_V32_RESTORE25]]
  ; CHECK-NEXT:   [[SI_SPILL_V32_RESTORE26:%[0-9]+]]:vgpr_32 = SI_SPILL_V32_RESTORE %stack.0, $sgpr32, 0, implicit $exec :: (load (s32) from %stack.0, addrspace 5)
  ; CHECK-NEXT:   [[COPY488:%[0-9]+]]:vgpr_32 = COPY [[SI_SPILL_V32_RESTORE26]]
  ; CHECK-NEXT:   [[REG_SEQUENCE71:%[0-9]+]]:vreg_128 = REG_SEQUENCE [[COPY488]], %subreg.sub0, [[COPY487]], %subreg.sub1, [[COPY486]], %subreg.sub2, [[COPY485]], %subreg.sub3
  ; CHECK-NEXT:   GLOBAL_STORE_DWORDX4 undef %832:vreg_64, [[REG_SEQUENCE71]], 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef`, align 128, addrspace 1)
  ; CHECK-NEXT:   [[COPY489:%[0-9]+]]:vgpr_32 = COPY [[COPY231]].sub31
  ; CHECK-NEXT:   [[COPY490:%[0-9]+]]:vgpr_32 = COPY [[COPY231]].sub30
  ; CHECK-NEXT:   [[SI_SPILL_V32_RESTORE27:%[0-9]+]]:vgpr_32 = SI_SPILL_V32_RESTORE %stack.56, $sgpr32, 0, implicit $exec :: (load (s32) from %stack.56, addrspace 5)
  ; CHECK-NEXT:   [[COPY491:%[0-9]+]]:vgpr_32 = COPY [[SI_SPILL_V32_RESTORE27]]
  ; CHECK-NEXT:   [[SI_SPILL_V32_RESTORE28:%[0-9]+]]:vgpr_32 = SI_SPILL_V32_RESTORE %stack.55, $sgpr32, 0, implicit $exec :: (load (s32) from %stack.55, addrspace 5)
  ; CHECK-NEXT:   [[COPY492:%[0-9]+]]:vgpr_32 = COPY [[SI_SPILL_V32_RESTORE28]]
  ; CHECK-NEXT:   [[REG_SEQUENCE72:%[0-9]+]]:vreg_128 = REG_SEQUENCE [[COPY492]], %subreg.sub0, [[COPY491]], %subreg.sub1, [[COPY490]], %subreg.sub2, [[COPY489]], %subreg.sub3
  ; CHECK-NEXT:   GLOBAL_STORE_DWORDX4 undef %840:vreg_64, [[REG_SEQUENCE72]], 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 112, addrspace 1)
  ; CHECK-NEXT:   [[SI_SPILL_V32_RESTORE29:%[0-9]+]]:vgpr_32 = SI_SPILL_V32_RESTORE %stack.54, $sgpr32, 0, implicit $exec :: (load (s32) from %stack.54, addrspace 5)
  ; CHECK-NEXT:   [[COPY493:%[0-9]+]]:vgpr_32 = COPY [[SI_SPILL_V32_RESTORE29]]
  ; CHECK-NEXT:   [[SI_SPILL_V32_RESTORE30:%[0-9]+]]:vgpr_32 = SI_SPILL_V32_RESTORE %stack.53, $sgpr32, 0, implicit $exec :: (load (s32) from %stack.53, addrspace 5)
  ; CHECK-NEXT:   [[COPY494:%[0-9]+]]:vgpr_32 = COPY [[SI_SPILL_V32_RESTORE30]]
  ; CHECK-NEXT:   [[SI_SPILL_V32_RESTORE31:%[0-9]+]]:vgpr_32 = SI_SPILL_V32_RESTORE %stack.52, $sgpr32, 0, implicit $exec :: (load (s32) from %stack.52, addrspace 5)
  ; CHECK-NEXT:   [[COPY495:%[0-9]+]]:vgpr_32 = COPY [[SI_SPILL_V32_RESTORE31]]
  ; CHECK-NEXT:   [[SI_SPILL_V32_RESTORE32:%[0-9]+]]:vgpr_32 = SI_SPILL_V32_RESTORE %stack.51, $sgpr32, 0, implicit $exec :: (load (s32) from %stack.51, addrspace 5)
  ; CHECK-NEXT:   [[COPY496:%[0-9]+]]:vgpr_32 = COPY [[SI_SPILL_V32_RESTORE32]]
  ; CHECK-NEXT:   [[REG_SEQUENCE73:%[0-9]+]]:vreg_128 = REG_SEQUENCE [[COPY496]], %subreg.sub0, [[COPY495]], %subreg.sub1, [[COPY494]], %subreg.sub2, [[COPY493]], %subreg.sub3
  ; CHECK-NEXT:   GLOBAL_STORE_DWORDX4 undef %848:vreg_64, [[REG_SEQUENCE73]], 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 96, align 32, addrspace 1)
  ; CHECK-NEXT:   [[SI_SPILL_V32_RESTORE33:%[0-9]+]]:vgpr_32 = SI_SPILL_V32_RESTORE %stack.50, $sgpr32, 0, implicit $exec :: (load (s32) from %stack.50, addrspace 5)
  ; CHECK-NEXT:   [[COPY497:%[0-9]+]]:vgpr_32 = COPY [[SI_SPILL_V32_RESTORE33]]
  ; CHECK-NEXT:   [[SI_SPILL_V32_RESTORE34:%[0-9]+]]:vgpr_32 = SI_SPILL_V32_RESTORE %stack.49, $sgpr32, 0, implicit $exec :: (load (s32) from %stack.49, addrspace 5)
  ; CHECK-NEXT:   [[COPY498:%[0-9]+]]:vgpr_32 = COPY [[SI_SPILL_V32_RESTORE34]]
  ; CHECK-NEXT:   [[SI_SPILL_V32_RESTORE35:%[0-9]+]]:vgpr_32 = SI_SPILL_V32_RESTORE %stack.48, $sgpr32, 0, implicit $exec :: (load (s32) from %stack.48, addrspace 5)
  ; CHECK-NEXT:   [[COPY499:%[0-9]+]]:vgpr_32 = COPY [[SI_SPILL_V32_RESTORE35]]
  ; CHECK-NEXT:   [[SI_SPILL_V32_RESTORE36:%[0-9]+]]:vgpr_32 = SI_SPILL_V32_RESTORE %stack.47, $sgpr32, 0, implicit $exec :: (load (s32) from %stack.47, addrspace 5)
  ; CHECK-NEXT:   [[COPY500:%[0-9]+]]:vgpr_32 = COPY [[SI_SPILL_V32_RESTORE36]]
  ; CHECK-NEXT:   [[REG_SEQUENCE74:%[0-9]+]]:vreg_128 = REG_SEQUENCE [[COPY500]], %subreg.sub0, [[COPY499]], %subreg.sub1, [[COPY498]], %subreg.sub2, [[COPY497]], %subreg.sub3
  ; CHECK-NEXT:   GLOBAL_STORE_DWORDX4 undef %856:vreg_64, [[REG_SEQUENCE74]], 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 80, addrspace 1)
  ; CHECK-NEXT:   [[SI_SPILL_V32_RESTORE37:%[0-9]+]]:vgpr_32 = SI_SPILL_V32_RESTORE %stack.46, $sgpr32, 0, implicit $exec :: (load (s32) from %stack.46, addrspace 5)
  ; CHECK-NEXT:   [[COPY501:%[0-9]+]]:vgpr_32 = COPY [[SI_SPILL_V32_RESTORE37]]
  ; CHECK-NEXT:   [[SI_SPILL_V32_RESTORE38:%[0-9]+]]:vgpr_32 = SI_SPILL_V32_RESTORE %stack.45, $sgpr32, 0, implicit $exec :: (load (s32) from %stack.45, addrspace 5)
  ; CHECK-NEXT:   [[COPY502:%[0-9]+]]:vgpr_32 = COPY [[SI_SPILL_V32_RESTORE38]]
  ; CHECK-NEXT:   [[SI_SPILL_V32_RESTORE39:%[0-9]+]]:vgpr_32 = SI_SPILL_V32_RESTORE %stack.44, $sgpr32, 0, implicit $exec :: (load (s32) from %stack.44, addrspace 5)
  ; CHECK-NEXT:   [[COPY503:%[0-9]+]]:vgpr_32 = COPY [[SI_SPILL_V32_RESTORE39]]
  ; CHECK-NEXT:   [[SI_SPILL_V32_RESTORE40:%[0-9]+]]:vgpr_32 = SI_SPILL_V32_RESTORE %stack.43, $sgpr32, 0, implicit $exec :: (load (s32) from %stack.43, addrspace 5)
  ; CHECK-NEXT:   [[COPY504:%[0-9]+]]:vgpr_32 = COPY [[SI_SPILL_V32_RESTORE40]]
  ; CHECK-NEXT:   [[REG_SEQUENCE75:%[0-9]+]]:vreg_128 = REG_SEQUENCE [[COPY504]], %subreg.sub0, [[COPY503]], %subreg.sub1, [[COPY502]], %subreg.sub2, [[COPY501]], %subreg.sub3
  ; CHECK-NEXT:   GLOBAL_STORE_DWORDX4 undef %864:vreg_64, [[REG_SEQUENCE75]], 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 64, align 64, addrspace 1)
  ; CHECK-NEXT:   [[SI_SPILL_V32_RESTORE41:%[0-9]+]]:vgpr_32 = SI_SPILL_V32_RESTORE %stack.42, $sgpr32, 0, implicit $exec :: (load (s32) from %stack.42, addrspace 5)
  ; CHECK-NEXT:   [[COPY505:%[0-9]+]]:vgpr_32 = COPY [[SI_SPILL_V32_RESTORE41]]
  ; CHECK-NEXT:   [[SI_SPILL_V32_RESTORE42:%[0-9]+]]:vgpr_32 = SI_SPILL_V32_RESTORE %stack.41, $sgpr32, 0, implicit $exec :: (load (s32) from %stack.41, addrspace 5)
  ; CHECK-NEXT:   [[COPY506:%[0-9]+]]:vgpr_32 = COPY [[SI_SPILL_V32_RESTORE42]]
  ; CHECK-NEXT:   [[SI_SPILL_V32_RESTORE43:%[0-9]+]]:vgpr_32 = SI_SPILL_V32_RESTORE %stack.40, $sgpr32, 0, implicit $exec :: (load (s32) from %stack.40, addrspace 5)
  ; CHECK-NEXT:   [[COPY507:%[0-9]+]]:vgpr_32 = COPY [[SI_SPILL_V32_RESTORE43]]
  ; CHECK-NEXT:   [[SI_SPILL_V32_RESTORE44:%[0-9]+]]:vgpr_32 = SI_SPILL_V32_RESTORE %stack.39, $sgpr32, 0, implicit $exec :: (load (s32) from %stack.39, addrspace 5)
  ; CHECK-NEXT:   [[COPY508:%[0-9]+]]:vgpr_32 = COPY [[SI_SPILL_V32_RESTORE44]]
  ; CHECK-NEXT:   [[REG_SEQUENCE76:%[0-9]+]]:vreg_128 = REG_SEQUENCE [[COPY508]], %subreg.sub0, [[COPY507]], %subreg.sub1, [[COPY506]], %subreg.sub2, [[COPY505]], %subreg.sub3
  ; CHECK-NEXT:   GLOBAL_STORE_DWORDX4 undef %872:vreg_64, [[REG_SEQUENCE76]], 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 48, addrspace 1)
  ; CHECK-NEXT:   [[SI_SPILL_V32_RESTORE45:%[0-9]+]]:vgpr_32 = SI_SPILL_V32_RESTORE %stack.38, $sgpr32, 0, implicit $exec :: (load (s32) from %stack.38, addrspace 5)
  ; CHECK-NEXT:   [[COPY509:%[0-9]+]]:vgpr_32 = COPY [[SI_SPILL_V32_RESTORE45]]
  ; CHECK-NEXT:   [[SI_SPILL_V32_RESTORE46:%[0-9]+]]:vgpr_32 = SI_SPILL_V32_RESTORE %stack.37, $sgpr32, 0, implicit $exec :: (load (s32) from %stack.37, addrspace 5)
  ; CHECK-NEXT:   [[COPY510:%[0-9]+]]:vgpr_32 = COPY [[SI_SPILL_V32_RESTORE46]]
  ; CHECK-NEXT:   [[SI_SPILL_V32_RESTORE47:%[0-9]+]]:vgpr_32 = SI_SPILL_V32_RESTORE %stack.36, $sgpr32, 0, implicit $exec :: (load (s32) from %stack.36, addrspace 5)
  ; CHECK-NEXT:   [[COPY511:%[0-9]+]]:vgpr_32 = COPY [[SI_SPILL_V32_RESTORE47]]
  ; CHECK-NEXT:   [[SI_SPILL_V32_RESTORE48:%[0-9]+]]:vgpr_32 = SI_SPILL_V32_RESTORE %stack.35, $sgpr32, 0, implicit $exec :: (load (s32) from %stack.35, addrspace 5)
  ; CHECK-NEXT:   [[COPY512:%[0-9]+]]:vgpr_32 = COPY [[SI_SPILL_V32_RESTORE48]]
  ; CHECK-NEXT:   [[REG_SEQUENCE77:%[0-9]+]]:vreg_128 = REG_SEQUENCE [[COPY512]], %subreg.sub0, [[COPY511]], %subreg.sub1, [[COPY510]], %subreg.sub2, [[COPY509]], %subreg.sub3
  ; CHECK-NEXT:   GLOBAL_STORE_DWORDX4 undef %880:vreg_64, [[REG_SEQUENCE77]], 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 32, align 32, addrspace 1)
  ; CHECK-NEXT:   [[SI_SPILL_V32_RESTORE49:%[0-9]+]]:vgpr_32 = SI_SPILL_V32_RESTORE %stack.34, $sgpr32, 0, implicit $exec :: (load (s32) from %stack.34, addrspace 5)
  ; CHECK-NEXT:   [[COPY513:%[0-9]+]]:vgpr_32 = COPY [[SI_SPILL_V32_RESTORE49]]
  ; CHECK-NEXT:   [[SI_SPILL_V32_RESTORE50:%[0-9]+]]:vgpr_32 = SI_SPILL_V32_RESTORE %stack.33, $sgpr32, 0, implicit $exec :: (load (s32) from %stack.33, addrspace 5)
  ; CHECK-NEXT:   [[COPY514:%[0-9]+]]:vgpr_32 = COPY [[SI_SPILL_V32_RESTORE50]]
  ; CHECK-NEXT:   [[SI_SPILL_V32_RESTORE51:%[0-9]+]]:vgpr_32 = SI_SPILL_V32_RESTORE %stack.32, $sgpr32, 0, implicit $exec :: (load (s32) from %stack.32, addrspace 5)
  ; CHECK-NEXT:   [[COPY515:%[0-9]+]]:vgpr_32 = COPY [[SI_SPILL_V32_RESTORE51]]
  ; CHECK-NEXT:   [[SI_SPILL_V32_RESTORE52:%[0-9]+]]:vgpr_32 = SI_SPILL_V32_RESTORE %stack.31, $sgpr32, 0, implicit $exec :: (load (s32) from %stack.31, addrspace 5)
  ; CHECK-NEXT:   [[COPY516:%[0-9]+]]:vgpr_32 = COPY [[SI_SPILL_V32_RESTORE52]]
  ; CHECK-NEXT:   [[REG_SEQUENCE78:%[0-9]+]]:vreg_128 = REG_SEQUENCE [[COPY516]], %subreg.sub0, [[COPY515]], %subreg.sub1, [[COPY514]], %subreg.sub2, [[COPY513]], %subreg.sub3
  ; CHECK-NEXT:   GLOBAL_STORE_DWORDX4 undef %888:vreg_64, [[REG_SEQUENCE78]], 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 16, addrspace 1)
  ; CHECK-NEXT:   [[SI_SPILL_V32_RESTORE53:%[0-9]+]]:vgpr_32 = SI_SPILL_V32_RESTORE %stack.30, $sgpr32, 0, implicit $exec :: (load (s32) from %stack.30, addrspace 5)
  ; CHECK-NEXT:   [[COPY517:%[0-9]+]]:vgpr_32 = COPY [[SI_SPILL_V32_RESTORE53]]
  ; CHECK-NEXT:   [[SI_SPILL_V32_RESTORE54:%[0-9]+]]:vgpr_32 = SI_SPILL_V32_RESTORE %stack.29, $sgpr32, 0, implicit $exec :: (load (s32) from %stack.29, addrspace 5)
  ; CHECK-NEXT:   [[COPY518:%[0-9]+]]:vgpr_32 = COPY [[SI_SPILL_V32_RESTORE54]]
  ; CHECK-NEXT:   [[SI_SPILL_V32_RESTORE55:%[0-9]+]]:vgpr_32 = SI_SPILL_V32_RESTORE %stack.28, $sgpr32, 0, implicit $exec :: (load (s32) from %stack.28, addrspace 5)
  ; CHECK-NEXT:   [[COPY519:%[0-9]+]]:vgpr_32 = COPY [[SI_SPILL_V32_RESTORE55]]
  ; CHECK-NEXT:   [[SI_SPILL_V32_RESTORE56:%[0-9]+]]:vgpr_32 = SI_SPILL_V32_RESTORE %stack.27, $sgpr32, 0, implicit $exec :: (load (s32) from %stack.27, addrspace 5)
  ; CHECK-NEXT:   [[COPY520:%[0-9]+]]:vgpr_32 = COPY [[SI_SPILL_V32_RESTORE56]]
  ; CHECK-NEXT:   [[REG_SEQUENCE79:%[0-9]+]]:vreg_128 = REG_SEQUENCE [[COPY520]], %subreg.sub0, [[COPY519]], %subreg.sub1, [[COPY518]], %subreg.sub2, [[COPY517]], %subreg.sub3
  ; CHECK-NEXT:   GLOBAL_STORE_DWORDX4 undef %896:vreg_64, [[REG_SEQUENCE79]], 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef`, align 128, addrspace 1)
  ; CHECK-NEXT:   [[COPY521:%[0-9]+]]:vgpr_32 = COPY [[COPY264]].sub31
  ; CHECK-NEXT:   [[COPY522:%[0-9]+]]:vgpr_32 = COPY [[COPY264]].sub30
  ; CHECK-NEXT:   [[COPY523:%[0-9]+]]:vgpr_32 = COPY [[COPY264]].sub29
  ; CHECK-NEXT:   [[COPY524:%[0-9]+]]:vgpr_32 = COPY [[COPY264]].sub28
  ; CHECK-NEXT:   [[REG_SEQUENCE80:%[0-9]+]]:vreg_128 = REG_SEQUENCE [[COPY524]], %subreg.sub0, [[COPY523]], %subreg.sub1, [[COPY522]], %subreg.sub2, [[COPY521]], %subreg.sub3
  ; CHECK-NEXT:   GLOBAL_STORE_DWORDX4 undef %904:vreg_64, [[REG_SEQUENCE80]], 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 112, addrspace 1)
  ; CHECK-NEXT:   [[COPY525:%[0-9]+]]:vgpr_32 = COPY [[COPY264]].sub27
  ; CHECK-NEXT:   [[COPY526:%[0-9]+]]:vgpr_32 = COPY [[COPY264]].sub26
  ; CHECK-NEXT:   [[COPY527:%[0-9]+]]:vgpr_32 = COPY [[COPY264]].sub25
  ; CHECK-NEXT:   [[COPY528:%[0-9]+]]:vgpr_32 = COPY [[COPY264]].sub24
  ; CHECK-NEXT:   [[REG_SEQUENCE81:%[0-9]+]]:vreg_128 = REG_SEQUENCE [[COPY528]], %subreg.sub0, [[COPY527]], %subreg.sub1, [[COPY526]], %subreg.sub2, [[COPY525]], %subreg.sub3
  ; CHECK-NEXT:   GLOBAL_STORE_DWORDX4 undef %912:vreg_64, [[REG_SEQUENCE81]], 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 96, align 32, addrspace 1)
  ; CHECK-NEXT:   [[COPY529:%[0-9]+]]:vgpr_32 = COPY [[COPY264]].sub23
  ; CHECK-NEXT:   [[COPY530:%[0-9]+]]:vgpr_32 = COPY [[COPY264]].sub22
  ; CHECK-NEXT:   [[COPY531:%[0-9]+]]:vgpr_32 = COPY [[COPY264]].sub21
  ; CHECK-NEXT:   [[COPY532:%[0-9]+]]:vgpr_32 = COPY [[COPY264]].sub20
  ; CHECK-NEXT:   [[REG_SEQUENCE82:%[0-9]+]]:vreg_128 = REG_SEQUENCE [[COPY532]], %subreg.sub0, [[COPY531]], %subreg.sub1, [[COPY530]], %subreg.sub2, [[COPY529]], %subreg.sub3
  ; CHECK-NEXT:   GLOBAL_STORE_DWORDX4 undef %920:vreg_64, [[REG_SEQUENCE82]], 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 80, addrspace 1)
  ; CHECK-NEXT:   [[COPY533:%[0-9]+]]:vgpr_32 = COPY [[COPY264]].sub19
  ; CHECK-NEXT:   [[COPY534:%[0-9]+]]:vgpr_32 = COPY [[COPY264]].sub18
  ; CHECK-NEXT:   [[COPY535:%[0-9]+]]:vgpr_32 = COPY [[COPY264]].sub17
  ; CHECK-NEXT:   [[COPY536:%[0-9]+]]:vgpr_32 = COPY [[COPY264]].sub16
  ; CHECK-NEXT:   [[REG_SEQUENCE83:%[0-9]+]]:vreg_128 = REG_SEQUENCE [[COPY536]], %subreg.sub0, [[COPY535]], %subreg.sub1, [[COPY534]], %subreg.sub2, [[COPY533]], %subreg.sub3
  ; CHECK-NEXT:   GLOBAL_STORE_DWORDX4 undef %928:vreg_64, [[REG_SEQUENCE83]], 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 64, align 64, addrspace 1)
  ; CHECK-NEXT:   [[COPY537:%[0-9]+]]:vgpr_32 = COPY [[COPY264]].sub15
  ; CHECK-NEXT:   [[COPY538:%[0-9]+]]:vgpr_32 = COPY [[COPY264]].sub14
  ; CHECK-NEXT:   [[COPY539:%[0-9]+]]:vgpr_32 = COPY [[COPY264]].sub13
  ; CHECK-NEXT:   [[COPY540:%[0-9]+]]:vgpr_32 = COPY [[COPY264]].sub12
  ; CHECK-NEXT:   [[REG_SEQUENCE84:%[0-9]+]]:vreg_128 = REG_SEQUENCE [[COPY540]], %subreg.sub0, [[COPY539]], %subreg.sub1, [[COPY538]], %subreg.sub2, [[COPY537]], %subreg.sub3
  ; CHECK-NEXT:   GLOBAL_STORE_DWORDX4 undef %936:vreg_64, [[REG_SEQUENCE84]], 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 48, addrspace 1)
  ; CHECK-NEXT:   [[COPY541:%[0-9]+]]:vgpr_32 = COPY [[COPY264]].sub11
  ; CHECK-NEXT:   [[COPY542:%[0-9]+]]:vgpr_32 = COPY [[COPY264]].sub10
  ; CHECK-NEXT:   [[COPY543:%[0-9]+]]:vgpr_32 = COPY [[COPY264]].sub9
  ; CHECK-NEXT:   [[COPY544:%[0-9]+]]:vgpr_32 = COPY [[COPY264]].sub8
  ; CHECK-NEXT:   [[REG_SEQUENCE85:%[0-9]+]]:vreg_128 = REG_SEQUENCE [[COPY544]], %subreg.sub0, [[COPY543]], %subreg.sub1, [[COPY542]], %subreg.sub2, [[COPY541]], %subreg.sub3
  ; CHECK-NEXT:   GLOBAL_STORE_DWORDX4 undef %944:vreg_64, [[REG_SEQUENCE85]], 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 32, align 32, addrspace 1)
  ; CHECK-NEXT:   [[COPY545:%[0-9]+]]:vgpr_32 = COPY [[COPY264]].sub7
  ; CHECK-NEXT:   [[COPY546:%[0-9]+]]:vgpr_32 = COPY [[COPY264]].sub6
  ; CHECK-NEXT:   [[COPY547:%[0-9]+]]:vgpr_32 = COPY [[COPY264]].sub5
  ; CHECK-NEXT:   [[COPY548:%[0-9]+]]:vgpr_32 = COPY [[COPY264]].sub4
  ; CHECK-NEXT:   [[REG_SEQUENCE86:%[0-9]+]]:vreg_128 = REG_SEQUENCE [[COPY548]], %subreg.sub0, [[COPY547]], %subreg.sub1, [[COPY546]], %subreg.sub2, [[COPY545]], %subreg.sub3
  ; CHECK-NEXT:   GLOBAL_STORE_DWORDX4 undef %952:vreg_64, [[REG_SEQUENCE86]], 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 16, addrspace 1)
  ; CHECK-NEXT:   [[COPY549:%[0-9]+]]:vgpr_32 = COPY [[COPY264]].sub3
  ; CHECK-NEXT:   [[COPY550:%[0-9]+]]:vgpr_32 = COPY [[COPY264]].sub2
  ; CHECK-NEXT:   [[COPY551:%[0-9]+]]:vgpr_32 = COPY [[COPY264]].sub1
  ; CHECK-NEXT:   [[COPY552:%[0-9]+]]:vgpr_32 = COPY [[COPY264]].sub0
  ; CHECK-NEXT:   [[REG_SEQUENCE87:%[0-9]+]]:vreg_128 = REG_SEQUENCE [[COPY552]], %subreg.sub0, [[COPY551]], %subreg.sub1, [[COPY550]], %subreg.sub2, [[COPY549]], %subreg.sub3
  ; CHECK-NEXT:   GLOBAL_STORE_DWORDX4 undef %960:vreg_64, [[REG_SEQUENCE87]], 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef`, align 128, addrspace 1)
  ; CHECK-NEXT:   SI_RETURN
  bb.0 (%ir-block.0):
    successors: %bb.1(0x80000000)
    liveins: $vgpr0, $vgpr1, $vgpr2, $vgpr3, $vgpr4, $vgpr5, $vgpr6, $vgpr7, $vgpr8, $vgpr9, $vgpr10, $vgpr11, $vgpr12, $vgpr13, $vgpr14, $vgpr15, $vgpr16, $vgpr17, $vgpr18, $vgpr19, $vgpr20, $vgpr21, $vgpr22, $vgpr23, $vgpr24, $vgpr25, $vgpr26, $vgpr27, $vgpr28, $vgpr29, $vgpr30, $vgpr31

    %47:vgpr_32 = COPY $vgpr31
    %44:vgpr_32 = COPY $vgpr30
    %43:vgpr_32 = COPY $vgpr29
    %42:vgpr_32 = COPY $vgpr28
    %41:vgpr_32 = COPY $vgpr27
    %40:vgpr_32 = COPY $vgpr26
    %39:vgpr_32 = COPY $vgpr25
    %38:vgpr_32 = COPY $vgpr24
    %37:vgpr_32 = COPY $vgpr23
    %36:vgpr_32 = COPY $vgpr22
    %35:vgpr_32 = COPY $vgpr21
    %34:vgpr_32 = COPY $vgpr20
    %33:vgpr_32 = COPY $vgpr19
    %32:vgpr_32 = COPY $vgpr18
    %31:vgpr_32 = COPY $vgpr17
    %30:vgpr_32 = COPY $vgpr16
    %29:vgpr_32 = COPY $vgpr15
    %28:vgpr_32 = COPY $vgpr14
    %27:vgpr_32 = COPY $vgpr13
    %26:vgpr_32 = COPY $vgpr12
    %25:vgpr_32 = COPY $vgpr11
    %24:vgpr_32 = COPY $vgpr10
    %23:vgpr_32 = COPY $vgpr9
    %22:vgpr_32 = COPY $vgpr8
    %21:vgpr_32 = COPY $vgpr7
    %20:vgpr_32 = COPY $vgpr6
    %19:vgpr_32 = COPY $vgpr5
    %18:vgpr_32 = COPY $vgpr4
    %17:vgpr_32 = COPY $vgpr3
    %16:vgpr_32 = COPY $vgpr2
    %15:vgpr_32 = COPY $vgpr1
    %14:vgpr_32 = COPY $vgpr0
    %48:vgpr_32 = BUFFER_LOAD_DWORD_OFFEN %fixed-stack.32, $sgpr0_sgpr1_sgpr2_sgpr3, 0, 0, 0, 0, implicit $exec :: (load (s32) from %fixed-stack.32, align 16, addrspace 5)
    %49:vgpr_32 = BUFFER_LOAD_DWORD_OFFEN %fixed-stack.31, $sgpr0_sgpr1_sgpr2_sgpr3, 0, 0, 0, 0, implicit $exec :: (load (s32) from %fixed-stack.31, addrspace 5)
    %50:vgpr_32 = BUFFER_LOAD_DWORD_OFFEN %fixed-stack.30, $sgpr0_sgpr1_sgpr2_sgpr3, 0, 0, 0, 0, implicit $exec :: (load (s32) from %fixed-stack.30, align 8, addrspace 5)
    %51:vgpr_32 = BUFFER_LOAD_DWORD_OFFEN %fixed-stack.29, $sgpr0_sgpr1_sgpr2_sgpr3, 0, 0, 0, 0, implicit $exec :: (load (s32) from %fixed-stack.29, addrspace 5)
    %52:vgpr_32 = BUFFER_LOAD_DWORD_OFFEN %fixed-stack.28, $sgpr0_sgpr1_sgpr2_sgpr3, 0, 0, 0, 0, implicit $exec :: (load (s32) from %fixed-stack.28, align 16, addrspace 5)
    %53:vgpr_32 = BUFFER_LOAD_DWORD_OFFEN %fixed-stack.27, $sgpr0_sgpr1_sgpr2_sgpr3, 0, 0, 0, 0, implicit $exec :: (load (s32) from %fixed-stack.27, addrspace 5)
    %54:vgpr_32 = BUFFER_LOAD_DWORD_OFFEN %fixed-stack.26, $sgpr0_sgpr1_sgpr2_sgpr3, 0, 0, 0, 0, implicit $exec :: (load (s32) from %fixed-stack.26, align 8, addrspace 5)
    %55:vgpr_32 = BUFFER_LOAD_DWORD_OFFEN %fixed-stack.25, $sgpr0_sgpr1_sgpr2_sgpr3, 0, 0, 0, 0, implicit $exec :: (load (s32) from %fixed-stack.25, addrspace 5)
    %56:vgpr_32 = BUFFER_LOAD_DWORD_OFFEN %fixed-stack.24, $sgpr0_sgpr1_sgpr2_sgpr3, 0, 0, 0, 0, implicit $exec :: (load (s32) from %fixed-stack.24, align 16, addrspace 5)
    %57:vgpr_32 = BUFFER_LOAD_DWORD_OFFEN %fixed-stack.23, $sgpr0_sgpr1_sgpr2_sgpr3, 0, 0, 0, 0, implicit $exec :: (load (s32) from %fixed-stack.23, addrspace 5)
    %58:vgpr_32 = BUFFER_LOAD_DWORD_OFFEN %fixed-stack.22, $sgpr0_sgpr1_sgpr2_sgpr3, 0, 0, 0, 0, implicit $exec :: (load (s32) from %fixed-stack.22, align 8, addrspace 5)
    %59:vgpr_32 = BUFFER_LOAD_DWORD_OFFEN %fixed-stack.21, $sgpr0_sgpr1_sgpr2_sgpr3, 0, 0, 0, 0, implicit $exec :: (load (s32) from %fixed-stack.21, addrspace 5)
    %60:vgpr_32 = BUFFER_LOAD_DWORD_OFFEN %fixed-stack.20, $sgpr0_sgpr1_sgpr2_sgpr3, 0, 0, 0, 0, implicit $exec :: (load (s32) from %fixed-stack.20, align 16, addrspace 5)
    %61:vgpr_32 = BUFFER_LOAD_DWORD_OFFEN %fixed-stack.19, $sgpr0_sgpr1_sgpr2_sgpr3, 0, 0, 0, 0, implicit $exec :: (load (s32) from %fixed-stack.19, addrspace 5)
    %62:vgpr_32 = BUFFER_LOAD_DWORD_OFFEN %fixed-stack.18, $sgpr0_sgpr1_sgpr2_sgpr3, 0, 0, 0, 0, implicit $exec :: (load (s32) from %fixed-stack.18, align 8, addrspace 5)
    %63:vgpr_32 = BUFFER_LOAD_DWORD_OFFEN %fixed-stack.17, $sgpr0_sgpr1_sgpr2_sgpr3, 0, 0, 0, 0, implicit $exec :: (load (s32) from %fixed-stack.17, addrspace 5)
    %64:vgpr_32 = BUFFER_LOAD_DWORD_OFFEN %fixed-stack.16, $sgpr0_sgpr1_sgpr2_sgpr3, 0, 0, 0, 0, implicit $exec :: (load (s32) from %fixed-stack.16, align 16, addrspace 5)
    %65:vgpr_32 = BUFFER_LOAD_DWORD_OFFEN %fixed-stack.15, $sgpr0_sgpr1_sgpr2_sgpr3, 0, 0, 0, 0, implicit $exec :: (load (s32) from %fixed-stack.15, addrspace 5)
    %66:vgpr_32 = BUFFER_LOAD_DWORD_OFFEN %fixed-stack.14, $sgpr0_sgpr1_sgpr2_sgpr3, 0, 0, 0, 0, implicit $exec :: (load (s32) from %fixed-stack.14, align 8, addrspace 5)
    %67:vgpr_32 = BUFFER_LOAD_DWORD_OFFEN %fixed-stack.13, $sgpr0_sgpr1_sgpr2_sgpr3, 0, 0, 0, 0, implicit $exec :: (load (s32) from %fixed-stack.13, addrspace 5)
    %68:vgpr_32 = BUFFER_LOAD_DWORD_OFFEN %fixed-stack.12, $sgpr0_sgpr1_sgpr2_sgpr3, 0, 0, 0, 0, implicit $exec :: (load (s32) from %fixed-stack.12, align 16, addrspace 5)
    %69:vgpr_32 = BUFFER_LOAD_DWORD_OFFEN %fixed-stack.11, $sgpr0_sgpr1_sgpr2_sgpr3, 0, 0, 0, 0, implicit $exec :: (load (s32) from %fixed-stack.11, addrspace 5)
    %70:vgpr_32 = BUFFER_LOAD_DWORD_OFFEN %fixed-stack.10, $sgpr0_sgpr1_sgpr2_sgpr3, 0, 0, 0, 0, implicit $exec :: (load (s32) from %fixed-stack.10, align 8, addrspace 5)
    %71:vgpr_32 = BUFFER_LOAD_DWORD_OFFEN %fixed-stack.9, $sgpr0_sgpr1_sgpr2_sgpr3, 0, 0, 0, 0, implicit $exec :: (load (s32) from %fixed-stack.9, addrspace 5)
    %72:vgpr_32 = BUFFER_LOAD_DWORD_OFFEN %fixed-stack.8, $sgpr0_sgpr1_sgpr2_sgpr3, 0, 0, 0, 0, implicit $exec :: (load (s32) from %fixed-stack.8, align 16, addrspace 5)
    %73:vgpr_32 = BUFFER_LOAD_DWORD_OFFEN %fixed-stack.7, $sgpr0_sgpr1_sgpr2_sgpr3, 0, 0, 0, 0, implicit $exec :: (load (s32) from %fixed-stack.7, addrspace 5)
    %74:vgpr_32 = BUFFER_LOAD_DWORD_OFFEN %fixed-stack.6, $sgpr0_sgpr1_sgpr2_sgpr3, 0, 0, 0, 0, implicit $exec :: (load (s32) from %fixed-stack.6, align 8, addrspace 5)
    %75:vgpr_32 = BUFFER_LOAD_DWORD_OFFEN %fixed-stack.5, $sgpr0_sgpr1_sgpr2_sgpr3, 0, 0, 0, 0, implicit $exec :: (load (s32) from %fixed-stack.5, addrspace 5)
    %76:vgpr_32 = BUFFER_LOAD_DWORD_OFFEN %fixed-stack.4, $sgpr0_sgpr1_sgpr2_sgpr3, 0, 0, 0, 0, implicit $exec :: (load (s32) from %fixed-stack.4, align 16, addrspace 5)
    %77:vgpr_32 = BUFFER_LOAD_DWORD_OFFEN %fixed-stack.3, $sgpr0_sgpr1_sgpr2_sgpr3, 0, 0, 0, 0, implicit $exec :: (load (s32) from %fixed-stack.3, addrspace 5)
    %78:vgpr_32 = BUFFER_LOAD_DWORD_OFFEN %fixed-stack.2, $sgpr0_sgpr1_sgpr2_sgpr3, 0, 0, 0, 0, implicit $exec :: (load (s32) from %fixed-stack.2, align 8, addrspace 5)
    %79:vgpr_32 = BUFFER_LOAD_DWORD_OFFEN %fixed-stack.1, $sgpr0_sgpr1_sgpr2_sgpr3, 0, 0, 0, 0, implicit $exec :: (load (s32) from %fixed-stack.1, addrspace 5)
    %1624:vreg_1024 = REG_SEQUENCE %79, %subreg.sub0, %78, %subreg.sub1, %77, %subreg.sub2, %76, %subreg.sub3, %75, %subreg.sub4, %74, %subreg.sub5, %73, %subreg.sub6, %72, %subreg.sub7, %71, %subreg.sub8, %70, %subreg.sub9, %69, %subreg.sub10, %68, %subreg.sub11, %67, %subreg.sub12, %66, %subreg.sub13, %65, %subreg.sub14, %64, %subreg.sub15, %63, %subreg.sub16, %62, %subreg.sub17, %61, %subreg.sub18, %60, %subreg.sub19, %59, %subreg.sub20, %58, %subreg.sub21, %57, %subreg.sub22, %56, %subreg.sub23, %55, %subreg.sub24, %54, %subreg.sub25, %53, %subreg.sub26, %52, %subreg.sub27, %51, %subreg.sub28, %50, %subreg.sub29, %49, %subreg.sub30, %48, %subreg.sub31
    %81:vgpr_32 = BUFFER_LOAD_DWORD_OFFEN %fixed-stack.0, $sgpr0_sgpr1_sgpr2_sgpr3, 0, 0, 0, 0, implicit $exec :: (load (s32) from %fixed-stack.0, align 16, addrspace 5)
    %1623:vreg_1024 = REG_SEQUENCE %14, %subreg.sub0, %15, %subreg.sub1, %16, %subreg.sub2, %17, %subreg.sub3, %18, %subreg.sub4, %19, %subreg.sub5, %20, %subreg.sub6, %21, %subreg.sub7, %22, %subreg.sub8, %23, %subreg.sub9, %24, %subreg.sub10, %25, %subreg.sub11, %26, %subreg.sub12, %27, %subreg.sub13, %28, %subreg.sub14, %29, %subreg.sub15, %30, %subreg.sub16, %31, %subreg.sub17, %32, %subreg.sub18, %33, %subreg.sub19, %34, %subreg.sub20, %35, %subreg.sub21, %36, %subreg.sub22, %37, %subreg.sub23, %38, %subreg.sub24, %39, %subreg.sub25, %40, %subreg.sub26, %41, %subreg.sub27, %42, %subreg.sub28, %43, %subreg.sub29, %44, %subreg.sub30, %81, %subreg.sub31
    %83:vgpr_32 = BUFFER_LOAD_DWORD_OFFEN %fixed-stack.34, $sgpr0_sgpr1_sgpr2_sgpr3, 0, 0, 0, 0, implicit $exec :: (load (s32) from %fixed-stack.34, align 8, addrspace 5)
    %84:vgpr_32 = BUFFER_LOAD_DWORD_OFFEN %fixed-stack.33, $sgpr0_sgpr1_sgpr2_sgpr3, 0, 0, 0, 0, implicit $exec :: (load (s32) from %fixed-stack.33, addrspace 5)
    %46:vreg_1024 = COPY %1624
    %45:vreg_1024 = COPY %1623
    %87:vgpr_32 = V_AND_B32_e32 1023, %47, implicit $exec
    %89:vgpr_32 = nuw nsw V_LSHLREV_B32_e32 7, %87, implicit $exec
    %1625:vgpr_32, %1627:sreg_64_xexec = V_ADD_CO_U32_e64 %84, %89, 0, implicit $exec
    %1626:vgpr_32, dead %1628:sreg_64_xexec = V_ADDC_U32_e64 0, %83, %1627, 0, implicit $exec
    %92:vreg_64 = REG_SEQUENCE %1625, %subreg.sub0, %1626, %subreg.sub1
    %1633:vgpr_32, %1635:sreg_64_xexec = V_ADD_CO_U32_e64 %1625, %89, 0, implicit $exec
    %1634:vgpr_32, dead %1636:sreg_64_xexec = V_ADDC_U32_e64 0, %1626, %1635, 0, implicit $exec
    %93:vreg_64 = REG_SEQUENCE %1633, %subreg.sub0, %1634, %subreg.sub1
    %1641:vgpr_32, %1643:sreg_64_xexec = V_ADD_CO_U32_e64 %1633, %89, 0, implicit $exec
    %1642:vgpr_32, dead %1644:sreg_64_xexec = V_ADDC_U32_e64 0, %1634, %1643, 0, implicit $exec
    %94:vreg_64 = REG_SEQUENCE %1641, %subreg.sub0, %1642, %subreg.sub1
    %1649:vgpr_32, %1651:sreg_64_xexec = V_ADD_CO_U32_e64 %1641, %89, 0, implicit $exec
    %1650:vgpr_32, dead %1652:sreg_64_xexec = V_ADDC_U32_e64 0, %1642, %1651, 0, implicit $exec
    %95:vreg_64 = REG_SEQUENCE %1649, %subreg.sub0, %1650, %subreg.sub1
    %1657:vgpr_32, %1659:sreg_64_xexec = V_ADD_CO_U32_e64 %1649, %89, 0, implicit $exec
    %1658:vgpr_32, dead %1660:sreg_64_xexec = V_ADDC_U32_e64 0, %1650, %1659, 0, implicit $exec
    %96:vreg_64 = REG_SEQUENCE %1657, %subreg.sub0, %1658, %subreg.sub1
    %1665:vgpr_32, %1667:sreg_64_xexec = V_ADD_CO_U32_e64 %1657, %89, 0, implicit $exec
    %1666:vgpr_32, dead %1668:sreg_64_xexec = V_ADDC_U32_e64 0, %1658, %1667, 0, implicit $exec
    %97:vreg_64 = REG_SEQUENCE %1665, %subreg.sub0, %1666, %subreg.sub1
    %1673:vgpr_32, %1675:sreg_64_xexec = V_ADD_CO_U32_e64 %1665, %89, 0, implicit $exec
    %1674:vgpr_32, dead %1676:sreg_64_xexec = V_ADDC_U32_e64 0, %1666, %1675, 0, implicit $exec
    %98:vreg_64 = REG_SEQUENCE %1673, %subreg.sub0, %1674, %subreg.sub1
    %99:vreg_128 = GLOBAL_LOAD_DWORDX4 %92, 112, 0, implicit $exec :: (volatile load (s128) from %ir.p1 + 112, addrspace 1)
    %100:vgpr_32 = COPY %99.sub3
    %101:vgpr_32 = COPY %99.sub2
    %102:vgpr_32 = COPY %99.sub1
    %103:vgpr_32 = COPY %99.sub0
    %104:vreg_128 = GLOBAL_LOAD_DWORDX4 %92, 96, 0, implicit $exec :: (volatile load (s128) from %ir.p1 + 96, align 32, addrspace 1)
    %105:vgpr_32 = COPY %104.sub3
    %106:vgpr_32 = COPY %104.sub2
    %107:vgpr_32 = COPY %104.sub1
    %108:vgpr_32 = COPY %104.sub0
    %109:vreg_128 = GLOBAL_LOAD_DWORDX4 %92, 80, 0, implicit $exec :: (volatile load (s128) from %ir.p1 + 80, addrspace 1)
    %110:vgpr_32 = COPY %109.sub3
    %111:vgpr_32 = COPY %109.sub2
    %112:vgpr_32 = COPY %109.sub1
    %113:vgpr_32 = COPY %109.sub0
    %114:vreg_128 = GLOBAL_LOAD_DWORDX4 %92, 64, 0, implicit $exec :: (volatile load (s128) from %ir.p1 + 64, align 64, addrspace 1)
    %115:vgpr_32 = COPY %114.sub3
    %116:vgpr_32 = COPY %114.sub2
    %117:vgpr_32 = COPY %114.sub1
    %118:vgpr_32 = COPY %114.sub0
    %119:vreg_128 = GLOBAL_LOAD_DWORDX4 %92, 48, 0, implicit $exec :: (volatile load (s128) from %ir.p1 + 48, addrspace 1)
    %120:vgpr_32 = COPY %119.sub3
    %121:vgpr_32 = COPY %119.sub2
    %122:vgpr_32 = COPY %119.sub1
    %123:vgpr_32 = COPY %119.sub0
    %124:vreg_128 = GLOBAL_LOAD_DWORDX4 %92, 32, 0, implicit $exec :: (volatile load (s128) from %ir.p1 + 32, align 32, addrspace 1)
    %125:vgpr_32 = COPY %124.sub3
    %126:vgpr_32 = COPY %124.sub2
    %127:vgpr_32 = COPY %124.sub1
    %128:vgpr_32 = COPY %124.sub0
    %129:vreg_128 = GLOBAL_LOAD_DWORDX4 %92, 16, 0, implicit $exec :: (volatile load (s128) from %ir.p1 + 16, addrspace 1)
    %130:vgpr_32 = COPY %129.sub3
    %131:vgpr_32 = COPY %129.sub2
    %132:vgpr_32 = COPY %129.sub1
    %133:vgpr_32 = COPY %129.sub0
    %134:vreg_128 = GLOBAL_LOAD_DWORDX4 %92, 0, 0, implicit $exec :: (volatile load (s128) from %ir.p1, align 128, addrspace 1)
    %135:vgpr_32 = COPY %134.sub3
    %136:vgpr_32 = COPY %134.sub2
    %137:vgpr_32 = COPY %134.sub1
    %138:vgpr_32 = COPY %134.sub0
    %1619:vreg_1024 = REG_SEQUENCE %138, %subreg.sub0, %137, %subreg.sub1, %136, %subreg.sub2, %135, %subreg.sub3, %133, %subreg.sub4, %132, %subreg.sub5, %131, %subreg.sub6, %130, %subreg.sub7, %128, %subreg.sub8, %127, %subreg.sub9, %126, %subreg.sub10, %125, %subreg.sub11, %123, %subreg.sub12, %122, %subreg.sub13, %121, %subreg.sub14, %120, %subreg.sub15, %118, %subreg.sub16, %117, %subreg.sub17, %116, %subreg.sub18, %115, %subreg.sub19, %113, %subreg.sub20, %112, %subreg.sub21, %111, %subreg.sub22, %110, %subreg.sub23, %108, %subreg.sub24, %107, %subreg.sub25, %106, %subreg.sub26, %105, %subreg.sub27, %103, %subreg.sub28, %102, %subreg.sub29, %101, %subreg.sub30, %100, %subreg.sub31
    %0:vreg_1024 = COPY %1619
    %140:vreg_128 = GLOBAL_LOAD_DWORDX4 %93, 112, 0, implicit $exec :: (volatile load (s128) from %ir.p2 + 112, addrspace 1)
    %141:vgpr_32 = COPY %140.sub3
    %142:vgpr_32 = COPY %140.sub2
    %143:vgpr_32 = COPY %140.sub1
    %144:vgpr_32 = COPY %140.sub0
    %145:vreg_128 = GLOBAL_LOAD_DWORDX4 %93, 96, 0, implicit $exec :: (volatile load (s128) from %ir.p2 + 96, align 32, addrspace 1)
    %146:vgpr_32 = COPY %145.sub3
    %147:vgpr_32 = COPY %145.sub2
    %148:vgpr_32 = COPY %145.sub1
    %149:vgpr_32 = COPY %145.sub0
    %150:vreg_128 = GLOBAL_LOAD_DWORDX4 %93, 80, 0, implicit $exec :: (volatile load (s128) from %ir.p2 + 80, addrspace 1)
    %151:vgpr_32 = COPY %150.sub3
    %152:vgpr_32 = COPY %150.sub2
    %153:vgpr_32 = COPY %150.sub1
    %154:vgpr_32 = COPY %150.sub0
    %155:vreg_128 = GLOBAL_LOAD_DWORDX4 %93, 64, 0, implicit $exec :: (volatile load (s128) from %ir.p2 + 64, align 64, addrspace 1)
    %156:vgpr_32 = COPY %155.sub3
    %157:vgpr_32 = COPY %155.sub2
    %158:vgpr_32 = COPY %155.sub1
    %159:vgpr_32 = COPY %155.sub0
    %160:vreg_128 = GLOBAL_LOAD_DWORDX4 %93, 48, 0, implicit $exec :: (volatile load (s128) from %ir.p2 + 48, addrspace 1)
    %161:vgpr_32 = COPY %160.sub3
    %162:vgpr_32 = COPY %160.sub2
    %163:vgpr_32 = COPY %160.sub1
    %164:vgpr_32 = COPY %160.sub0
    %165:vreg_128 = GLOBAL_LOAD_DWORDX4 %93, 32, 0, implicit $exec :: (volatile load (s128) from %ir.p2 + 32, align 32, addrspace 1)
    %166:vgpr_32 = COPY %165.sub3
    %167:vgpr_32 = COPY %165.sub2
    %168:vgpr_32 = COPY %165.sub1
    %169:vgpr_32 = COPY %165.sub0
    %170:vreg_128 = GLOBAL_LOAD_DWORDX4 %93, 16, 0, implicit $exec :: (volatile load (s128) from %ir.p2 + 16, addrspace 1)
    %171:vgpr_32 = COPY %170.sub3
    %172:vgpr_32 = COPY %170.sub2
    %173:vgpr_32 = COPY %170.sub1
    %174:vgpr_32 = COPY %170.sub0
    %175:vreg_128 = GLOBAL_LOAD_DWORDX4 %93, 0, 0, implicit $exec :: (volatile load (s128) from %ir.p2, align 128, addrspace 1)
    %176:vgpr_32 = COPY %175.sub3
    %177:vgpr_32 = COPY %175.sub2
    %178:vgpr_32 = COPY %175.sub1
    %179:vgpr_32 = COPY %175.sub0
    %1618:vreg_1024 = REG_SEQUENCE %179, %subreg.sub0, %178, %subreg.sub1, %177, %subreg.sub2, %176, %subreg.sub3, %174, %subreg.sub4, %173, %subreg.sub5, %172, %subreg.sub6, %171, %subreg.sub7, %169, %subreg.sub8, %168, %subreg.sub9, %167, %subreg.sub10, %166, %subreg.sub11, %164, %subreg.sub12, %163, %subreg.sub13, %162, %subreg.sub14, %161, %subreg.sub15, %159, %subreg.sub16, %158, %subreg.sub17, %157, %subreg.sub18, %156, %subreg.sub19, %154, %subreg.sub20, %153, %subreg.sub21, %152, %subreg.sub22, %151, %subreg.sub23, %149, %subreg.sub24, %148, %subreg.sub25, %147, %subreg.sub26, %146, %subreg.sub27, %144, %subreg.sub28, %143, %subreg.sub29, %142, %subreg.sub30, %141, %subreg.sub31
    %1:vreg_1024 = COPY %1618
    %181:vreg_128 = GLOBAL_LOAD_DWORDX4 %94, 112, 0, implicit $exec :: (volatile load (s128) from %ir.p3 + 112, addrspace 1)
    %182:vgpr_32 = COPY %181.sub3
    %183:vgpr_32 = COPY %181.sub2
    %184:vgpr_32 = COPY %181.sub1
    %185:vgpr_32 = COPY %181.sub0
    %186:vreg_128 = GLOBAL_LOAD_DWORDX4 %94, 96, 0, implicit $exec :: (volatile load (s128) from %ir.p3 + 96, align 32, addrspace 1)
    %187:vgpr_32 = COPY %186.sub3
    %188:vgpr_32 = COPY %186.sub2
    %189:vgpr_32 = COPY %186.sub1
    %190:vgpr_32 = COPY %186.sub0
    %191:vreg_128 = GLOBAL_LOAD_DWORDX4 %94, 80, 0, implicit $exec :: (volatile load (s128) from %ir.p3 + 80, addrspace 1)
    %192:vgpr_32 = COPY %191.sub3
    %193:vgpr_32 = COPY %191.sub2
    %194:vgpr_32 = COPY %191.sub1
    %195:vgpr_32 = COPY %191.sub0
    %196:vreg_128 = GLOBAL_LOAD_DWORDX4 %94, 64, 0, implicit $exec :: (volatile load (s128) from %ir.p3 + 64, align 64, addrspace 1)
    %197:vgpr_32 = COPY %196.sub3
    %198:vgpr_32 = COPY %196.sub2
    %199:vgpr_32 = COPY %196.sub1
    %200:vgpr_32 = COPY %196.sub0
    %201:vreg_128 = GLOBAL_LOAD_DWORDX4 %94, 48, 0, implicit $exec :: (volatile load (s128) from %ir.p3 + 48, addrspace 1)
    %202:vgpr_32 = COPY %201.sub3
    %203:vgpr_32 = COPY %201.sub2
    %204:vgpr_32 = COPY %201.sub1
    %205:vgpr_32 = COPY %201.sub0
    %206:vreg_128 = GLOBAL_LOAD_DWORDX4 %94, 32, 0, implicit $exec :: (volatile load (s128) from %ir.p3 + 32, align 32, addrspace 1)
    %207:vgpr_32 = COPY %206.sub3
    %208:vgpr_32 = COPY %206.sub2
    %209:vgpr_32 = COPY %206.sub1
    %210:vgpr_32 = COPY %206.sub0
    %211:vreg_128 = GLOBAL_LOAD_DWORDX4 %94, 16, 0, implicit $exec :: (volatile load (s128) from %ir.p3 + 16, addrspace 1)
    %212:vgpr_32 = COPY %211.sub3
    %213:vgpr_32 = COPY %211.sub2
    %214:vgpr_32 = COPY %211.sub1
    %215:vgpr_32 = COPY %211.sub0
    %216:vreg_128 = GLOBAL_LOAD_DWORDX4 %94, 0, 0, implicit $exec :: (volatile load (s128) from %ir.p3, align 128, addrspace 1)
    %217:vgpr_32 = COPY %216.sub3
    %218:vgpr_32 = COPY %216.sub2
    %219:vgpr_32 = COPY %216.sub1
    %220:vgpr_32 = COPY %216.sub0
    %1617:vreg_1024 = REG_SEQUENCE %220, %subreg.sub0, %219, %subreg.sub1, %218, %subreg.sub2, %217, %subreg.sub3, %215, %subreg.sub4, %214, %subreg.sub5, %213, %subreg.sub6, %212, %subreg.sub7, %210, %subreg.sub8, %209, %subreg.sub9, %208, %subreg.sub10, %207, %subreg.sub11, %205, %subreg.sub12, %204, %subreg.sub13, %203, %subreg.sub14, %202, %subreg.sub15, %200, %subreg.sub16, %199, %subreg.sub17, %198, %subreg.sub18, %197, %subreg.sub19, %195, %subreg.sub20, %194, %subreg.sub21, %193, %subreg.sub22, %192, %subreg.sub23, %190, %subreg.sub24, %189, %subreg.sub25, %188, %subreg.sub26, %187, %subreg.sub27, %185, %subreg.sub28, %184, %subreg.sub29, %183, %subreg.sub30, %182, %subreg.sub31
    %2:vreg_1024 = COPY %1617
    %222:vreg_128 = GLOBAL_LOAD_DWORDX4 %95, 112, 0, implicit $exec :: (volatile load (s128) from %ir.p4 + 112, addrspace 1)
    %223:vgpr_32 = COPY %222.sub3
    %224:vgpr_32 = COPY %222.sub2
    %225:vgpr_32 = COPY %222.sub1
    %226:vgpr_32 = COPY %222.sub0
    %227:vreg_128 = GLOBAL_LOAD_DWORDX4 %95, 96, 0, implicit $exec :: (volatile load (s128) from %ir.p4 + 96, align 32, addrspace 1)
    %228:vgpr_32 = COPY %227.sub3
    %229:vgpr_32 = COPY %227.sub2
    %230:vgpr_32 = COPY %227.sub1
    %231:vgpr_32 = COPY %227.sub0
    %232:vreg_128 = GLOBAL_LOAD_DWORDX4 %95, 80, 0, implicit $exec :: (volatile load (s128) from %ir.p4 + 80, addrspace 1)
    %233:vgpr_32 = COPY %232.sub3
    %234:vgpr_32 = COPY %232.sub2
    %235:vgpr_32 = COPY %232.sub1
    %236:vgpr_32 = COPY %232.sub0
    %237:vreg_128 = GLOBAL_LOAD_DWORDX4 %95, 64, 0, implicit $exec :: (volatile load (s128) from %ir.p4 + 64, align 64, addrspace 1)
    %238:vgpr_32 = COPY %237.sub3
    %239:vgpr_32 = COPY %237.sub2
    %240:vgpr_32 = COPY %237.sub1
    %241:vgpr_32 = COPY %237.sub0
    %242:vreg_128 = GLOBAL_LOAD_DWORDX4 %95, 48, 0, implicit $exec :: (volatile load (s128) from %ir.p4 + 48, addrspace 1)
    %243:vgpr_32 = COPY %242.sub3
    %244:vgpr_32 = COPY %242.sub2
    %245:vgpr_32 = COPY %242.sub1
    %246:vgpr_32 = COPY %242.sub0
    %247:vreg_128 = GLOBAL_LOAD_DWORDX4 %95, 32, 0, implicit $exec :: (volatile load (s128) from %ir.p4 + 32, align 32, addrspace 1)
    %248:vgpr_32 = COPY %247.sub3
    %249:vgpr_32 = COPY %247.sub2
    %250:vgpr_32 = COPY %247.sub1
    %251:vgpr_32 = COPY %247.sub0
    %252:vreg_128 = GLOBAL_LOAD_DWORDX4 %95, 16, 0, implicit $exec :: (volatile load (s128) from %ir.p4 + 16, addrspace 1)
    %253:vgpr_32 = COPY %252.sub3
    %254:vgpr_32 = COPY %252.sub2
    %255:vgpr_32 = COPY %252.sub1
    %256:vgpr_32 = COPY %252.sub0
    %257:vreg_128 = GLOBAL_LOAD_DWORDX4 %95, 0, 0, implicit $exec :: (volatile load (s128) from %ir.p4, align 128, addrspace 1)
    %258:vgpr_32 = COPY %257.sub3
    %259:vgpr_32 = COPY %257.sub2
    %260:vgpr_32 = COPY %257.sub1
    %261:vgpr_32 = COPY %257.sub0
    %1616:vreg_1024 = REG_SEQUENCE %261, %subreg.sub0, %260, %subreg.sub1, %259, %subreg.sub2, %258, %subreg.sub3, %256, %subreg.sub4, %255, %subreg.sub5, %254, %subreg.sub6, %253, %subreg.sub7, %251, %subreg.sub8, %250, %subreg.sub9, %249, %subreg.sub10, %248, %subreg.sub11, %246, %subreg.sub12, %245, %subreg.sub13, %244, %subreg.sub14, %243, %subreg.sub15, %241, %subreg.sub16, %240, %subreg.sub17, %239, %subreg.sub18, %238, %subreg.sub19, %236, %subreg.sub20, %235, %subreg.sub21, %234, %subreg.sub22, %233, %subreg.sub23, %231, %subreg.sub24, %230, %subreg.sub25, %229, %subreg.sub26, %228, %subreg.sub27, %226, %subreg.sub28, %225, %subreg.sub29, %224, %subreg.sub30, %223, %subreg.sub31
    %3:vreg_1024 = COPY %1616
    %263:vreg_128 = GLOBAL_LOAD_DWORDX4 %96, 112, 0, implicit $exec :: (volatile load (s128) from %ir.p5 + 112, addrspace 1)
    %264:vgpr_32 = COPY %263.sub3
    %265:vgpr_32 = COPY %263.sub2
    %266:vgpr_32 = COPY %263.sub1
    %267:vgpr_32 = COPY %263.sub0
    %268:vreg_128 = GLOBAL_LOAD_DWORDX4 %96, 96, 0, implicit $exec :: (volatile load (s128) from %ir.p5 + 96, align 32, addrspace 1)
    %269:vgpr_32 = COPY %268.sub3
    %270:vgpr_32 = COPY %268.sub2
    %271:vgpr_32 = COPY %268.sub1
    %272:vgpr_32 = COPY %268.sub0
    %273:vreg_128 = GLOBAL_LOAD_DWORDX4 %96, 80, 0, implicit $exec :: (volatile load (s128) from %ir.p5 + 80, addrspace 1)
    %274:vgpr_32 = COPY %273.sub3
    %275:vgpr_32 = COPY %273.sub2
    %276:vgpr_32 = COPY %273.sub1
    %277:vgpr_32 = COPY %273.sub0
    %278:vreg_128 = GLOBAL_LOAD_DWORDX4 %96, 64, 0, implicit $exec :: (volatile load (s128) from %ir.p5 + 64, align 64, addrspace 1)
    %279:vgpr_32 = COPY %278.sub3
    %280:vgpr_32 = COPY %278.sub2
    %281:vgpr_32 = COPY %278.sub1
    %282:vgpr_32 = COPY %278.sub0
    %283:vreg_128 = GLOBAL_LOAD_DWORDX4 %96, 48, 0, implicit $exec :: (volatile load (s128) from %ir.p5 + 48, addrspace 1)
    %284:vgpr_32 = COPY %283.sub3
    %285:vgpr_32 = COPY %283.sub2
    %286:vgpr_32 = COPY %283.sub1
    %287:vgpr_32 = COPY %283.sub0
    %288:vreg_128 = GLOBAL_LOAD_DWORDX4 %96, 32, 0, implicit $exec :: (volatile load (s128) from %ir.p5 + 32, align 32, addrspace 1)
    %289:vgpr_32 = COPY %288.sub3
    %290:vgpr_32 = COPY %288.sub2
    %291:vgpr_32 = COPY %288.sub1
    %292:vgpr_32 = COPY %288.sub0
    %293:vreg_128 = GLOBAL_LOAD_DWORDX4 %96, 16, 0, implicit $exec :: (volatile load (s128) from %ir.p5 + 16, addrspace 1)
    %294:vgpr_32 = COPY %293.sub3
    %295:vgpr_32 = COPY %293.sub2
    %296:vgpr_32 = COPY %293.sub1
    %297:vgpr_32 = COPY %293.sub0
    %298:vreg_128 = GLOBAL_LOAD_DWORDX4 %96, 0, 0, implicit $exec :: (volatile load (s128) from %ir.p5, align 128, addrspace 1)
    %299:vgpr_32 = COPY %298.sub3
    %300:vgpr_32 = COPY %298.sub2
    %301:vgpr_32 = COPY %298.sub1
    %302:vgpr_32 = COPY %298.sub0
    %1615:vreg_1024 = REG_SEQUENCE %302, %subreg.sub0, %301, %subreg.sub1, %300, %subreg.sub2, %299, %subreg.sub3, %297, %subreg.sub4, %296, %subreg.sub5, %295, %subreg.sub6, %294, %subreg.sub7, %292, %subreg.sub8, %291, %subreg.sub9, %290, %subreg.sub10, %289, %subreg.sub11, %287, %subreg.sub12, %286, %subreg.sub13, %285, %subreg.sub14, %284, %subreg.sub15, %282, %subreg.sub16, %281, %subreg.sub17, %280, %subreg.sub18, %279, %subreg.sub19, %277, %subreg.sub20, %276, %subreg.sub21, %275, %subreg.sub22, %274, %subreg.sub23, %272, %subreg.sub24, %271, %subreg.sub25, %270, %subreg.sub26, %269, %subreg.sub27, %267, %subreg.sub28, %266, %subreg.sub29, %265, %subreg.sub30, %264, %subreg.sub31
    %4:vreg_1024 = COPY %1615
    %304:vreg_128 = GLOBAL_LOAD_DWORDX4 %97, 112, 0, implicit $exec :: (volatile load (s128) from %ir.p6 + 112, addrspace 1)
    %305:vgpr_32 = COPY %304.sub3
    %306:vgpr_32 = COPY %304.sub2
    %307:vgpr_32 = COPY %304.sub1
    %308:vgpr_32 = COPY %304.sub0
    %309:vreg_128 = GLOBAL_LOAD_DWORDX4 %97, 96, 0, implicit $exec :: (volatile load (s128) from %ir.p6 + 96, align 32, addrspace 1)
    %310:vgpr_32 = COPY %309.sub3
    %311:vgpr_32 = COPY %309.sub2
    %312:vgpr_32 = COPY %309.sub1
    %313:vgpr_32 = COPY %309.sub0
    %314:vreg_128 = GLOBAL_LOAD_DWORDX4 %97, 80, 0, implicit $exec :: (volatile load (s128) from %ir.p6 + 80, addrspace 1)
    %315:vgpr_32 = COPY %314.sub3
    %316:vgpr_32 = COPY %314.sub2
    %317:vgpr_32 = COPY %314.sub1
    %318:vgpr_32 = COPY %314.sub0
    %319:vreg_128 = GLOBAL_LOAD_DWORDX4 %97, 64, 0, implicit $exec :: (volatile load (s128) from %ir.p6 + 64, align 64, addrspace 1)
    %320:vgpr_32 = COPY %319.sub3
    %321:vgpr_32 = COPY %319.sub2
    %322:vgpr_32 = COPY %319.sub1
    %323:vgpr_32 = COPY %319.sub0
    %324:vreg_128 = GLOBAL_LOAD_DWORDX4 %97, 48, 0, implicit $exec :: (volatile load (s128) from %ir.p6 + 48, addrspace 1)
    %325:vgpr_32 = COPY %324.sub3
    %326:vgpr_32 = COPY %324.sub2
    %327:vgpr_32 = COPY %324.sub1
    %328:vgpr_32 = COPY %324.sub0
    %329:vreg_128 = GLOBAL_LOAD_DWORDX4 %97, 32, 0, implicit $exec :: (volatile load (s128) from %ir.p6 + 32, align 32, addrspace 1)
    %330:vgpr_32 = COPY %329.sub3
    %331:vgpr_32 = COPY %329.sub2
    %332:vgpr_32 = COPY %329.sub1
    %333:vgpr_32 = COPY %329.sub0
    %334:vreg_128 = GLOBAL_LOAD_DWORDX4 %97, 16, 0, implicit $exec :: (volatile load (s128) from %ir.p6 + 16, addrspace 1)
    %335:vgpr_32 = COPY %334.sub3
    %336:vgpr_32 = COPY %334.sub2
    %337:vgpr_32 = COPY %334.sub1
    %338:vgpr_32 = COPY %334.sub0
    %339:vreg_128 = GLOBAL_LOAD_DWORDX4 %97, 0, 0, implicit $exec :: (volatile load (s128) from %ir.p6, align 128, addrspace 1)
    %340:vgpr_32 = COPY %339.sub3
    %341:vgpr_32 = COPY %339.sub2
    %342:vgpr_32 = COPY %339.sub1
    %343:vgpr_32 = COPY %339.sub0
    %1614:vreg_1024 = REG_SEQUENCE %343, %subreg.sub0, %342, %subreg.sub1, %341, %subreg.sub2, %340, %subreg.sub3, %338, %subreg.sub4, %337, %subreg.sub5, %336, %subreg.sub6, %335, %subreg.sub7, %333, %subreg.sub8, %332, %subreg.sub9, %331, %subreg.sub10, %330, %subreg.sub11, %328, %subreg.sub12, %327, %subreg.sub13, %326, %subreg.sub14, %325, %subreg.sub15, %323, %subreg.sub16, %322, %subreg.sub17, %321, %subreg.sub18, %320, %subreg.sub19, %318, %subreg.sub20, %317, %subreg.sub21, %316, %subreg.sub22, %315, %subreg.sub23, %313, %subreg.sub24, %312, %subreg.sub25, %311, %subreg.sub26, %310, %subreg.sub27, %308, %subreg.sub28, %307, %subreg.sub29, %306, %subreg.sub30, %305, %subreg.sub31
    %5:vreg_1024 = COPY %1614
    %345:vreg_128 = GLOBAL_LOAD_DWORDX4 %98, 112, 0, implicit $exec :: (volatile load (s128) from %ir.p7 + 112, addrspace 1)
    %346:vgpr_32 = COPY %345.sub3
    %347:vgpr_32 = COPY %345.sub2
    %348:vgpr_32 = COPY %345.sub1
    %349:vgpr_32 = COPY %345.sub0
    %350:vreg_128 = GLOBAL_LOAD_DWORDX4 %98, 96, 0, implicit $exec :: (volatile load (s128) from %ir.p7 + 96, align 32, addrspace 1)
    %351:vgpr_32 = COPY %350.sub3
    %352:vgpr_32 = COPY %350.sub2
    %353:vgpr_32 = COPY %350.sub1
    %354:vgpr_32 = COPY %350.sub0
    %355:vreg_128 = GLOBAL_LOAD_DWORDX4 %98, 80, 0, implicit $exec :: (volatile load (s128) from %ir.p7 + 80, addrspace 1)
    %356:vgpr_32 = COPY %355.sub3
    %357:vgpr_32 = COPY %355.sub2
    %358:vgpr_32 = COPY %355.sub1
    %359:vgpr_32 = COPY %355.sub0
    %360:vreg_128 = GLOBAL_LOAD_DWORDX4 %98, 64, 0, implicit $exec :: (volatile load (s128) from %ir.p7 + 64, align 64, addrspace 1)
    %361:vgpr_32 = COPY %360.sub3
    %362:vgpr_32 = COPY %360.sub2
    %363:vgpr_32 = COPY %360.sub1
    %364:vgpr_32 = COPY %360.sub0
    %365:vreg_128 = GLOBAL_LOAD_DWORDX4 %98, 48, 0, implicit $exec :: (volatile load (s128) from %ir.p7 + 48, addrspace 1)
    %366:vgpr_32 = COPY %365.sub3
    %367:vgpr_32 = COPY %365.sub2
    %368:vgpr_32 = COPY %365.sub1
    %369:vgpr_32 = COPY %365.sub0
    %370:vreg_128 = GLOBAL_LOAD_DWORDX4 %98, 32, 0, implicit $exec :: (volatile load (s128) from %ir.p7 + 32, align 32, addrspace 1)
    %371:vgpr_32 = COPY %370.sub3
    %372:vgpr_32 = COPY %370.sub2
    %373:vgpr_32 = COPY %370.sub1
    %374:vgpr_32 = COPY %370.sub0
    %375:vreg_128 = GLOBAL_LOAD_DWORDX4 %98, 16, 0, implicit $exec :: (volatile load (s128) from %ir.p7 + 16, addrspace 1)
    %376:vgpr_32 = COPY %375.sub3
    %377:vgpr_32 = COPY %375.sub2
    %378:vgpr_32 = COPY %375.sub1
    %379:vgpr_32 = COPY %375.sub0
    %380:vreg_128 = GLOBAL_LOAD_DWORDX4 %98, 0, 0, implicit $exec :: (volatile load (s128) from %ir.p7, align 128, addrspace 1)
    %381:vgpr_32 = COPY %380.sub3
    %382:vgpr_32 = COPY %380.sub2
    %383:vgpr_32 = COPY %380.sub1
    %384:vgpr_32 = COPY %380.sub0
    %1613:vreg_1024 = REG_SEQUENCE %384, %subreg.sub0, %383, %subreg.sub1, %382, %subreg.sub2, %381, %subreg.sub3, %379, %subreg.sub4, %378, %subreg.sub5, %377, %subreg.sub6, %376, %subreg.sub7, %374, %subreg.sub8, %373, %subreg.sub9, %372, %subreg.sub10, %371, %subreg.sub11, %369, %subreg.sub12, %368, %subreg.sub13, %367, %subreg.sub14, %366, %subreg.sub15, %364, %subreg.sub16, %363, %subreg.sub17, %362, %subreg.sub18, %361, %subreg.sub19, %359, %subreg.sub20, %358, %subreg.sub21, %357, %subreg.sub22, %356, %subreg.sub23, %354, %subreg.sub24, %353, %subreg.sub25, %352, %subreg.sub26, %351, %subreg.sub27, %349, %subreg.sub28, %348, %subreg.sub29, %347, %subreg.sub30, %346, %subreg.sub31
    %6:vreg_1024 = COPY %1613

  bb.1.st:
    %386:vgpr_32 = COPY %45.sub31
    %387:vgpr_32 = COPY %45.sub30
    %388:vgpr_32 = COPY %45.sub29
    %389:vgpr_32 = COPY %45.sub28
    %1612:vreg_128 = REG_SEQUENCE %389, %subreg.sub0, %388, %subreg.sub1, %387, %subreg.sub2, %386, %subreg.sub3
    GLOBAL_STORE_DWORDX4 undef %392:vreg_64, %1612, 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 112, addrspace 1)
    %394:vgpr_32 = COPY %45.sub27
    %395:vgpr_32 = COPY %45.sub26
    %396:vgpr_32 = COPY %45.sub25
    %397:vgpr_32 = COPY %45.sub24
    %1611:vreg_128 = REG_SEQUENCE %397, %subreg.sub0, %396, %subreg.sub1, %395, %subreg.sub2, %394, %subreg.sub3
    GLOBAL_STORE_DWORDX4 undef %400:vreg_64, %1611, 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 96, align 32, addrspace 1)
    %402:vgpr_32 = COPY %45.sub23
    %403:vgpr_32 = COPY %45.sub22
    %404:vgpr_32 = COPY %45.sub21
    %405:vgpr_32 = COPY %45.sub20
    %1610:vreg_128 = REG_SEQUENCE %405, %subreg.sub0, %404, %subreg.sub1, %403, %subreg.sub2, %402, %subreg.sub3
    GLOBAL_STORE_DWORDX4 undef %408:vreg_64, %1610, 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 80, addrspace 1)
    %410:vgpr_32 = COPY %45.sub19
    %411:vgpr_32 = COPY %45.sub18
    %412:vgpr_32 = COPY %45.sub17
    %413:vgpr_32 = COPY %45.sub16
    %1609:vreg_128 = REG_SEQUENCE %413, %subreg.sub0, %412, %subreg.sub1, %411, %subreg.sub2, %410, %subreg.sub3
    GLOBAL_STORE_DWORDX4 undef %416:vreg_64, %1609, 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 64, align 64, addrspace 1)
    %418:vgpr_32 = COPY %45.sub15
    %419:vgpr_32 = COPY %45.sub14
    %420:vgpr_32 = COPY %45.sub13
    %421:vgpr_32 = COPY %45.sub12
    %1608:vreg_128 = REG_SEQUENCE %421, %subreg.sub0, %420, %subreg.sub1, %419, %subreg.sub2, %418, %subreg.sub3
    GLOBAL_STORE_DWORDX4 undef %424:vreg_64, %1608, 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 48, addrspace 1)
    %426:vgpr_32 = COPY %45.sub11
    %427:vgpr_32 = COPY %45.sub10
    %428:vgpr_32 = COPY %45.sub9
    %429:vgpr_32 = COPY %45.sub8
    %1607:vreg_128 = REG_SEQUENCE %429, %subreg.sub0, %428, %subreg.sub1, %427, %subreg.sub2, %426, %subreg.sub3
    GLOBAL_STORE_DWORDX4 undef %432:vreg_64, %1607, 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 32, align 32, addrspace 1)
    %434:vgpr_32 = COPY %45.sub7
    %435:vgpr_32 = COPY %45.sub6
    %436:vgpr_32 = COPY %45.sub5
    %437:vgpr_32 = COPY %45.sub4
    %1606:vreg_128 = REG_SEQUENCE %437, %subreg.sub0, %436, %subreg.sub1, %435, %subreg.sub2, %434, %subreg.sub3
    GLOBAL_STORE_DWORDX4 undef %440:vreg_64, %1606, 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 16, addrspace 1)
    %442:vgpr_32 = COPY %45.sub3
    %443:vgpr_32 = COPY %45.sub2
    %444:vgpr_32 = COPY %45.sub1
    %445:vgpr_32 = COPY %45.sub0
    %1605:vreg_128 = REG_SEQUENCE %445, %subreg.sub0, %444, %subreg.sub1, %443, %subreg.sub2, %442, %subreg.sub3
    GLOBAL_STORE_DWORDX4 undef %448:vreg_64, %1605, 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef`, align 128, addrspace 1)
    %450:vgpr_32 = COPY %46.sub31
    %451:vgpr_32 = COPY %46.sub30
    %452:vgpr_32 = COPY %46.sub29
    %453:vgpr_32 = COPY %46.sub28
    %1604:vreg_128 = REG_SEQUENCE %453, %subreg.sub0, %452, %subreg.sub1, %451, %subreg.sub2, %450, %subreg.sub3
    GLOBAL_STORE_DWORDX4 undef %456:vreg_64, %1604, 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 112, addrspace 1)
    %458:vgpr_32 = COPY %46.sub27
    %459:vgpr_32 = COPY %46.sub26
    %460:vgpr_32 = COPY %46.sub25
    %461:vgpr_32 = COPY %46.sub24
    %1603:vreg_128 = REG_SEQUENCE %461, %subreg.sub0, %460, %subreg.sub1, %459, %subreg.sub2, %458, %subreg.sub3
    GLOBAL_STORE_DWORDX4 undef %464:vreg_64, %1603, 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 96, align 32, addrspace 1)
    %466:vgpr_32 = COPY %46.sub23
    %467:vgpr_32 = COPY %46.sub22
    %468:vgpr_32 = COPY %46.sub21
    %469:vgpr_32 = COPY %46.sub20
    %1602:vreg_128 = REG_SEQUENCE %469, %subreg.sub0, %468, %subreg.sub1, %467, %subreg.sub2, %466, %subreg.sub3
    GLOBAL_STORE_DWORDX4 undef %472:vreg_64, %1602, 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 80, addrspace 1)
    %474:vgpr_32 = COPY %46.sub19
    %475:vgpr_32 = COPY %46.sub18
    %476:vgpr_32 = COPY %46.sub17
    %477:vgpr_32 = COPY %46.sub16
    %1601:vreg_128 = REG_SEQUENCE %477, %subreg.sub0, %476, %subreg.sub1, %475, %subreg.sub2, %474, %subreg.sub3
    GLOBAL_STORE_DWORDX4 undef %480:vreg_64, %1601, 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 64, align 64, addrspace 1)
    %482:vgpr_32 = COPY %46.sub15
    %483:vgpr_32 = COPY %46.sub14
    %484:vgpr_32 = COPY %46.sub13
    %485:vgpr_32 = COPY %46.sub12
    %1600:vreg_128 = REG_SEQUENCE %485, %subreg.sub0, %484, %subreg.sub1, %483, %subreg.sub2, %482, %subreg.sub3
    GLOBAL_STORE_DWORDX4 undef %488:vreg_64, %1600, 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 48, addrspace 1)
    %490:vgpr_32 = COPY %46.sub11
    %491:vgpr_32 = COPY %46.sub10
    %492:vgpr_32 = COPY %46.sub9
    %493:vgpr_32 = COPY %46.sub8
    %1599:vreg_128 = REG_SEQUENCE %493, %subreg.sub0, %492, %subreg.sub1, %491, %subreg.sub2, %490, %subreg.sub3
    GLOBAL_STORE_DWORDX4 undef %496:vreg_64, %1599, 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 32, align 32, addrspace 1)
    %498:vgpr_32 = COPY %46.sub7
    %499:vgpr_32 = COPY %46.sub6
    %500:vgpr_32 = COPY %46.sub5
    %501:vgpr_32 = COPY %46.sub4
    %1598:vreg_128 = REG_SEQUENCE %501, %subreg.sub0, %500, %subreg.sub1, %499, %subreg.sub2, %498, %subreg.sub3
    GLOBAL_STORE_DWORDX4 undef %504:vreg_64, %1598, 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 16, addrspace 1)
    %506:vgpr_32 = COPY %46.sub3
    %507:vgpr_32 = COPY %46.sub2
    %508:vgpr_32 = COPY %46.sub1
    %509:vgpr_32 = COPY %46.sub0
    %1597:vreg_128 = REG_SEQUENCE %509, %subreg.sub0, %508, %subreg.sub1, %507, %subreg.sub2, %506, %subreg.sub3
    GLOBAL_STORE_DWORDX4 undef %512:vreg_64, %1597, 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef`, align 128, addrspace 1)
    %514:vgpr_32 = COPY %0.sub31
    %515:vgpr_32 = COPY %0.sub30
    %516:vgpr_32 = COPY %0.sub29
    %517:vgpr_32 = COPY %0.sub28
    %1596:vreg_128 = REG_SEQUENCE %517, %subreg.sub0, %516, %subreg.sub1, %515, %subreg.sub2, %514, %subreg.sub3
    GLOBAL_STORE_DWORDX4 undef %520:vreg_64, %1596, 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 112, addrspace 1)
    %522:vgpr_32 = COPY %0.sub27
    %523:vgpr_32 = COPY %0.sub26
    %524:vgpr_32 = COPY %0.sub25
    %525:vgpr_32 = COPY %0.sub24
    %1595:vreg_128 = REG_SEQUENCE %525, %subreg.sub0, %524, %subreg.sub1, %523, %subreg.sub2, %522, %subreg.sub3
    GLOBAL_STORE_DWORDX4 undef %528:vreg_64, %1595, 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 96, align 32, addrspace 1)
    %530:vgpr_32 = COPY %0.sub23
    %531:vgpr_32 = COPY %0.sub22
    %532:vgpr_32 = COPY %0.sub21
    %533:vgpr_32 = COPY %0.sub20
    %1594:vreg_128 = REG_SEQUENCE %533, %subreg.sub0, %532, %subreg.sub1, %531, %subreg.sub2, %530, %subreg.sub3
    GLOBAL_STORE_DWORDX4 undef %536:vreg_64, %1594, 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 80, addrspace 1)
    %538:vgpr_32 = COPY %0.sub19
    %539:vgpr_32 = COPY %0.sub18
    %540:vgpr_32 = COPY %0.sub17
    %541:vgpr_32 = COPY %0.sub16
    %1593:vreg_128 = REG_SEQUENCE %541, %subreg.sub0, %540, %subreg.sub1, %539, %subreg.sub2, %538, %subreg.sub3
    GLOBAL_STORE_DWORDX4 undef %544:vreg_64, %1593, 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 64, align 64, addrspace 1)
    %546:vgpr_32 = COPY %0.sub15
    %547:vgpr_32 = COPY %0.sub14
    %548:vgpr_32 = COPY %0.sub13
    %549:vgpr_32 = COPY %0.sub12
    %1592:vreg_128 = REG_SEQUENCE %549, %subreg.sub0, %548, %subreg.sub1, %547, %subreg.sub2, %546, %subreg.sub3
    GLOBAL_STORE_DWORDX4 undef %552:vreg_64, %1592, 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 48, addrspace 1)
    %554:vgpr_32 = COPY %0.sub11
    %555:vgpr_32 = COPY %0.sub10
    %556:vgpr_32 = COPY %0.sub9
    %557:vgpr_32 = COPY %0.sub8
    %1591:vreg_128 = REG_SEQUENCE %557, %subreg.sub0, %556, %subreg.sub1, %555, %subreg.sub2, %554, %subreg.sub3
    GLOBAL_STORE_DWORDX4 undef %560:vreg_64, %1591, 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 32, align 32, addrspace 1)
    %562:vgpr_32 = COPY %0.sub7
    %563:vgpr_32 = COPY %0.sub6
    %564:vgpr_32 = COPY %0.sub5
    %565:vgpr_32 = COPY %0.sub4
    %1590:vreg_128 = REG_SEQUENCE %565, %subreg.sub0, %564, %subreg.sub1, %563, %subreg.sub2, %562, %subreg.sub3
    GLOBAL_STORE_DWORDX4 undef %568:vreg_64, %1590, 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 16, addrspace 1)
    %570:vgpr_32 = COPY %0.sub3
    %571:vgpr_32 = COPY %0.sub2
    %572:vgpr_32 = COPY %0.sub1
    %573:vgpr_32 = COPY %0.sub0
    %1589:vreg_128 = REG_SEQUENCE %573, %subreg.sub0, %572, %subreg.sub1, %571, %subreg.sub2, %570, %subreg.sub3
    GLOBAL_STORE_DWORDX4 undef %576:vreg_64, %1589, 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef`, align 128, addrspace 1)
    %578:vgpr_32 = COPY %1.sub31
    %579:vgpr_32 = COPY %1.sub30
    %580:vgpr_32 = COPY %1.sub29
    %581:vgpr_32 = COPY %1.sub28
    %1588:vreg_128 = REG_SEQUENCE %581, %subreg.sub0, %580, %subreg.sub1, %579, %subreg.sub2, %578, %subreg.sub3
    GLOBAL_STORE_DWORDX4 undef %584:vreg_64, %1588, 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 112, addrspace 1)
    %586:vgpr_32 = COPY %1.sub27
    %587:vgpr_32 = COPY %1.sub26
    %588:vgpr_32 = COPY %1.sub25
    %589:vgpr_32 = COPY %1.sub24
    %1587:vreg_128 = REG_SEQUENCE %589, %subreg.sub0, %588, %subreg.sub1, %587, %subreg.sub2, %586, %subreg.sub3
    GLOBAL_STORE_DWORDX4 undef %592:vreg_64, %1587, 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 96, align 32, addrspace 1)
    %594:vgpr_32 = COPY %1.sub23
    %595:vgpr_32 = COPY %1.sub22
    %596:vgpr_32 = COPY %1.sub21
    %597:vgpr_32 = COPY %1.sub20
    %1586:vreg_128 = REG_SEQUENCE %597, %subreg.sub0, %596, %subreg.sub1, %595, %subreg.sub2, %594, %subreg.sub3
    GLOBAL_STORE_DWORDX4 undef %600:vreg_64, %1586, 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 80, addrspace 1)
    %602:vgpr_32 = COPY %1.sub19
    %603:vgpr_32 = COPY %1.sub18
    %604:vgpr_32 = COPY %1.sub17
    %605:vgpr_32 = COPY %1.sub16
    %1585:vreg_128 = REG_SEQUENCE %605, %subreg.sub0, %604, %subreg.sub1, %603, %subreg.sub2, %602, %subreg.sub3
    GLOBAL_STORE_DWORDX4 undef %608:vreg_64, %1585, 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 64, align 64, addrspace 1)
    %610:vgpr_32 = COPY %1.sub15
    %611:vgpr_32 = COPY %1.sub14
    %612:vgpr_32 = COPY %1.sub13
    %613:vgpr_32 = COPY %1.sub12
    %1584:vreg_128 = REG_SEQUENCE %613, %subreg.sub0, %612, %subreg.sub1, %611, %subreg.sub2, %610, %subreg.sub3
    GLOBAL_STORE_DWORDX4 undef %616:vreg_64, %1584, 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 48, addrspace 1)
    %618:vgpr_32 = COPY %1.sub11
    %619:vgpr_32 = COPY %1.sub10
    %620:vgpr_32 = COPY %1.sub9
    %621:vgpr_32 = COPY %1.sub8
    %1583:vreg_128 = REG_SEQUENCE %621, %subreg.sub0, %620, %subreg.sub1, %619, %subreg.sub2, %618, %subreg.sub3
    GLOBAL_STORE_DWORDX4 undef %624:vreg_64, %1583, 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 32, align 32, addrspace 1)
    %626:vgpr_32 = COPY %1.sub7
    %627:vgpr_32 = COPY %1.sub6
    %628:vgpr_32 = COPY %1.sub5
    %629:vgpr_32 = COPY %1.sub4
    %1582:vreg_128 = REG_SEQUENCE %629, %subreg.sub0, %628, %subreg.sub1, %627, %subreg.sub2, %626, %subreg.sub3
    GLOBAL_STORE_DWORDX4 undef %632:vreg_64, %1582, 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 16, addrspace 1)
    %634:vgpr_32 = COPY %1.sub3
    %635:vgpr_32 = COPY %1.sub2
    %636:vgpr_32 = COPY %1.sub1
    %637:vgpr_32 = COPY %1.sub0
    %1581:vreg_128 = REG_SEQUENCE %637, %subreg.sub0, %636, %subreg.sub1, %635, %subreg.sub2, %634, %subreg.sub3
    GLOBAL_STORE_DWORDX4 undef %640:vreg_64, %1581, 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef`, align 128, addrspace 1)
    %642:vgpr_32 = COPY %2.sub31
    %643:vgpr_32 = COPY %2.sub30
    %644:vgpr_32 = COPY %2.sub29
    %645:vgpr_32 = COPY %2.sub28
    %1580:vreg_128 = REG_SEQUENCE %645, %subreg.sub0, %644, %subreg.sub1, %643, %subreg.sub2, %642, %subreg.sub3
    GLOBAL_STORE_DWORDX4 undef %648:vreg_64, %1580, 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 112, addrspace 1)
    %650:vgpr_32 = COPY %2.sub27
    %651:vgpr_32 = COPY %2.sub26
    %652:vgpr_32 = COPY %2.sub25
    %653:vgpr_32 = COPY %2.sub24
    %1579:vreg_128 = REG_SEQUENCE %653, %subreg.sub0, %652, %subreg.sub1, %651, %subreg.sub2, %650, %subreg.sub3
    GLOBAL_STORE_DWORDX4 undef %656:vreg_64, %1579, 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 96, align 32, addrspace 1)
    %658:vgpr_32 = COPY %2.sub23
    %659:vgpr_32 = COPY %2.sub22
    %660:vgpr_32 = COPY %2.sub21
    %661:vgpr_32 = COPY %2.sub20
    %1578:vreg_128 = REG_SEQUENCE %661, %subreg.sub0, %660, %subreg.sub1, %659, %subreg.sub2, %658, %subreg.sub3
    GLOBAL_STORE_DWORDX4 undef %664:vreg_64, %1578, 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 80, addrspace 1)
    %666:vgpr_32 = COPY %2.sub19
    %667:vgpr_32 = COPY %2.sub18
    %668:vgpr_32 = COPY %2.sub17
    %669:vgpr_32 = COPY %2.sub16
    %1577:vreg_128 = REG_SEQUENCE %669, %subreg.sub0, %668, %subreg.sub1, %667, %subreg.sub2, %666, %subreg.sub3
    GLOBAL_STORE_DWORDX4 undef %672:vreg_64, %1577, 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 64, align 64, addrspace 1)
    %674:vgpr_32 = COPY %2.sub15
    %675:vgpr_32 = COPY %2.sub14
    %676:vgpr_32 = COPY %2.sub13
    %677:vgpr_32 = COPY %2.sub12
    %1576:vreg_128 = REG_SEQUENCE %677, %subreg.sub0, %676, %subreg.sub1, %675, %subreg.sub2, %674, %subreg.sub3
    GLOBAL_STORE_DWORDX4 undef %680:vreg_64, %1576, 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 48, addrspace 1)
    %682:vgpr_32 = COPY %2.sub11
    %683:vgpr_32 = COPY %2.sub10
    %684:vgpr_32 = COPY %2.sub9
    %685:vgpr_32 = COPY %2.sub8
    %1575:vreg_128 = REG_SEQUENCE %685, %subreg.sub0, %684, %subreg.sub1, %683, %subreg.sub2, %682, %subreg.sub3
    GLOBAL_STORE_DWORDX4 undef %688:vreg_64, %1575, 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 32, align 32, addrspace 1)
    %690:vgpr_32 = COPY %2.sub7
    %691:vgpr_32 = COPY %2.sub6
    %692:vgpr_32 = COPY %2.sub5
    %693:vgpr_32 = COPY %2.sub4
    %1574:vreg_128 = REG_SEQUENCE %693, %subreg.sub0, %692, %subreg.sub1, %691, %subreg.sub2, %690, %subreg.sub3
    GLOBAL_STORE_DWORDX4 undef %696:vreg_64, %1574, 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 16, addrspace 1)
    %698:vgpr_32 = COPY %2.sub3
    %699:vgpr_32 = COPY %2.sub2
    %700:vgpr_32 = COPY %2.sub1
    %701:vgpr_32 = COPY %2.sub0
    %1573:vreg_128 = REG_SEQUENCE %701, %subreg.sub0, %700, %subreg.sub1, %699, %subreg.sub2, %698, %subreg.sub3
    GLOBAL_STORE_DWORDX4 undef %704:vreg_64, %1573, 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef`, align 128, addrspace 1)
    %706:vgpr_32 = COPY %3.sub31
    %707:vgpr_32 = COPY %3.sub30
    %708:vgpr_32 = COPY %3.sub29
    %709:vgpr_32 = COPY %3.sub28
    %1572:vreg_128 = REG_SEQUENCE %709, %subreg.sub0, %708, %subreg.sub1, %707, %subreg.sub2, %706, %subreg.sub3
    GLOBAL_STORE_DWORDX4 undef %712:vreg_64, %1572, 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 112, addrspace 1)
    %714:vgpr_32 = COPY %3.sub27
    %715:vgpr_32 = COPY %3.sub26
    %716:vgpr_32 = COPY %3.sub25
    %717:vgpr_32 = COPY %3.sub24
    %1571:vreg_128 = REG_SEQUENCE %717, %subreg.sub0, %716, %subreg.sub1, %715, %subreg.sub2, %714, %subreg.sub3
    GLOBAL_STORE_DWORDX4 undef %720:vreg_64, %1571, 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 96, align 32, addrspace 1)
    %722:vgpr_32 = COPY %3.sub23
    %723:vgpr_32 = COPY %3.sub22
    %724:vgpr_32 = COPY %3.sub21
    %725:vgpr_32 = COPY %3.sub20
    %1570:vreg_128 = REG_SEQUENCE %725, %subreg.sub0, %724, %subreg.sub1, %723, %subreg.sub2, %722, %subreg.sub3
    GLOBAL_STORE_DWORDX4 undef %728:vreg_64, %1570, 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 80, addrspace 1)
    %730:vgpr_32 = COPY %3.sub19
    %731:vgpr_32 = COPY %3.sub18
    %732:vgpr_32 = COPY %3.sub17
    %733:vgpr_32 = COPY %3.sub16
    %1569:vreg_128 = REG_SEQUENCE %733, %subreg.sub0, %732, %subreg.sub1, %731, %subreg.sub2, %730, %subreg.sub3
    GLOBAL_STORE_DWORDX4 undef %736:vreg_64, %1569, 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 64, align 64, addrspace 1)
    %738:vgpr_32 = COPY %3.sub15
    %739:vgpr_32 = COPY %3.sub14
    %740:vgpr_32 = COPY %3.sub13
    %741:vgpr_32 = COPY %3.sub12
    %1568:vreg_128 = REG_SEQUENCE %741, %subreg.sub0, %740, %subreg.sub1, %739, %subreg.sub2, %738, %subreg.sub3
    GLOBAL_STORE_DWORDX4 undef %744:vreg_64, %1568, 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 48, addrspace 1)
    %746:vgpr_32 = COPY %3.sub11
    %747:vgpr_32 = COPY %3.sub10
    %748:vgpr_32 = COPY %3.sub9
    %749:vgpr_32 = COPY %3.sub8
    %1567:vreg_128 = REG_SEQUENCE %749, %subreg.sub0, %748, %subreg.sub1, %747, %subreg.sub2, %746, %subreg.sub3
    GLOBAL_STORE_DWORDX4 undef %752:vreg_64, %1567, 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 32, align 32, addrspace 1)
    %754:vgpr_32 = COPY %3.sub7
    %755:vgpr_32 = COPY %3.sub6
    %756:vgpr_32 = COPY %3.sub5
    %757:vgpr_32 = COPY %3.sub4
    %1566:vreg_128 = REG_SEQUENCE %757, %subreg.sub0, %756, %subreg.sub1, %755, %subreg.sub2, %754, %subreg.sub3
    GLOBAL_STORE_DWORDX4 undef %760:vreg_64, %1566, 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 16, addrspace 1)
    %762:vgpr_32 = COPY %3.sub3
    %763:vgpr_32 = COPY %3.sub2
    %764:vgpr_32 = COPY %3.sub1
    %765:vgpr_32 = COPY %3.sub0
    %1565:vreg_128 = REG_SEQUENCE %765, %subreg.sub0, %764, %subreg.sub1, %763, %subreg.sub2, %762, %subreg.sub3
    GLOBAL_STORE_DWORDX4 undef %768:vreg_64, %1565, 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef`, align 128, addrspace 1)
    %770:vgpr_32 = COPY %4.sub31
    %771:vgpr_32 = COPY %4.sub30
    %772:vgpr_32 = COPY %4.sub29
    %773:vgpr_32 = COPY %4.sub28
    %1564:vreg_128 = REG_SEQUENCE %773, %subreg.sub0, %772, %subreg.sub1, %771, %subreg.sub2, %770, %subreg.sub3
    GLOBAL_STORE_DWORDX4 undef %776:vreg_64, %1564, 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 112, addrspace 1)
    %778:vgpr_32 = COPY %4.sub27
    %779:vgpr_32 = COPY %4.sub26
    %780:vgpr_32 = COPY %4.sub25
    %781:vgpr_32 = COPY %4.sub24
    %1563:vreg_128 = REG_SEQUENCE %781, %subreg.sub0, %780, %subreg.sub1, %779, %subreg.sub2, %778, %subreg.sub3
    GLOBAL_STORE_DWORDX4 undef %784:vreg_64, %1563, 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 96, align 32, addrspace 1)
    %786:vgpr_32 = COPY %4.sub23
    %787:vgpr_32 = COPY %4.sub22
    %788:vgpr_32 = COPY %4.sub21
    %789:vgpr_32 = COPY %4.sub20
    %1562:vreg_128 = REG_SEQUENCE %789, %subreg.sub0, %788, %subreg.sub1, %787, %subreg.sub2, %786, %subreg.sub3
    GLOBAL_STORE_DWORDX4 undef %792:vreg_64, %1562, 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 80, addrspace 1)
    %794:vgpr_32 = COPY %4.sub19
    %795:vgpr_32 = COPY %4.sub18
    %796:vgpr_32 = COPY %4.sub17
    %797:vgpr_32 = COPY %4.sub16
    %1561:vreg_128 = REG_SEQUENCE %797, %subreg.sub0, %796, %subreg.sub1, %795, %subreg.sub2, %794, %subreg.sub3
    GLOBAL_STORE_DWORDX4 undef %800:vreg_64, %1561, 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 64, align 64, addrspace 1)
    %802:vgpr_32 = COPY %4.sub15
    %803:vgpr_32 = COPY %4.sub14
    %804:vgpr_32 = COPY %4.sub13
    %805:vgpr_32 = COPY %4.sub12
    %1560:vreg_128 = REG_SEQUENCE %805, %subreg.sub0, %804, %subreg.sub1, %803, %subreg.sub2, %802, %subreg.sub3
    GLOBAL_STORE_DWORDX4 undef %808:vreg_64, %1560, 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 48, addrspace 1)
    %810:vgpr_32 = COPY %4.sub11
    %811:vgpr_32 = COPY %4.sub10
    %812:vgpr_32 = COPY %4.sub9
    %813:vgpr_32 = COPY %4.sub8
    %1559:vreg_128 = REG_SEQUENCE %813, %subreg.sub0, %812, %subreg.sub1, %811, %subreg.sub2, %810, %subreg.sub3
    GLOBAL_STORE_DWORDX4 undef %816:vreg_64, %1559, 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 32, align 32, addrspace 1)
    %818:vgpr_32 = COPY %4.sub7
    %819:vgpr_32 = COPY %4.sub6
    %820:vgpr_32 = COPY %4.sub5
    %821:vgpr_32 = COPY %4.sub4
    %1558:vreg_128 = REG_SEQUENCE %821, %subreg.sub0, %820, %subreg.sub1, %819, %subreg.sub2, %818, %subreg.sub3
    GLOBAL_STORE_DWORDX4 undef %824:vreg_64, %1558, 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 16, addrspace 1)
    %826:vgpr_32 = COPY %4.sub3
    %827:vgpr_32 = COPY %4.sub2
    %828:vgpr_32 = COPY %4.sub1
    %829:vgpr_32 = COPY %4.sub0
    %1557:vreg_128 = REG_SEQUENCE %829, %subreg.sub0, %828, %subreg.sub1, %827, %subreg.sub2, %826, %subreg.sub3
    GLOBAL_STORE_DWORDX4 undef %832:vreg_64, %1557, 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef`, align 128, addrspace 1)
    %834:vgpr_32 = COPY %5.sub31
    %835:vgpr_32 = COPY %5.sub30
    %836:vgpr_32 = COPY %5.sub29
    %837:vgpr_32 = COPY %5.sub28
    %1556:vreg_128 = REG_SEQUENCE %837, %subreg.sub0, %836, %subreg.sub1, %835, %subreg.sub2, %834, %subreg.sub3
    GLOBAL_STORE_DWORDX4 undef %840:vreg_64, %1556, 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 112, addrspace 1)
    %842:vgpr_32 = COPY %5.sub27
    %843:vgpr_32 = COPY %5.sub26
    %844:vgpr_32 = COPY %5.sub25
    %845:vgpr_32 = COPY %5.sub24
    %1555:vreg_128 = REG_SEQUENCE %845, %subreg.sub0, %844, %subreg.sub1, %843, %subreg.sub2, %842, %subreg.sub3
    GLOBAL_STORE_DWORDX4 undef %848:vreg_64, %1555, 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 96, align 32, addrspace 1)
    %850:vgpr_32 = COPY %5.sub23
    %851:vgpr_32 = COPY %5.sub22
    %852:vgpr_32 = COPY %5.sub21
    %853:vgpr_32 = COPY %5.sub20
    %1554:vreg_128 = REG_SEQUENCE %853, %subreg.sub0, %852, %subreg.sub1, %851, %subreg.sub2, %850, %subreg.sub3
    GLOBAL_STORE_DWORDX4 undef %856:vreg_64, %1554, 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 80, addrspace 1)
    %858:vgpr_32 = COPY %5.sub19
    %859:vgpr_32 = COPY %5.sub18
    %860:vgpr_32 = COPY %5.sub17
    %861:vgpr_32 = COPY %5.sub16
    %1553:vreg_128 = REG_SEQUENCE %861, %subreg.sub0, %860, %subreg.sub1, %859, %subreg.sub2, %858, %subreg.sub3
    GLOBAL_STORE_DWORDX4 undef %864:vreg_64, %1553, 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 64, align 64, addrspace 1)
    %866:vgpr_32 = COPY %5.sub15
    %867:vgpr_32 = COPY %5.sub14
    %868:vgpr_32 = COPY %5.sub13
    %869:vgpr_32 = COPY %5.sub12
    %1552:vreg_128 = REG_SEQUENCE %869, %subreg.sub0, %868, %subreg.sub1, %867, %subreg.sub2, %866, %subreg.sub3
    GLOBAL_STORE_DWORDX4 undef %872:vreg_64, %1552, 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 48, addrspace 1)
    %874:vgpr_32 = COPY %5.sub11
    %875:vgpr_32 = COPY %5.sub10
    %876:vgpr_32 = COPY %5.sub9
    %877:vgpr_32 = COPY %5.sub8
    %1551:vreg_128 = REG_SEQUENCE %877, %subreg.sub0, %876, %subreg.sub1, %875, %subreg.sub2, %874, %subreg.sub3
    GLOBAL_STORE_DWORDX4 undef %880:vreg_64, %1551, 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 32, align 32, addrspace 1)
    %882:vgpr_32 = COPY %5.sub7
    %883:vgpr_32 = COPY %5.sub6
    %884:vgpr_32 = COPY %5.sub5
    %885:vgpr_32 = COPY %5.sub4
    %1550:vreg_128 = REG_SEQUENCE %885, %subreg.sub0, %884, %subreg.sub1, %883, %subreg.sub2, %882, %subreg.sub3
    GLOBAL_STORE_DWORDX4 undef %888:vreg_64, %1550, 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 16, addrspace 1)
    %890:vgpr_32 = COPY %5.sub3
    %891:vgpr_32 = COPY %5.sub2
    %892:vgpr_32 = COPY %5.sub1
    %893:vgpr_32 = COPY %5.sub0
    %1549:vreg_128 = REG_SEQUENCE %893, %subreg.sub0, %892, %subreg.sub1, %891, %subreg.sub2, %890, %subreg.sub3
    GLOBAL_STORE_DWORDX4 undef %896:vreg_64, %1549, 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef`, align 128, addrspace 1)
    %898:vgpr_32 = COPY %6.sub31
    %899:vgpr_32 = COPY %6.sub30
    %900:vgpr_32 = COPY %6.sub29
    %901:vgpr_32 = COPY %6.sub28
    %1548:vreg_128 = REG_SEQUENCE %901, %subreg.sub0, %900, %subreg.sub1, %899, %subreg.sub2, %898, %subreg.sub3
    GLOBAL_STORE_DWORDX4 undef %904:vreg_64, %1548, 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 112, addrspace 1)
    %906:vgpr_32 = COPY %6.sub27
    %907:vgpr_32 = COPY %6.sub26
    %908:vgpr_32 = COPY %6.sub25
    %909:vgpr_32 = COPY %6.sub24
    %1547:vreg_128 = REG_SEQUENCE %909, %subreg.sub0, %908, %subreg.sub1, %907, %subreg.sub2, %906, %subreg.sub3
    GLOBAL_STORE_DWORDX4 undef %912:vreg_64, %1547, 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 96, align 32, addrspace 1)
    %914:vgpr_32 = COPY %6.sub23
    %915:vgpr_32 = COPY %6.sub22
    %916:vgpr_32 = COPY %6.sub21
    %917:vgpr_32 = COPY %6.sub20
    %1546:vreg_128 = REG_SEQUENCE %917, %subreg.sub0, %916, %subreg.sub1, %915, %subreg.sub2, %914, %subreg.sub3
    GLOBAL_STORE_DWORDX4 undef %920:vreg_64, %1546, 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 80, addrspace 1)
    %922:vgpr_32 = COPY %6.sub19
    %923:vgpr_32 = COPY %6.sub18
    %924:vgpr_32 = COPY %6.sub17
    %925:vgpr_32 = COPY %6.sub16
    %1545:vreg_128 = REG_SEQUENCE %925, %subreg.sub0, %924, %subreg.sub1, %923, %subreg.sub2, %922, %subreg.sub3
    GLOBAL_STORE_DWORDX4 undef %928:vreg_64, %1545, 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 64, align 64, addrspace 1)
    %930:vgpr_32 = COPY %6.sub15
    %931:vgpr_32 = COPY %6.sub14
    %932:vgpr_32 = COPY %6.sub13
    %933:vgpr_32 = COPY %6.sub12
    %1544:vreg_128 = REG_SEQUENCE %933, %subreg.sub0, %932, %subreg.sub1, %931, %subreg.sub2, %930, %subreg.sub3
    GLOBAL_STORE_DWORDX4 undef %936:vreg_64, %1544, 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 48, addrspace 1)
    %938:vgpr_32 = COPY %6.sub11
    %939:vgpr_32 = COPY %6.sub10
    %940:vgpr_32 = COPY %6.sub9
    %941:vgpr_32 = COPY %6.sub8
    %1543:vreg_128 = REG_SEQUENCE %941, %subreg.sub0, %940, %subreg.sub1, %939, %subreg.sub2, %938, %subreg.sub3
    GLOBAL_STORE_DWORDX4 undef %944:vreg_64, %1543, 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 32, align 32, addrspace 1)
    %946:vgpr_32 = COPY %6.sub7
    %947:vgpr_32 = COPY %6.sub6
    %948:vgpr_32 = COPY %6.sub5
    %949:vgpr_32 = COPY %6.sub4
    %1542:vreg_128 = REG_SEQUENCE %949, %subreg.sub0, %948, %subreg.sub1, %947, %subreg.sub2, %946, %subreg.sub3
    GLOBAL_STORE_DWORDX4 undef %952:vreg_64, %1542, 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef` + 16, addrspace 1)
    %954:vgpr_32 = COPY %6.sub3
    %955:vgpr_32 = COPY %6.sub2
    %956:vgpr_32 = COPY %6.sub1
    %957:vgpr_32 = COPY %6.sub0
    %1541:vreg_128 = REG_SEQUENCE %957, %subreg.sub0, %956, %subreg.sub1, %955, %subreg.sub2, %954, %subreg.sub3
    GLOBAL_STORE_DWORDX4 undef %960:vreg_64, %1541, 0, 0, implicit $exec :: (volatile store (s128) into `ptr addrspace(1) undef`, align 128, addrspace 1)
    SI_RETURN
...
